Repository alibaba/pouch, pull requests merged in 2018-05, with the labels that each got.

#1260 bugfix: set container env failed Invalid cross-device link
  daemon/mgr/spec_hook.go
  storage/quota/quota.go
Labels: LGTM, kind/bug, size/S

#1263 bugfix: align with existing system
  cli/inspect.go
Labels: LGTM, kind/bug, size/M

#1264 bugfix: compability with alidocker when update container diskquota
  daemon/mgr/container.go
Labels: kind/bug, size/S

#1251 bugfix: fix the mount path of tmpfs volume and some misspells
  daemon/mgr/volume.go
  storage/volume/modules/tmpfs/tmpfs.go
Labels: LGTM, areas/storage, kind/bug, size/XS

#1253 bugfix: fix mountpoint binary not found error
  pkg/utils/mount.go
Labels: LGTM, kind/bug, size/XS

#1255 feature: add "volume" flag when remove container
  apis/server/container_bridge.go
  apis/server/volume_bridge.go
  apis/swagger.yml
  apis/types/container_remove_options.go
  cli/rm.go
  cli/run.go
  client/container_remove.go
  client/container_remove_test.go
  client/interface.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/cri.go
  daemon/mgr/volume.go
  pkg/errtypes/errors.go
  storage/volume/core.go
  storage/volume/types/types.go
  test/cli_rm_test.go
  test/environment/cleanup.go
Labels: LGTM, areas/storage, kind/feature, size/XL

#1261 refactor: facilitate make.sh build
  hack/make.sh
Labels: LGTM, areas/test, kind/refactor, size/L

#1269 bugfix: can't stop a paused container
  daemon/mgr/container.go
  test/api_container_restart_test.go
  test/api_container_stop_test.go
  test/cli_restart_test.go
  test/cli_stop_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/bug, size/L

#1272 bugfix: restart_paused_container ci failed
  test/cli_restart_test.go
Labels: LGTM, areas/test, kind/bug, size/XS

#1267 refactor: image manager
  apis/server/image_bridge.go
  cli/image_list.go
  cli/pull.go
  cli/upgrade.go
  ctrd/image.go
  ctrd/interface.go
  daemon/mgr/container.go
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  daemon/mgr/image.go
  daemon/mgr/image_store.go
  daemon/mgr/image_store_test.go
  daemon/mgr/image_test.go
  daemon/mgr/image_utils.go
  daemon/mgr/image_utils_test.go
  pkg/reference/def.go
  pkg/reference/parse.go
  pkg/reference/parse_test.go
  test/api_image_inspect_test.go
  test/cli_pull_test.go
  test/cli_rmi_test.go
  test/environment/env.go
Labels: kind/refactor, size/XXL

#1240 bugfix: free resource after exec exit
  ctrd/container.go
Labels: LGTM, kind/bug, size/XS

#1170 feature: set volumes to /etc/mtab
  daemon/mgr/container.go
  daemon/mgr/spec_hook.go
Labels: areas/storage, kind/feature, size/M

#1238 enhance: add more field in 'pouch info' command
  daemon/config/config.go
  daemon/mgr/system.go
  internal/generator.go
Labels: LGTM, areas/cli, size/M

#1279 test: make test more robust
  test/api_image_create_test.go
  test/api_system_test.go
  test/api_volume_list_test.go
  test/cli_alikernel_test.go
  test/cli_images_test.go
  test/cli_volume_test.go
  test/util_daemon.go
Labels: areas/test, size/M

#1275 feature: take over old containerd instance when pouchd restart
  ctrd/client.go
  ctrd/client_opts.go
  ctrd/client_test.go
  ctrd/interface.go
  ctrd/wrapper_client.go
  daemon/config/config.go
  daemon/daemon.go
  main.go
  pkg/utils/utils.go
Labels: kind/feature, size/XL

#1283 docs: polish code style document for pouch
  .circleci/config.yml
  docs/contributions/code_styles.md
Labels: LGTM, areas/docs, size/XL

#1286 bugfix: add lock in boltdb
  pkg/meta/boltdb.go
Labels: LGTM, kind/bug, size/S

#1294 test: add -race to go test to detect race
  hack/build
Labels: LGTM, areas/test, size/XS

#1295 docs: add kata-container support docs
  docs/features/pouch_with_kata.md
Labels: LGTM, areas/docs, size/L

#1271 bugfix: change volume metadata struct
  storage/volume/config.go
  storage/volume/core.go
  storage/volume/modules/ceph/ceph.go
  storage/volume/types/storage.go
  storage/volume/types/volume.go
Labels: LGTM, areas/storage, kind/bug, size/S

#1296 refactor: reorder function sequence to make it more reasonable
  apis/server/container_bridge.go
  apis/server/exec_bridge.go
  apis/server/image_bridge.go
  apis/server/network_bridge.go
  apis/server/volume_bridge.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  daemon/mgr/image.go
  daemon/mgr/network.go
  daemon/mgr/volume.go
Labels: LGTM, kind/refactor, size/XXL

#1303 docs: fix typo
  CONTRIBUTING.md
  FAQ.md
  INSTALLATION.md
  README.md
  ROADMAP.md
  docs/README.md
  docs/commandline/README.md
  docs/contributions/code_styles.md
  docs/features/pouch_with_diskquota.md
  docs/features/pouch_with_dragonfly.md
  docs/features/pouch_with_kata.md
  docs/features/pouch_with_lxcfs.md
  docs/features/pouch_with_plugin.md
  docs/features/pouch_with_rich_container.md
  docs/features/pouch_with_runV.md
  docs/kubernetes/pouch_with_cri_introduction.md
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
  docs/test/debug_in_travis.md
  docs/test/test.md
Labels: LGTM, areas/docs, areas/typo, size/L

#1284 bugfix: fix remove all endpoints when network disconnect
  daemon/mgr/network.go
Labels: LGTM, areas/network, kind/bug, size/M

#1300 refactor: eliminate containerMeta in daemon manager
  apis/server/container_bridge.go
  apis/server/image_bridge.go
  ctrd/container.go
  daemon/daemon.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_monitor.go
  daemon/mgr/container_rich_mode.go
  daemon/mgr/container_rich_mode_test.go
  daemon/mgr/container_types.go
  daemon/mgr/container_types_test.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  daemon/mgr/cri_utils_test.go
  daemon/mgr/spec.go
  daemon/mgr/spec_annotations.go
  daemon/mgr/spec_hook.go
  daemon/mgr/spec_linux.go
  daemon/mgr/spec_mount.go
  daemon/mgr/spec_process.go
  daemon/mgr/system.go
Labels: kind/refactor, size/XXL

#1128 bugfix: fix exec not exit with correct exit code
  cli/exec.go
  client/container.go
  client/container_exec.go
  client/interface.go
  test/cli_exec_test.go
Labels: kind/bug, size/L

#1304 feature: add misspell tool to check English words
  .circleci/config.yml
  pkg/errtypes/errors.go
Labels: LGTM, kind/feature, size/S

#1298 feature: init and add base pouchd logs API
  apis/server/container_bridge.go
  apis/server/router.go
  apis/server/utils.go
  apis/swagger.yml
  apis/types/host_config.go
  apis/types/log_config.go
  daemon/config/config.go
  daemon/containerio/jsonfile.go
  daemon/containerio/options.go
  daemon/containerio/raw_file.go
  daemon/logger/jsonfile/encode.go
  daemon/logger/jsonfile/encode_test.go
  daemon/logger/jsonfile/jsonfile.go
  daemon/logger/jsonfile/jsonfile_read.go
  daemon/logger/jsonfile/jsonfile_read_test.go
  daemon/logger/jsonfile/utils.go
  daemon/logger/jsonfile/utils_test.go
  daemon/logger/logmessage.go
  daemon/mgr/container.go
  daemon/mgr/container_logs.go
  daemon/mgr/container_logs_test.go
  daemon/mgr/system.go
  hack/make.sh
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/api_container_logs_test.go
  test/request/request.go
  test/util/goroutine.go
Labels: areas/log, kind/feature, size/XXL

#1313 test: using existing image and fix shell format error
  hack/make.sh
Labels: areas/test, kind/bug, size/L

#1315 bugfix: fix the typo created by previous PR
  daemon/containerio/jsonfile.go
  daemon/logger/jsonfile/jsonfile_read.go
Labels: LGTM, areas/typo, kind/bug, size/XS

#1314 bugfix: mount /sys/fs/cgroup into container
  ctrd/container.go
  daemon/mgr/spec_mount.go
Labels: LGTM, areas/test, kind/bug, size/S

#1317 refactor: move the code about cri out of mgr
  .gitignore
  cri/config/config.go
  cri/service/cri.go
  cri/src/cri.go
  cri/src/cri_network.go
  cri/src/cri_stream.go
  cri/src/cri_types.go
  cri/src/cri_utils.go
  cri/src/cri_utils_test.go
  cri/src/cri_wrapper.go
  daemon/config/config.go
  daemon/daemon.go
  internal/generator.go
Labels: LGTM, kind/refactor, size/L

#1311 bugfix: make the daemon exit happy
  main.go
Labels: LGTM, kind/bug, size/M

#1319 refactor: format topExamples code and add execExample.
  cli/exec.go
  cli/top.go
Labels: LGTM, kind/refactor, size/S

#1318 feature: add timeout handler for execSync in cri part
  cri/src/cri.go
  daemon/containerio/mem_buffer.go
  daemon/containerio/options.go
  daemon/containerio/pipe.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
Labels: kind/feature, size/XL

#1327 test: add missing removal of container
  test/api_container_restart_test.go
Labels: areas/test, size/XS

#1334 test: fix cli_ps_test failed
  test/cli_ps_test.go
Labels: LGTM, areas/test, size/XS

#1330 bugfix: make the jsonfile log friendly
  daemon/containerio/jsonfile.go
  daemon/logger/jsonfile/jsonfile_read_test.go
Labels: LGTM, areas/log, kind/bug, size/XS

#1340 bugfix: move IO part behind to ensure execConfig result assignment before IO closes
  daemon/mgr/container.go
Labels: kind/bug, size/S

#1331 doc: update test.md about how to run test
  docs/test/test.md
Labels: areas/docs, areas/test, size/S

#1341 test: enhance cli related tests
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_help_test.go
  test/cli_inspect_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_pull_test.go
  test/cli_restart_test.go
  test/cli_rich_container_test.go
  test/cli_rm_test.go
  test/cli_rmi_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_top_test.go
  test/cli_unpause_test.go
  test/cli_update_test.go
  test/cli_upgrade_test.go
  test/cli_volume_test.go
Labels: areas/test, size/XL

#1227 feature: add pidslimit implement
  cli/common_flags.go
  cli/container.go
  daemon/mgr/spec_linux.go
  test/cli_create_test.go
  test/cli_run_test.go
  test/cli_start_test.go
Labels: kind/feature, size/M

#1339 Update INSTALLATION.md apt-key fingerprint BE2F475F
  INSTALLATION.md
Labels: size/S

#1326 feature: remote volume driver
  daemon/mgr/volume.go
  plugins/plugins.go
  storage/volume/core.go
  storage/volume/core_util.go
  storage/volume/driver/driver.go
  storage/volume/driver/driver_interface.go
  storage/volume/driver/proxy.go
  storage/volume/driver/remote.go
  storage/volume/driver/types.go
  storage/volume/modules/local/local.go
  storage/volume/types/vars.go
  storage/volume/types/volume.go
  storage/volume/types/volume_util.go
Labels: LGTM, areas/storage, kind/feature, size/XXL

#1350 build: generate version information at build time
  daemon/mgr/system.go
  hack/build
  main.go
  test/cli_version_test.go
  version/version.go
Labels: size/S

#1351 feature: allow use image by digest id
  cri/src/cri.go
  daemon/mgr/container.go
  daemon/mgr/image.go
  daemon/mgr/image_store.go
  daemon/mgr/image_store_test.go
  pkg/reference/parse_test.go
  test/api_image_inspect_test.go
  test/cli_rmi_test.go
  test/environment/env.go
Labels: kind/feature, size/L

#1353 test: fix TestRunWithPidsLimit fail cause no pids cgroup support
  test/cli_run_test.go
Labels: LGTM, areas/test, size/XS

#1352 feature: add volume drivers info for system info
  apis/swagger.yml
  apis/types/system_info.go
  cli/info.go
  daemon/mgr/system.go
  storage/volume/driver/driver.go
  test/api_system_test.go
Labels: LGTM, areas/storage, kind/feature, size/M

#1354 bugfix: remove pids-limit initial value
  cli/common_flags.go
Labels: kind/bug, size/XS

#1361 bugfix: fix cgroup-parent can not set from config
  cli/common_flags.go
Labels: LGTM, kind/bug, size/XS

#1357 feature: enable managing more containers for some commands
  cli/pause.go
  cli/restart.go
  cli/rm.go
  cli/rmi.go
  cli/start.go
  cli/unpause.go
  test/cli_restart_test.go
  test/cli_start_test.go
  test/cli_unpause_test.go
Labels: areas/cli, kind/feature, size/XL

#1364 feature: support update and delete env
  apis/opts/env.go
  apis/opts/env_test.go
  daemon/mgr/container.go
  test/cli_update_test.go
Labels: kind/feature, size/L

#1368 test: add ci tests for volume plugin
  hack/make.sh
  test/api_system_test.go
  test/api_volume_create_test.go
  test/api_volume_list_test.go
  test/cli_volume_test.go
  test/util_api.go
Labels: LGTM, areas/storage, areas/test, size/L

#1338 test: add test coverage for integration test
  .travis.yml
  Makefile
  hack/build
  hack/make.sh
  main_test.go
  test/api_container_exec_inspect_test.go
Labels: areas/test, size/L

#1257 docs: add daemon config file doc
  docs/user/config_file.md
Labels: areas/docs, size/M

#1374 bugfix: add judge for whether pidfile path is given
  main.go
Labels: LGTM, kind/bug, size/S, size/XL

#1359 feature: Update CRI from v1alpha1 to v1alpha2 & support down-level compatibility
  cri/config/config.go
  cri/criservice.go
  cri/stream/request_cache.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_network.go
  cri/v1alpha1/cri_stream.go
  cri/v1alpha1/cri_types.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha1/server.go
  cri/v1alpha1/service/cri.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_network.go
  cri/v1alpha2/cri_stream.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  cri/v1alpha2/cri_wrapper.go
  cri/v1alpha2/server.go
  cri/v1alpha2/service/cri.go
  daemon/daemon.go
  hack/cri-test/test-cri.sh
  hack/cri-test/versions
  internal/generator.go
  main.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/constants.go
Labels: kind/feature, size/XXL

#1384 doc: update doc of pouch with kubernetes deploying
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
Labels: LGTM, areas/docs, areas/orchestration, size/S

#1378 feature: init pouch tag functionality
  apis/server/image_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/main.go
  cli/tag.go
  client/image_tag.go
  client/image_tag_test.go
  client/interface.go
  ctrd/image.go
  ctrd/interface.go
  daemon/mgr/image.go
  daemon/mgr/image_store.go
  test/api_image_tag_test.go
  test/cli_tag_test.go
Labels: LGTM, kind/feature, size/XL

#1382 enhance: replace the default sandbox image for pouchd with google-released image
  hack/cri-test/test-utils.sh
Labels: LGTM, size/XS

#1383 cherry-pick: cherry-pick #1359 from master to 0.5.x
  cri/config/config.go
  cri/criservice.go
  cri/stream/request_cache.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_network.go
  cri/v1alpha1/cri_stream.go
  cri/v1alpha1/cri_types.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha1/server.go
  cri/v1alpha1/service/cri.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_network.go
  cri/v1alpha2/cri_stream.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  cri/v1alpha2/cri_wrapper.go
  cri/v1alpha2/server.go
  cri/v1alpha2/service/cri.go
  daemon/daemon.go
  hack/cri-test/test-cri.sh
  hack/cri-test/versions
  internal/generator.go
  main.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/constants.go
Labels: LGTM, size/XXL

#1386 bugfix: make the PullImage test util work
  test/main_test.go
  test/util_api.go
Labels: LGTM, areas/test, kind/bug, size/M

#1381 cli: add instruction for blkio-weight-device
  apis/swagger.yml
  apis/types/resources.go
  cli/common_flags.go
  test/cli_run_test.go
Labels: LGTM, areas/cli, size/S

#1387 doc: change pouch version from 0.4.0 to 0.5.0-dev
  hack/build
  version/version.go
Labels: LGTM, areas/docs, size/XS

#1394 bugfix: panic when execute exec command with flag -d
  daemon/mgr/container.go
Labels: areas/cli, kind/bug, kind/panic, priority/P1, size/XS

#1404 bugfix: use the stable image ID in test
  test/api_image_inspect_test.go
  test/environment/env.go
Labels: LGTM, areas/test, kind/bug, size/S

#1406 bugfix: use busybox:1.25 instead of busybox:1.28 in cli_tag_test
  test/cli_tag_test.go
  test/utils.go
Labels: LGTM, areas/test, kind/bug, size/S

#1407 bugfix: containerd instance exit may cause container exit
  ctrd/client.go
  ctrd/watch.go
Labels: kind/bug, size/S

#1410 doc: change version to 0.5.0
  hack/build
  version/version.go
Labels: LGTM, areas/docs, size/XS

#1411 Merge 0.5.x to master
  apis/server/image_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/main.go
  cli/tag.go
  client/image_tag.go
  client/image_tag_test.go
  client/interface.go
  ctrd/image.go
  ctrd/interface.go
  daemon/mgr/image.go
  daemon/mgr/image_store.go
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
  hack/build
  hack/cri-test/test-utils.sh
  main.go
  test/api_image_tag_test.go
  test/cli_tag_test.go
  test/utils.go
  version/version.go
Labels: size/XL

#1413 test: sort image list before check
  test/cli_images_test.go
Labels: areas/test, kind/bug, size/S

#1412 feature: travis doesn't run document-only changed commit
  .travis.yml
Labels: LGTM, areas/docs, kind/feature, size/XS

#1414 doc: add 0.5.0 ChangeLog
  CHANGELOG.md
Labels: areas/docs, areas/log, size/L

#1400 enhance: clean the local-persist after integration tests
  hack/make.sh
Labels: LGTM, areas/test, size/S

#1409 bugfix: change the option to set volume size
  apis/server/volume_bridge.go
  apis/swagger.yml
  cli/volume.go
  storage/volume/modules/local/local.go
  test/cli_alikernel_test.go
  test/cli_run_volume_test.go
  test/cli_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/L

#1422 bugfix: we must call Restore container after initialize network Mgr
  daemon/daemon.go
  daemon/mgr/container.go
Labels: LGTM, areas/network, kind/bug, size/S

#1419 bugfix: pull image before run and upgrade
  apis/server/image_bridge.go
  cli/pull.go
  cli/run.go
  cli/upgrade.go
  client/request.go
Labels: kind/bug, size/L

#1430 test: fix a ineffectual assignment
  test/api_container_stop_test.go
Labels: LGTM

#1391 feature: add pouch load functionality
  apis/server/image_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/load.go
  cli/main.go
  client/image_load.go
  client/image_load_test.go
  client/interface.go
  client/request.go
  ctrd/image.go
  ctrd/interface.go
  daemon/mgr/image.go
  daemon/mgr/image_load.go
  pkg/multierror/def.go
  pkg/multierror/def_test.go
  test/api_image_load_test.go
  test/cli_load_test.go
  vendor/github.com/containerd/containerd/images/oci/exporter.go
  vendor/github.com/containerd/containerd/images/oci/importer.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL
