Repository alibaba/pouch, pull requests merged in 2018-06, with the labels that each got.

#1444 docs: update FAQ.md to add kernel version support
  FAQ.md
Labels: areas/docs, size/S

#1403 feature: add container's network files
  apis/swagger.yml
  apis/types/container_config.go
  cli/common_flags.go
  cli/container.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri_utils.go
  daemon/mgr/container.go
  daemon/mgr/spec_mount.go
  test/cli_run_test.go
Labels: LGTM, areas/network, kind/feature, size/XL

#1441 refactor: remove ceph volume plugin
  Makefile
  apis/server/volume_bridge.go
  daemon/mgr/container.go
  daemon/mgr/volume.go
  storage/controlserver/client/client.go
  storage/controlserver/client/errors.go
  storage/controlserver/client/httpcli.go
  storage/controlserver/client/httpcli_test.go
  storage/controlserver/client/url.go
  storage/controlserver/client/url_test.go
  storage/volume/README.md
  storage/volume/config.go
  storage/volume/core.go
  storage/volume/core_util.go
  storage/volume/driver/driver_interface.go
  storage/volume/driver/remote.go
  storage/volume/examples/demo/demo.go
  storage/volume/modules/ceph/ceph.go
  storage/volume/modules/ceph/map.go
  storage/volume/modules/ceph/types.go
  storage/volume/modules/local/local.go
  storage/volume/modules/tmpfs/tmpfs.go
  storage/volume/types/storage.go
  storage/volume/types/volume.go
  storage/volume/types/volume_util.go
  test/api_system_test.go
Labels: areas/storage, kind/refactor, size/XXL

#1447 fix: correct shell script format via shellcheck reports
  .circleci/Dockerfile
  .circleci/config.yml
  hack/cri-test/test-cri.sh
  hack/cri-test/test-utils.sh
  hack/generate-swagger-models.sh
  hack/install_lxcfs_on_centos.sh
  hack/make.sh
  hack/package/deb/build.sh
  hack/package/package.sh
  hack/package/rpm/build.sh
  hack/package/rpm/scripts/after-install.sh
  hack/package/rpm/scripts/after-remove.sh
  hack/package/rpm/scripts/after-trans.sh
  hack/package/rpm/scripts/before-install.sh
  hack/package/rpm/scripts/before-remove.sh
  hack/vagrant/bootstrap.sh
Labels: LGTM, kind/bug, size/XL

#1450 enhance: add more log for creating new objects
  apis/server/container_bridge.go
  apis/server/network_bridge.go
  apis/server/utils.go
  apis/server/volume_bridge.go
Labels: LGTM, areas/log, size/S

#1375 feature: add cgroup resources check
  daemon/mgr/container.go
  daemon/mgr/container_utils.go
  pkg/system/cgroup.go
  pkg/system/cgroup_test.go
Labels: LGTM, kind/feature, size/XL

#1452 refactor: correct hard coding in several shell script
  hack/make.sh
  hack/package/rpm/build.sh
Labels: LGTM, kind/refactor, size/M

#1462 fix: replace DelContainerForceOk with DelContainerForceMultyTime
  test/api_container_create_test.go
  test/api_container_delete_test.go
  test/api_container_exec_create_test.go
  test/api_container_exec_inspect_test.go
  test/api_container_exec_start_test.go
  test/api_container_inspect_test.go
  test/api_container_logs_test.go
  test/api_container_pause_test.go
  test/api_container_rename_test.go
  test/api_container_resize_test.go
  test/api_container_restart_test.go
  test/api_container_start_test.go
  test/api_container_stop_test.go
  test/api_container_wait_test.go
  test/api_image_delete_test.go
  test/util_api.go
Labels: LGTM, kind/bug, size/L

#1461 docs: add docs about lxcfs feature
  docs/features/pouch_with_lxcfs.md
Labels: LGTM, areas/docs, kind/feature, size/S

#1442 docs: add supporting legacy kernels into runV
  docs/features/pouch_with_runV.md
Labels: areas/docs, areas/runv, size/S

#1466 bugfix: set memory swap initial value to 0
  daemon/mgr/container_utils.go
Labels: LGTM, kind/bug, size/S

#1307 feature: update lock policy for container management
  apis/server/image_bridge.go
  ctrd/container.go
  daemon/containerio/jsonfile.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_state.go
  daemon/mgr/container_types.go
  daemon/mgr/spec.go
  test/api_container_logs_test.go
  test/cli_pull_test.go
  test/cli_top_test.go
Labels: LGTM, kind/feature, size/XXL

#1465 docs: better arch to add connection between cri manager and pouchd
  docs/static_files/pouch_ecosystem_architecture.png
Labels: LGTM, areas/docs, size/XS

#1478 feature: add make help into makefile
  Makefile
Labels: LGTM, kind/feature, size/S

#1424 feature: modify defaut bridge mode
  apis/swagger.yml
  apis/types/ip_a_m_config.go
  daemon/config/config.go
  daemon/daemon.go
  daemon/mgr/network.go
  extra/libnetwork/drivers/bridge/port_mapping.go
  extra/libnetwork/drivers/bridge/setup_ipv4.go
  extra/libnetwork/drivers/bridge/setup_verify.go
  main.go
  network/config.go
  network/mode/bridge/bridge.go
  network/mode/bridge/vars.go
Labels: LGTM, kind/feature, size/XL

#1457 test: add more test for container operations
  client/container_attach.go
  client/container_create_test.go
  client/container_exec_test.go
  client/container_logs.go
  client/container_upgrade.go
  client/container_upgrade_test.go
  client/network_connect_test.go
Labels: LGTM, areas/test, size/XL

#1490 bugfix: rename lxcfs to pouch-lxcfs in pouch.rpm
  hack/package/rpm/build.sh
  hack/package/rpm/scripts/after-install.sh
  hack/package/rpm/service/pouch-lxcfs.service
Labels: kind/bug, size/S

#1492 fix: set memory swap double of non-zero memory value
  daemon/mgr/container_utils.go
  daemon/mgr/spec_linux.go
  test/cli_run_memory_test.go
Labels: LGTM, kind/bug, size/S

#1484 hack.build: reduce the size of pouch and pouchd binaries
  hack/build
Labels: LGTM, size/XS

#1495 bugfix: fix the wrong bridge gateway
  network/mode/bridge/bridge.go
Labels: LGTM, kind/bug, size/M

#1496 fix typo in the vendor/README.md
  vendor/README.md
Labels: areas/typo, size/XS

#1366 feature: add runtime config
  cli/info.go
  config/opt/runtime.go
  config/opt/runtime_test.go
  daemon/config/config.go
  daemon/mgr/container.go
  daemon/mgr/system.go
  hack/make.sh
  main.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/feature, size/XL

#1468 if run sandbox failed, clean up; deduplicate the default mounts with user defined ones
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
  daemon/mgr/spec_mount.go
Labels: LGTM, size/M

#1502 fix: support nullable bool value set in config
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: LGTM, kind/bug, size/S

#1471 bugfix: copy data before put it into ringbuf
  daemon/containerio/container_io.go
Labels: LGTM, kind/bug, size/S

#1459 doc: Modify the document about Kubernetes&pouch to make it friendly
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
  hack/kubernetes/allinone.sh
  hack/kubernetes/allinone_aliyun.sh
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto
  vendor/vendor.json
Labels: areas/docs, areas/orchestration, size/XXL

#1507 fix: Make hack/kubernetes/allinone_aliyun.sh to pass shellcheck
  hack/kubernetes/allinone_aliyun.sh
Labels: areas/orchestration, kind/bug, size/XL

#1513 bugfix: restore config after update fail
  daemon/mgr/container.go
Labels: LGTM, kind/bug, priority/P1, size/S

#1472 feature: finish the CLI logs part
  cli/logs.go
  client/container_logs.go
  client/container_logs_test.go
  daemon/logger/jsonfile/utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/api_container_logs_test.go
  test/cli_logs_test.go
Labels: LGTM, areas/log, kind/feature, size/XL

#1521 refactor: return CRI services error
  cri/criservice.go
Labels: kind/bug, kind/refactor, size/M

#1511 feature: UpdateContainerResources of CRI Manager
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
  daemon/mgr/container.go
  daemon/mgr/container_state.go
Labels: LGTM, kind/feature, size/M

#1525 docs: change pouch to PouchContainer
  CHANGELOG.md
  CONTRIBUTING.md
  FAQ.md
  INSTALLATION.md
  README.md
  ROADMAP.md
  apis/README.md
  docs/README.md
  docs/api/HTTP_API.md
  docs/architecture.md
  docs/commandline/README.md
  docs/contributions/code_styles.md
  docs/features/pouch_with_diskquota.md
  docs/features/pouch_with_dragonfly.md
  docs/features/pouch_with_kata.md
  docs/features/pouch_with_lxcfs.md
  docs/features/pouch_with_plugin.md
  docs/features/pouch_with_prometheus.md
  docs/features/pouch_with_rich_container.md
  docs/features/pouch_with_runV.md
  docs/features/pouch_with_tls.md
  docs/kubernetes/pouch_with_cri_introduction.md
  docs/kubernetes/pouch_with_cri_verification.md
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
  docs/test/debug_in_travis.md
  docs/test/test.md
  docs/user/config_file.md
  hack/package/README.md
  hack/vagrant/README.md
  storage/volume/README.md
  vendor/README.md
Labels: LGTM, areas/docs, size/XL

#1440 docs: add more details on rich container
  docs/features/pouch_with_rich_container.md
  docs/static_files/pouch_with_rich_container.png
Labels: LGTM, areas/docs, size/L

#1519 bugfix: fix rpm package bug
  hack/package/rpm/build.sh
Labels: kind/bug, size/XS

#1530 Revert "hack.build: reduce the size of pouch and pouchd binaries"
  hack/build
Labels: LGTM, size/XS

#1538 Revert "feature: add pouch kill functionality"
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/kill.go
  cli/main.go
  client/container_kill.go
  client/container_kill_test.go
  client/interface.go
  ctrd/container.go
  ctrd/interface.go
  daemon/mgr/container.go
  test/api_container_kill_test.go
  test/api_container_pause_test.go
  test/cli_kill_test.go
Labels: LGTM, kind/feature, size/XL

#1533 fix: update cpu-quota of 0.2.4 container may occur error
  cli/update.go
  ctrd/utils.go
  daemon/mgr/container.go
  test/cli_update_test.go
Labels: LGTM, kind/bug, size/M

#1520 bugfix: bind an address for stream server
  cri/v1alpha1/cri_stream.go
  cri/v1alpha2/cri_stream.go
  pkg/net/doc.go
  pkg/net/interface.go
  pkg/net/interface_test.go
Labels: kind/bug, size/XXL

#1514 feature: add update daemon config function
  apis/swagger.yml
  apis/types/registry_service_config.go
  cli/main.go
  cli/update_daemon.go
  client/client.go
  client/daemon_update.go
  client/daemon_update_test.go
  client/interface.go
  cri/config/config.go
  daemon/config/config.go
  main.go
  network/config.go
  network/mode/bridge/bridge.go
  storage/volume/config.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/feature, size/XL

#1541 bugfix: change the order of generating MountPoints
  daemon/mgr/container.go
Labels: kind/bug, size/S

#1539 bugfix: skip teardown network, if the sandbox has been stopped
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: areas/network, kind/bug, size/M

#1483 bugfix: add attach volume when container start
  daemon/mgr/container.go
  daemon/mgr/volume.go
  storage/volume/core.go
  storage/volume/driver/driver_interface.go
  storage/volume/modules/local/local.go
Labels: areas/storage, kind/bug, size/L

#1540 refactor: make code more encapsulate and logic simple
  daemon/mgr/container.go
  daemon/mgr/container_state.go
  daemon/mgr/container_types.go
Labels: areas/log, kind/refactor, size/XL

#1548 bugfix: refine tests with specifying CMD
  test/api_container_logs_test.go
  test/cli_alikernel_test.go
  test/cli_restart_test.go
  test/cli_run_blkio_test.go
  test/cli_run_pid_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_upgrade_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, areas/test, kind/bug, size/M

#1474 feature: support creating container by just specifying rootfs
  ctrd/container.go
  ctrd/container_types.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  pkg/mount/mount.go
  pkg/mount/mount_test.go
Labels: LGTM, areas/test, kind/feature, size/XL

#1500 feature: init syslog functionality in pouchd
  apis/opts/log_options.go
  apis/opts/log_options_test.go
  cli/common_flags.go
  cli/container.go
  daemon/containerio/jsonfile.go
  daemon/containerio/options.go
  daemon/containerio/syslog.go
  daemon/logger/info.go
  daemon/logger/loggerutils/tag.go
  daemon/logger/loggerutils/tag_test.go
  daemon/logger/syslog/const.go
  daemon/logger/syslog/fmt.go
  daemon/logger/syslog/syslog.go
  daemon/logger/syslog/syslog_test.go
  daemon/logger/syslog/validate.go
  daemon/logger/syslog/validate_test.go
  daemon/mgr/container.go
  daemon/mgr/container_logger.go
  daemon/mgr/container_logs.go
  daemon/mgr/container_validation.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/api_container_logs_test.go
  test/cli_create_log_options_test.go
  vendor/github.com/RackSec/srslog/CODE_OF_CONDUCT.md
  vendor/github.com/RackSec/srslog/LICENSE
  vendor/github.com/RackSec/srslog/README.md
  vendor/github.com/RackSec/srslog/constants.go
  vendor/github.com/RackSec/srslog/dialer.go
  vendor/github.com/RackSec/srslog/formatter.go
  vendor/github.com/RackSec/srslog/framer.go
  vendor/github.com/RackSec/srslog/net_conn.go
  vendor/github.com/RackSec/srslog/srslog.go
  vendor/github.com/RackSec/srslog/srslog_unix.go
  vendor/github.com/RackSec/srslog/writer.go
  vendor/vendor.json
Labels: areas/log, kind/feature, size/XXL

#1551 enhance: revise configure file to make travis happy
  .travis.yml
Labels: LGTM, size/XS

#1547 fix: rename cpu-share to cpu-shares in command line
  cli/common_flags.go
  cli/update.go
  daemon/mgr/container_utils.go
  test/cli_restart_test.go
  test/cli_run_cpu_test.go
  test/cli_update_test.go
  test/cli_upgrade_test.go
Labels: LGTM, areas/cli, size/S

#1549 test: add all states container restart validation
  test/cli_restart_test.go
Labels: LGTM, areas/test, size/M

#1554 test: add top command in upgrade test suite
  test/cli_upgrade_test.go
Labels: LGTM, areas/cli, areas/test, size/XS

#1537 feature: add container setting check
  apis/opts/memory_swappiness.go
  apis/opts/memory_swappiness_test.go
  apis/swagger.yml
  apis/types/resources.go
  cli/common_flags.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_utils.go
  test/cli_update_test.go
Labels: kind/feature, size/XL

#1542 feature: support shm size
  apis/opts/shm_size.go
  apis/opts/shm_size_test.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container_utils.go
  daemon/mgr/spec_mount.go
  test/cli_run_test.go
Labels: kind/feature, size/L

#1557 feature: add webhook to notify our friend PouchRobot when circleci fails
  .circleci/config.yml
Labels: LGTM, areas/test, kind/feature, size/XS

#1553 test: add test for different volume sources
  test/cli_run_volume_test.go
  test/util_api.go
Labels: LGTM, areas/storage, areas/test, size/M

#1531 enhance: add volume lock
  storage/volume/README.md
  storage/volume/core.go
Labels: areas/storage, size/L

#1556 bugfix: vendor latest libnetwork for connect panic
  test/cli_network_test.go
  vendor/github.com/docker/libnetwork/sandbox_store.go
  vendor/vendor.json
Labels: LGTM, areas/network, areas/test, kind/bug, kind/panic, priority/P0, size/L

#1561 feature: adjust pouchd unix socket premissions
  apis/server/server.go
  pkg/user/user.go
  pkg/user/user_test.go
Labels: kind/feature, size/L

#1473 bugfix: network not found
  daemon/daemon.go
  daemon/mgr/container.go
  daemon/mgr/network.go
Labels: LGTM, areas/network, kind/bug, size/S

#1569 enhance: add log for create container exec operation for debugging
  apis/server/exec_bridge.go
Labels: areas/log, kind/bug, size/XS

#1572 refactor: refactor container update diskquota type
  apis/plugins/ContainerPlugin.go
  apis/server/container_bridge.go
  apis/swagger.yml
  apis/types/update_config.go
  cli/update.go
  daemon/mgr/container.go
  test/cli_update_test.go
Labels: LGTM, kind/refactor, size/L

#1558 bugfix: make ringbuffer right
  daemon/containerio/container_io.go
  pkg/ringbuff/ringbuff.go
  pkg/ringbuff/ringbuff_test.go
  pkg/ringbuffer/list.go
  pkg/ringbuffer/ringbuff.go
  pkg/ringbuffer/ringbuff_test.go
Labels: LGTM, kind/bug, size/XL

#1552 test: add TestRunMemoryOOM test case
  test/cli_run_memory_test.go
Labels: LGTM, areas/test, size/XS

#1575 enhance: specify container name for exec args
  apis/server/exec_bridge.go
Labels: areas/test, size/XS

#1588 bugfix: remove the blank line
  test/cli_run_memory_test.go
Labels: LGTM, kind/bug, size/XS
