Repository alibaba/pouch, pull requests merged in 2018-10, with the labels that each got.

#2125 feature: support commit image from container
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/container_commit_options.go
  apis/types/container_commit_resp.go
  cli/commit.go
  cli/main.go
  client/container_commit.go
  client/container_commit_test.go
  client/interface.go
  ctrd/image_commit.go
  ctrd/interface.go
  daemon/mgr/container.go
  daemon/mgr/container_commit.go
  daemon/mgr/image.go
  daemon/mgr/image_load.go
  test/api_container_commit_test.go
  test/cli_container_commit_test.go
Labels: kind/feature, size/XXL

#2288 feature: add ineffassign in gometalinter
  .gometalinter.json
  apis/server/container_bridge.go
  cli/events.go
  cli/info.go
  cli/logs.go
  cli/network.go
  cli/version.go
  client/client.go
  client/client_test.go
  cri/stream/httpstream/httpstream_test.go
  ctrd/client.go
  daemon/logger/jsonfile/utils.go
  network/mode/bridge/bridge.go
  pkg/serializer/serialize.go
  pkg/utils/filters/filter.go
  registry/config.go
  storage/volume/core_test.go
  storage/volume/driver/driver.go
  test/api_checkpoint_test.go
  test/api_daemon_update_test.go
Labels: kind/feature, size/M

#2297 bugfix: jsonfile log should be compatible with moby
  daemon/logger/jsonfile/encode.go
  daemon/logger/jsonfile/utils_test.go
Labels: areas/log, kind/bug, size/S

#2301 enhance: cache image size and oci image spec in pouchd
  daemon/mgr/image.go
  daemon/mgr/image_store.go
Labels: LGTM, areas/test, size/L

#2303 feature: add pouch metrics
  apis/metrics/metrics.go
  apis/metrics/unit.go
  apis/server/container_bridge.go
  apis/server/image_bridge.go
  main.go
  test/api_container_metrics_test.go
  test/api_image_metrics_test.go
  test/util_api.go
Labels: LGTM, kind/feature, size/XL

#2308 golint:normalize some codes
  daemon/mgr/container_validation.go
  daemon/mgr/spec.go
  daemon/mgr/spec_linux.go
  daemon/mgr/spec_process.go
  pkg/archive/archive.go
  storage/volume/core.go
Labels: LGTM, size/M

#2306 bugfix: add check for json-file log opt
  daemon/logger/jsonfile/jsonfile.go
  daemon/mgr/container_validation.go
  test/cli_logs_test.go
Labels: areas/log, kind/bug, size/M

#2304 feature: add cri metrics
  apis/metrics/metrics.go
  apis/server/image_bridge.go
  cri/metrics/metrics.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/service/cri.go
  pkg/utils/metrics/metrics.go
  pkg/utils/metrics/unit.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/CHANGELOG.md
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/README.md
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/makefile
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/metric_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/util.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#2292 fix: keep meta data complete
  pkg/meta/local.go
Labels: LGTM, kind/bug, size/S

#2310 bugfix: remove set quota for container meta directory
  daemon/mgr/container.go
  daemon/mgr/container_storage.go
  storage/quota/grpquota.go
  storage/quota/prjquota.go
  storage/quota/quota.go
  test/cli_run_volume_test.go
Labels: LGTM, kind/bug, size/L

#2312 test: modify network test
  test/cli_network_test.go
  test/cli_run_network_test.go
Labels: LGTM, areas/network, areas/test, size/S

#2282 upgrade: upgrade the vendor of cri-o/ocicni
  cri/ocicni/cni_manager.go
  vendor/github.com/containernetworking/cni/CODE-OF-CONDUCT.md
  vendor/github.com/containernetworking/cni/CONTRIBUTING.md
  vendor/github.com/containernetworking/cni/CONVENTIONS.md
  vendor/github.com/containernetworking/cni/DCO
  vendor/github.com/containernetworking/cni/Documentation/cnitool.md
  vendor/github.com/containernetworking/cni/Documentation/spec-upgrades.md
  vendor/github.com/containernetworking/cni/GOVERNANCE.md
  vendor/github.com/containernetworking/cni/MAINTAINERS
  vendor/github.com/containernetworking/cni/README.md
  vendor/github.com/containernetworking/cni/RELEASING.md
  vendor/github.com/containernetworking/cni/ROADMAP.md
  vendor/github.com/containernetworking/cni/SPEC.md
  vendor/github.com/containernetworking/cni/Vagrantfile
  vendor/github.com/containernetworking/cni/cnitool/README.md
  vendor/github.com/containernetworking/cni/cnitool/cnitool.go
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/logo.png
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/cni_args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/version_decoder.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/skel/skel.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/version/legacy_examples/example_runtime.go
  vendor/github.com/containernetworking/cni/pkg/version/legacy_examples/examples.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/github.com/containernetworking/cni/pkg/version/testhelpers/testhelpers.go
  vendor/github.com/containernetworking/cni/pkg/version/version.go
  vendor/github.com/containernetworking/cni/plugins/test/noop/debug/debug.go
  vendor/github.com/containernetworking/cni/plugins/test/noop/main.go
  vendor/github.com/containernetworking/cni/scripts/docker-run.sh
  vendor/github.com/containernetworking/cni/scripts/exec-plugins.sh
  vendor/github.com/containernetworking/cni/scripts/priv-net-run.sh
  vendor/github.com/containernetworking/cni/scripts/release.sh
  vendor/github.com/containernetworking/cni/test.sh
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_unix.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types_windows.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util_unsupported.go
  vendor/vendor.json
Labels: LGTM, areas/network, areas/test, size/XXL

#2261 feature: add logs cli details opt support and add more cli tests
  apis/server/container_bridge.go
  apis/server/utils.go
  cli/logs.go
  client/container_logs.go
  daemon/containerio/jsonfile.go
  daemon/logger/jsonfile/encode.go
  daemon/logger/jsonfile/encode_test.go
  daemon/logger/jsonfile/jsonfile.go
  daemon/logger/jsonfile/jsonfile_read_test.go
  daemon/logger/logmessage.go
  daemon/mgr/container_logs.go
  test/cli_logs_test.go
Labels: areas/log, areas/test, kind/feature, size/XL

#2309 test: api_container_list_test: add filter test
  apis/swagger.yml
  test/api_container_list_test.go
  test/main_test.go
Labels: LGTM, areas/test, size/XL

#2316 refactor: modify the definition of ContainerPlugin interface
  apis/plugins/ContainerPlugin.go
  apis/server/container_bridge.go
  daemon/mgr/container.go
  daemon/mgr/spec_hook.go
Labels: kind/bug, kind/refactor, size/S

#2317 feature: add volume plugin
  apis/plugins/VolumePlugin.go
  daemon/daemon.go
Labels: areas/storage, kind/feature, size/S

#2318 enhance: split the containerd daamon control from ctrd
  ctrd/client.go
  ctrd/client_opts.go
  ctrd/client_test.go
  ctrd/supervisord/config.go
  ctrd/supervisord/daemon.go
  ctrd/supervisord/option.go
  daemon/daemon.go
  vendor/github.com/containerd/containerd/defaults/defaults_unix.go
  vendor/github.com/containerd/containerd/defaults/defaults_windows.go
  vendor/github.com/containerd/containerd/defaults/doc.go
  vendor/vendor.json
Labels: LGTM, containerd-related, size/XXL

#2211 refactor: re-design upgrade feature
  apis/swagger.yml
  apis/types/container_upgrade_config.go
  cli/upgrade.go
  client/container_upgrade.go
  client/interface.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri_utils.go
  ctrd/container.go
  ctrd/container_types.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_upgrade.go
  daemon/mgr/image.go
  pkg/utils/random_string.go
  pkg/utils/random_string_test.go
  test/cli_upgrade_test.go
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/LICENSE
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/vendor.json
Labels: LGTM, kind/design, kind/feature, kind/refactor, size/XXL

#2302 fix: remove fifo path if stdio is not initail
  daemon/containerio/cio.go
Labels: LGTM, kind/bug, size/XS

#2253 package: add bash completion file into rpm
  hack/package/rpm/scripts/after-install.sh
  hack/package/rpm/scripts/after-remove.sh
Labels: size/S

#2320 refactor: several change
  apis/server/exec_bridge.go
  apis/server/log_filter_writer.go
  apis/server/server.go
  daemon/mgr/container_utils.go
Labels: kind/refactor, size/M

#2319 enhance: add retry helper method for Trylock
  ctrd/container.go
  ctrd/container_lock.go
  ctrd/container_lock_test.go
Labels: LGTM, containerd-related, size/L

#2323 ci: output log when install criu
  hack/install/install_criu.sh
Labels: areas/log, areas/test, size/XS

#2334 test: api_devicemappings_and_mountpoint_test: add new checkpoints
  apis/opts/devicemappings_test.go
  apis/opts/mountpoint_test.go
Labels: areas/test, size/XS

#2332 test: api_ports_test: add new checkpoints
  apis/opts/ports_test.go
Labels: areas/test, size/S

#2331 test: api_add_restart_policy_test: add new checkpoints
  apis/opts/restart_policy_test.go
Labels: areas/test, size/S

#2326 bugfix: put sandbox into store after created to avoid uncontrolled sandbox container
  cri/v1alpha2/cri.go
Labels: kind/bug, size/M

#2340 [bugfix]: update the branch of cri-tools has been updated
  hack/install/install_critest.sh
Labels: kind/bug, size/XS

#2321 Upgrade: Bump to Go 1.10.4
  .circleci/config.yml
  .travis.yml
  Makefile
  Vagrantfile
  apis/opts/config/blkio_test.go
  apis/opts/intel_rdt_test.go
  apis/opts/networks_test.go
  apis/opts/portbindings_test.go
  cli/inspect/inspector_test.go
  client/client_test.go
  client/container_commit_test.go
  client/container_upgrade_test.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  daemon/containerio/cache_test.go
  daemon/mgr/container_commit.go
  daemon/mgr/container_envs_test.go
  daemon/mgr/container_types.go
  pkg/exec/command_test.go
  pkg/httputils/client_test.go
  pkg/httputils/http_utils_test.go
  pkg/mount/mount_test.go
  pkg/reference/regexp_test.go
  pkg/scheduler/scheduler_test.go
  storage/volume/examples/demo/demo.go
Labels: LGTM, size/XL

#2324 refactor: refact daemon log
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha2/cri_wrapper.go
  storage/quota/quota.go
Labels: areas/log, kind/refactor, size/M

#2344 docs: fix usage in `Run pouch command with non-root users`
  INSTALLATION.md
Labels: LGTM, areas/cli, areas/docs, size/XS

#2342 test: mv the start cli test into own test file
  test/cli_start_test.go
  test/cli_stop_test.go
Labels: LGTM, areas/test, size/S

#2338 bugfix: can't allow attach in non-tty client when container in ttyMode
  cli/start.go
  test/cli_start_test.go
Labels: kind/bug, size/M

#2348 bugfix: not remove the metadata when remove container failed
  cri/v1alpha2/cri.go
Labels: LGTM, kind/bug, size/XS

#2354 test: fix some integration tests which haven't deleted containers created before
  test/api_container_list_test.go
  test/api_version_parameter_test.go
Labels: areas/test, size/XS

#2347 bugfix: distinct init process exit and exec process exit
  apis/swagger.yml
  ctrd/client.go
  test/cli_events_test.go
Labels: LGTM, kind/bug, size/L

#2353 bugfix: can't allow run cmd attach ttyMode container from a non-tty c…
  cli/run.go
  test/cli_run_test.go
Labels: LGTM, kind/bug, size/S

#2352 test: add testcase for cli exec -i opt
  test/cli_exec_test.go
Labels: LGTM, areas/test, size/S

#2355 fix dead code and clean code format
  apis/opts/mountpoint.go
  apis/opts/mountpoint_test.go
Labels: LGTM, areas/storage, size/XL

#2364 bugfix: judge enablement of libnetwork resolver by network mode
  daemon/mgr/container.go
  daemon/mgr/network_utils.go
  test/cli_run_dns_test.go
Labels: LGTM, areas/network, kind/bug, size/L

#2346 doc: add document pouch_with_upgrade.md
  docs/features/pouch_with_upgrade.md
  docs/static_files/pouch_with_upgrade.png
Labels: LGTM, areas/docs, size/L

#2366 test: Add the unit-test called `APIContainerStopSuite.TestInvalidParam`
  test/api_container_stop_test.go
Labels: LGTM, areas/api, areas/test, size/S

#2370 test: make stopInWrong test complete
  test/cli_stop_test.go
Labels: areas/test, size/XS

#2349 test: api_network_test: add new check points
  apis/opts/networks.go
  apis/opts/networks_test.go
Labels: LGTM, areas/network, areas/test, size/XL

#2372 test: refactor the cli stop test
  test/cli_stop_test.go
  test/utils.go
Labels: LGTM, areas/test, kind/refactor, size/L

#2374 feature: add no-trunc flag for pouch images
  cli/image_list.go
  test/cli_images_test.go
Labels: kind/feature, size/M

#2382 docs: update `CriEnabled` field in the doc of deploy kubernetes with PouchContainer
  docs/kubernetes/pouch_with_kubernetes_deploying.md
Labels: LGTM, areas/docs, areas/orchestration, size/XS

#2385 test: refactor the test code use inspect func
  test/cli_create_test.go
  test/cli_ps_test.go
  test/cli_rich_container_test.go
  test/cli_run_blkio_test.go
  test/cli_run_cgroup_test.go
  test/cli_run_memory_test.go
  test/cli_run_pid_test.go
  test/cli_run_test.go
  test/cli_run_working_dir_test.go
  test/cli_start_test.go
  test/cli_update_test.go
  test/cli_upgrade_test.go
Labels: LGTM, areas/test, kind/refactor, size/XL
