Repository alibaba/pouch, pull requests merged in 2018-08, with the labels that each got.

#2028 bug: fix judgement for SetRootfsDiskQuota
  storage/quota/quota.go
Labels: kind/bug, size/XS

#1948 BJ266-4: add unit-test for getAppArmorSecurityOpts&getSeccompSecurityOpts , fix #1913
  cri/v1alpha1/cri_utils_test.go
Labels: areas/test, size/L

#2023 test: add unit-test for getSELinuxSecurityOpts method which locate on cri/v…
  cri/v1alpha1/cri_utils_test.go
Labels: areas/test, gap/needs-rebase, size/S

#1892 test: unit test for cri/stream/httpstream/httpstream.go
  cri/stream/httpstream/httpstream_test.go
Labels: areas/test, size/L

#1976 BJ266-4: Add unit-test for apis/opts/ports.go, fix #1906
  apis/opts/ports_test.go
Labels: areas/test, size/S

#1990 Test_imageToCriImage
  cri/v1alpha1/cri_utils_test.go
Labels: areas/test, size/XL

#2002 test: add unit-test for toCriSandbox
  cri/v1alpha1/cri_utils_test.go
Labels: areas/test, gap/needs-rebase, size/L

#1895 test: add test cases about parse object
  cri/v1alpha2/cri_utils_test.go
Labels: areas/test, size/XL

#2031 bugfix: cri Test_getSELinuxSecurityOpts
  cri/v1alpha1/cri_utils_test.go
Labels: areas/test, kind/bug, size/S

#1925 bugfix: data race in pkg cri/stream
  cri/stream/portforward/httpstream.go
Labels: kind/bug, size/S

#1615 feature: add memory cgroup check when validate config
  daemon/mgr/container_utils.go
  test/cli_run_memory_test.go
  test/cli_run_test.go
  test/environment/env.go
Labels: gap/needs-rebase, size/M

#2041 bugfix: cpu params json name compatibility with moby
  apis/swagger.yml
  apis/types/registry_service_config.go
  apis/types/resources.go
Labels: LGTM, kind/bug, size/L

#2035 bugfix: failed to start container when /etc/mtab is symbol link
  .travis.yml
  daemon/mgr/spec_hook.go
  test/cli_run_test.go
Labels: kind/bug, priority/P1, size/S

#1768 test: add unit test for generateMountBindings and modifySandboxNamespaceOptions
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/test, size/XL

#2044 bugfix: fix stdin hang when `kubectl exec`
  cri/stream/runtime.go
Labels: kind/bug, size/XS

#1730 refactor: merge different validate funtions
  daemon/mgr/container.go
  daemon/mgr/container_logger.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_validation.go
Labels: kind/refactor, size/XL

#2049 bugfix: fast fail if the exit code of script is not zero
  .travis.yml
Labels: kind/bug, size/S

#2054 bugfix: makeup logpath from sandbox & container mata
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/log, kind/bug, size/L

#2039 test: add test cases about toCriContainer
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/test, size/XL

#2050 test: add test cases about toCNIPortMappings
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/network, areas/test, size/XL

#2048 test: fix typo in TestAliKernelDiskQuotaWorks
  test/cli_alikernel_test.go
Labels: areas/test, areas/typo, size/XS

#1923 bugfix: fix panic for AttachVolume unittests
  storage/volume/types/volume_util.go
Labels: LGTM, areas/storage, areas/test, kind/bug, kind/panic, priority/P1, size/XS

#1688 test: add unit-tests for core AttachVolume
  storage/volume/core_test.go
Labels: areas/storage, areas/test, size/M

#2027 refactor: rm deadcode in storage/volume
  storage/volume/core_util.go
  storage/volume/driver/types.go
  storage/volume/types/vars.go
Labels: areas/storage, kind/refactor, size/M

#2055 refactor: add more error information
  daemon/mgr/container.go
  storage/quota/grpquota.go
  storage/quota/prjquota.go
Labels: LGTM, kind/bug, kind/refactor, size/XL

#2056 test: add test cases about modifyHostConfig
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/test, size/XL

#2063 feature: support resize the tty of cri exec process
  cri/stream/config.go
  cri/stream/remotecommand/exec.go
  cri/stream/remotecommand/httpstream.go
  cri/stream/runtime.go
  ctrd/container.go
  ctrd/interface.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
Labels: kind/feature, size/XL

#2053 feature: support event service
  apis/filters/parse.go
  apis/filters/parse_test.go
  apis/swagger.yml
  apis/types/event_type.go
  apis/types/events_actor.go
  apis/types/events_message.go
  daemon/events/events.go
  daemon/events/events_test.go
  daemon/events/filter.go
  daemon/events/filter_test.go
Labels: kind/feature, size/XXL

#2062 test: add test cases about modifyContainerConfig&containerNetns
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/test, size/XL

#2059 bash completion: first commit for bash completion
  .gitignore
  INSTALLATION.md
  contrib/completion/bash/pouch
Labels: size/XXL

#2034 bugfix: convert container err into pouchd manager error
  apis/swagger.yml
  ctrd/container.go
  ctrd/image.go
  ctrd/utils.go
  ctrd/utils_test.go
  test/api_container_start_test.go
Labels: kind/bug, size/XL

#1951 test: add unit-test for apis/opts/portbindings.go
  apis/opts/portbindings_test.go
Labels: areas/test, size/XS

#2029 feature: support nvidia-container 2.0 to enable GPU access
  apis/swagger.yml
  apis/types/nvidia_config.go
  apis/types/resources.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container_validation.go
  daemon/mgr/container_validation_test.go
  daemon/mgr/spec_hook.go
  daemon/mgr/spec_process.go
  hack/package/rpm/build.sh
  test/api_container_create_test.go
  test/cli_create_test.go
Labels: kind/feature, size/XL

#1898 feature: complete the funtion of runtime status
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: kind/feature, size/M

#2068 feature: lazy connect to syslog server
  daemon/logger/syslog/conn.go
  daemon/logger/syslog/const.go
  daemon/logger/syslog/dialer.go
  daemon/logger/syslog/syslog.go
  daemon/logger/syslog/syslog_test.go
  daemon/logger/syslog/test/ca-key.pem
  daemon/logger/syslog/test/ca.pem
  test/cli_run_syslog_test.go
Labels: LGTM, areas/log, kind/feature, size/XXL

#2038 docs: add adoptors.md for PouchContainer project
  adoptors.md
  docs/static_files/adoptors_logo/AlibabaCloud.png
  docs/static_files/adoptors_logo/AlibabaGroup.jpg
  docs/static_files/adoptors_logo/AntFinancial.png
  docs/static_files/adoptors_logo/CaiNiao.gif
  docs/static_files/adoptors_logo/HarmonyCloud.png
  docs/static_files/adoptors_logo/amap.png
  docs/static_files/adoptors_logo/cloudj.png
  docs/static_files/adoptors_logo/didi.png
  docs/static_files/adoptors_logo/iFLYTEK.png
  docs/static_files/adoptors_logo/lazada.png
Labels: areas/docs, size/S

#2072 api: checkpoint api optimization
  apis/server/container_bridge.go
  apis/swagger.yml
  client/container_start.go
  daemon/mgr/container_checkpoint.go
  test/api_checkpoint_test.go
  test/api_container_start_test.go
  test/util_api.go
Labels: LGTM, size/L

#2065 feature: update the version of cri-o/ocicni
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/vendor.json
Labels: areas/network, areas/test, gap/needs-rebase, kind/feature, size/M

#2075 bugfix: remove blobs and snapshot when remove image
  ctrd/image.go
Labels: kind/bug, size/XS

#2091 docs: update pull request template about test
  .github/PULL_REQUEST_TEMPLATE.md
Labels: LGTM, areas/docs, areas/test, size/XS

#2078 bugfix: do umount rootfs when failed to operate volumes
  daemon/mgr/container.go
Labels: LGTM

#2092 cgroup: enable memory swappiness equal to -1
  apis/opts/memory_swappiness.go
  apis/opts/memory_swappiness_test.go
  daemon/mgr/container_validation.go
  daemon/mgr/spec_linux.go
  test/cli_run_memory_test.go
  test/environment/env.go
Labels: LGTM, size/S

#2089 test: add unit test for storage module
  storage/volume/driver/driver.go
  storage/volume/driver/driver_test.go
  storage/volume/driver/proxy_test.go
Labels: LGTM, areas/storage, areas/test, size/XL

#2093 refactor: reduce repeat validate code
  apis/opts/cpu.go
  apis/opts/cpu_test.go
  apis/opts/intel_rdt.go
  apis/opts/memory_swap.go
  apis/opts/memory_swappiness.go
  apis/opts/memory_swappiness_test.go
  apis/opts/oom_score.go
  apis/opts/oom_score_test.go
  apis/opts/spec_annotation.go
  cli/container.go
Labels: LGTM, kind/refactor, size/XL

#2085 feature: support runtime args
  daemon/config/config.go
  daemon/daemon.go
  daemon/daemon_utils.go
  daemon/daemon_utils_test.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_utils.go
Labels: LGTM, kind/feature, size/XL

#2087 bugfix: populate volume error
  daemon/mgr/container_storage.go
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: LGTM, areas/storage, size/XL, volume

#2080 bugfix: fix that ContainerManager.Create wouldn't remove snapshot when failed
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/S

#1589 enhance: display network sandbox info for debug
  apis/server/container_bridge.go
Labels: LGTM, areas/network, gap/needs-rebase, kind/bug, size/XS

#2073 bugfix: avoid the deadlock when failed to remove invalid sandbox
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
Labels: kind/bug, size/L

#2098 bugfix: skip empty container dirs
  daemon/mgr/container_storage.go
  pkg/meta/local.go
Labels: kind/bug, size/XS

#2096 bugfix: use image reference during ContainerStatus
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: kind/bug, size/S

#2100 bugfix: make rpm package script works
  .travis.yml
  Makefile
  hack/package/rpm/build.sh
Labels: kind/bug, size/M

#2107 docs: fix wrong link of pouchd config
  docs/user/config_file.md
Labels: LGTM, areas/docs, size/XS

#2104 bugfix: fix meta store return all item when empty prefix
  pkg/meta/store.go
  pkg/meta/store_test.go
Labels: LGTM, kind/bug, size/M

#2057 fix: make iterateTLSConfig only work for TLS config
  daemon/config/config.go
  daemon/config/config_test.go
Labels: gap/needs-rebase, kind/bug, size/M

#2109 bugfix: return error when remove/stop containers of sandbox failed
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: kind/bug, size/XS

#2106 refactor: support specify Namespace by user
  daemon/config/config.go
  daemon/daemon.go
  daemon/mgr/container.go
  main.go
Labels: areas/test, kind/refactor, size/S

#2111 Revert "fix: make iterateTLSConfig only work for TLS config"
  daemon/config/config.go
  daemon/config/config_test.go
Labels: LGTM, kind/bug, size/M

#2117 bugfix: extend reference separator
  pkg/reference/parse_test.go
  pkg/reference/regexp.go
Labels: kind/bug, size/S

#2121 [bugfix] we should parse env params when create container
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
Labels: LGTM, kind/bug, size/XL

#2123 bugfix: fail to execute repquota
  storage/quota/quota.go
Labels: LGTM, kind/bug, size/XS

#2120 bugfix: can't use sudo command
  daemon/mgr/container_types.go
  daemon/mgr/spec.go
  pkg/user/user.go
Labels: LGTM, areas/cli, kind/bug, size/M

#2110 docs: add runtime format in config doc
  docs/features/pouch_with_kata.md
  docs/features/pouch_with_runV.md
  docs/user/config_file.md
Labels: LGTM, areas/docs, size/M

#2105 feature: add exec resize router
  apis/server/exec_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/history_result_item.go
Labels: kind/feature, size/L

#2102 feature: add disk quota for container metadata directory
  daemon/mgr/container.go
  daemon/mgr/container_storage.go
  storage/quota/quota.go
  test/cli_run_volume_test.go
Labels: LGTM, kind/feature, size/XL

#2131 test: make Test_mergeEnvSlice test case happy
  daemon/mgr/container_utils_test.go
Labels: LGTM, areas/test, kind/bug, size/XS

#2133 bugfix: can't quota on disk quota
  storage/quota/grpquota.go
  storage/quota/prjquota.go
Labels: LGTM, kind/bug, size/S

#2127 bugfix: fix failed to run a container with specifying a non-exist workdir
  daemon/mgr/container_exec.go
  daemon/mgr/container_storage.go
  test/cli_exec_test.go
  test/cli_run_working_dir_test.go
Labels: LGTM, areas/test, kind/bug, size/XL

#2119 bugfix: fix that list volumes sets hostname as default label filter
  daemon/mgr/volume.go
Labels: LGTM, areas/storage, kind/bug, size/XS

#2112 feature: add stats api in daemon side
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/blkio_stat_entry.go
  apis/types/blkio_stats.go
  apis/types/container_stats.go
  apis/types/cpu_stats.go
  apis/types/cpu_usage.go
  apis/types/memory_stats.go
  apis/types/network_stats.go
  apis/types/pids_stats.go
  apis/types/registry_service_config.go
  apis/types/throttling_data.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri_utils.go
  ctrd/container.go
  daemon/mgr/container.go
  daemon/mgr/container_stats.go
  daemon/mgr/container_types.go
Labels: areas/api, kind/feature, size/XXL

#2130 bugfix: attach hanging of cri container
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
Labels: kind/bug, size/M

#2030 test: add test cases about CRI image
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/kubernetes, areas/test, gap/needs-rebase, size/XL

#2140 test: make TestRunWithWorkingDir test case happy
  test/cli_run_working_dir_test.go
Labels: LGTM, areas/test, size/XS

#2141 bugfix: fix runtime script may be coverd
  daemon/mgr/container_utils.go
Labels: kind/bug, size/XS

#2142 docs: add disk quota requirement restriction to be much more clear
  docs/features/pouch_with_diskquota.md
Labels: LGTM, areas/docs, areas/storage, size/S

#2138 feature: extend cri apis for support quotaID
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/v1alpha2/cri.go
Labels: LGTM, kind/feature, size/XXL

#2139 bugfix: distinguish NotFound error with others about image
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
Labels: LGTM, kind/bug, size/M

#2145 release: release 1.0.0-rc2 version
  Makefile
  version/version.go
Labels: LGTM, size/XS

#2124 feature: extend cri apis for remove volume
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/criservice.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_wrapper.go
  cri/v1alpha2/service/cri.go
  daemon/daemon.go
  hack/protoc.sh
Labels: areas/storage, kind/feature, size/XXL

#2132 bugfix: cannot get restartCount and let restartCount++ after restart container
  apis/server/container_bridge.go
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/S

#2151 bugfix: handle the error returned by SandboxStore.Put
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: LGTM, kind/bug, size/XS

#2147 style: format cri logs
  cri/criservice.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha2/cri_wrapper.go
Labels: LGTM, areas/log, size/XL

#2157 enhance: clean filepath in mountpoint
  apis/opts/mountpoint.go
  daemon/mgr/container_storage.go
Labels: LGTM, size/S

#2156 bugfix: missing merge some config from image
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_types_test.go
Labels: kind/bug, size/XL

#2161 config: remove check unknow flag in config file
  daemon/config/config.go
  daemon/config/config_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, size/L

#2165 refactor: delete update specific code
  apis/plugins/ContainerPlugin.go
  daemon/mgr/container.go
Labels: LGTM, areas/test, kind/refactor, size/S

#2159 docs: add CRI enhancement into document
  docs/kubernetes/pouch_cri_api_changelog.md
Labels: LGTM, areas/docs, areas/kubernetes, size/XL

#2154 bugfix: set device limit by the mountpoint
  storage/quota/grpquota.go
  storage/quota/prjquota.go
  storage/quota/quota.go
Labels: LGTM, kind/bug, size/XL

#2169 add timeout for curl to prevent from hanging
  test/cli_network_test.go
Labels: size/XS

#2152 bugfix: avoid data race in set exec exit status
  ctrd/container.go
  daemon/mgr/container_exec.go
  test/cli_exec_test.go
Labels: LGTM, kind/bug, size/S

#2163 feature: extend cri apis for get envs
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  docs/kubernetes/pouch_cri_api_changelog.md
Labels: LGTM, kind/feature, size/XXL

#2148 feature: add cgroupfs in Info API
  daemon/config/config.go
  daemon/mgr/system.go
  test/api_system_test.go
Labels: LGTM, kind/feature, size/S

#2175 test: install criu in ci test
  Makefile
  hack/install/install_criu.sh
  hack/install/install_runc.sh
  hack/make.sh
  test/cli_start_test.go
Labels: areas/test, size/M

#2168 Add vagrant support for pouch
  VAGRANT.md
  Vagrantfile
  hack/vagrant/.gitignore
  hack/vagrant/README.md
  hack/vagrant/Vagrantfile
  hack/vagrant/bootstrap.sh
Labels: size/XL

#2183 package: update runc version
  hack/package/deb/Makefile
Labels: size/XS

#2184 release: General availability
  Makefile
  version/version.go
Labels: LGTM, size/XS

#2186 test: remove the criu install from package dependency
  Makefile
  daemon/mgr/container_exec.go
  hack/install/install_criu.sh
Labels: LGTM, areas/test, size/S

#2189 release: update version to 1.0.0
  hack/build
Labels: LGTM, size/XS

#2187 release: update CHANGELOG.md for 1.0.0
  .travis.yml
  CHANGELOG.md
Labels: areas/log, size/M
