Repository alibaba/pouch, pull requests merged in 2018-02, with the labels that each got.

#698 docs: add volume readme
  docs/static_files/pouch_volume_architecture.png
  volume/README.md
Labels: LGTM, areas/docs, areas/storage, size/L

#724 test: add blk test cases
  cli/blkio.go
  cli/blkio_test.go
Labels: LGTM, areas/test, size/XXL

#723 refactor: split parse function pass single parameter
  cli/container.go
  cli/container_test.go
Labels: LGTM, kind/refactor, size/L

#580 feature: framework of cni
  cri/config.go
  cri/service/cri.go
  daemon/config/config.go
  daemon/daemon.go
  daemon/mgr/cri.go
  daemon/mgr/cri_network.go
  daemon/mgr/cri_utils.go
  hack/make.sh
  internal/generator.go
  main.go
  vendor/github.com/containernetworking/cni/LICENSE
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/find.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_windows.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/version/conf.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/github.com/containernetworking/cni/pkg/version/reconcile.go
  vendor/github.com/containernetworking/cni/pkg/version/version.go
  vendor/github.com/cri-o/ocicni/LICENSE
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/util.go
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/vendor.json
Labels: areas/network, kind/feature, size/XXL

#726 test: add unit test cases for safe map in pkg
  pkg/collect/safe_map.go
  pkg/collect/safe_map_test.go
Labels: LGTM, areas/test, size/XL

#729 test: add unit test for container lock
  ctrd/container_lock.go
  ctrd/container_lock_test.go
Labels: LGTM, areas/test, size/M

#731 test: fix network test wrong usage
  test/api_network_create.go
  test/api_network_inspect_test.go
  test/api_network_list_test.go
  test/cli_network_test.go
  test/utils.go
Labels: LGTM, areas/network, areas/test, size/L

#737 test: add unit test for network
  cli/volume_test.go
  daemon/mgr/network_test.go
Labels: areas/network, areas/test, size/L

#736 add -y option to avoid interrupt automation
  hack/make.sh
Labels: size/XS

#733 test: add cache test unit test
  daemon/containerio/cache_test.go
  test/api_network_create_test.go
  test/api_network_delete_test.go
Labels: LGTM, areas/test, size/L

#722 feature: user configuration for cri manager
  cli/container.go
  cli/create.go
  cli/run.go
  daemon/mgr/container.go
  daemon/mgr/cri_utils.go
  daemon/mgr/spec_process.go
  hack/cri-test/test-cri.sh
  test/cli_create_test.go
  test/cli_run_test.go
  test/cli_start_test.go
Labels: LGTM, kind/feature, size/L

#738 feature: add context in pouch cli
  cli/create.go
  cli/exec.go
  cli/image_inspect.go
  cli/image_list.go
  cli/inspect.go
  cli/network.go
  cli/pause.go
  cli/ps.go
  cli/pull.go
  cli/rename.go
  cli/rm.go
  cli/rmi.go
  cli/run.go
  cli/start.go
  cli/stop.go
  cli/unpause.go
  cli/version.go
  cli/volume.go
  client/container.go
  client/image.go
  client/network.go
  client/request.go
  client/system.go
  client/volume.go
  test/cli_images_test.go
  test/environment/cleanup.go
Labels: LGTM, kind/feature, size/XL

#741 fix: make no quote in .travis.yml to enable CI failure notification
  .travis.yml
Labels: LGTM, areas/test, kind/bug, size/XS

#727 test: add unit test for container utils
  daemon/mgr/container.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
Labels: LGTM, areas/test, size/XL

#742 feature: support IntelRdtL3Cbm in pouch container
  cli/container.go
  cli/container_test.go
  cli/create.go
  cli/run.go
  daemon/mgr/spec.go
  daemon/mgr/spec_linux.go
  test/cli_create_test.go
Labels: kind/feature, size/M

#743 feature: add container memory isolation options
  apis/swagger.yml
  apis/types/resources.go
  cli/container.go
  cli/create.go
  cli/run.go
  daemon/mgr/spec.go
  daemon/mgr/spec_alios.go
  test/api_container_create_test.go
  test/cli_create_test.go
Labels: LGTM, kind/feature, size/XL

#678 refactor: combine command run and create's flags
  cli/common_flags.go
  cli/create.go
  cli/run.go
  docs/commandline/pouch_create.md
  docs/commandline/pouch_run.md
Labels: areas/cli, kind/refactor, size/XL

#725 feature: add local disk quota
  apis/server/volume_bridge.go
  cli/cli.go
  daemon/mgr/container.go
  daemon/mgr/volume.go
  pkg/bytefmt/bytefmt.go
  pkg/exec/command.go
  vendor/code.cloudfoundry.org/bytefmt/LICENSE
  vendor/code.cloudfoundry.org/bytefmt/NOTICE
  vendor/code.cloudfoundry.org/bytefmt/README.md
  vendor/code.cloudfoundry.org/bytefmt/package.go
  vendor/vendor.json
  volume/core_util.go
  volume/modules/local/grpquota.go
  volume/modules/local/local.go
  volume/modules/local/prjquota.go
  volume/modules/local/quota.go
  volume/types/volume.go
  volume/vars.go
Labels: LGTM, kind/feature, size/XXL

#730 feature: port mapping for cri manager
  daemon/mgr/cri.go
  daemon/mgr/cri_network.go
  daemon/mgr/cri_utils.go
  hack/cri-test/test-cri.sh
Labels: kind/feature, size/L

#728 feature: remove endpoint when container stop
  apis/server/container_bridge.go
  cli/container.go
  daemon/mgr/container.go
  daemon/mgr/network.go
  network/mode/init.go
Labels: LGTM, kind/feature, size/L

#740 refactor: abstract common api client
  cli/cli.go
  client/client.go
  client/container.go
  client/image.go
  client/interface.go
  test/main_test.go
  test/request/request.go
Labels: LGTM, kind/refactor, size/L

#749 docs: add pouch with lxcfs document
  docs/features/pouch_with_lxcfs.md
  docs/static_files/pouch_with_lxcfs.png
Labels: areas/docs, size/M

#746 fix: change specific names into annotation
  daemon/mgr/spec.go
  daemon/mgr/spec_alios.go
  daemon/mgr/spec_annotations.go
Labels: areas/test, kind/bug, size/M

#732 test: add cleanup for test
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_images_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_unpause_test.go
Labels: LGTM, areas/test, size/L

#734 feature: support login registry
  apis/server/router.go
  apis/server/system_bridge.go
  apis/swagger.yml
  apis/types/auth_config.go
  apis/types/auth_response.go
  cli/login.go
  cli/main.go
  client/interface.go
  client/system.go
  daemon/mgr/system.go
  pkg/term/term.go
  registry/auth.go
  registry/auth_challenge.go
  registry/config.go
Labels: areas/log, kind/feature, size/XXL

#756 bugfix: fix create volume failed but metadata is stored
  volume/core.go
Labels: LGTM, areas/storage, kind/bug, size/S

#765 test: add unit test for bytefmt
  pkg/bytefmt/bytefmt_test.go
Labels: LGTM, areas/test, size/XL

#710 doc: install pouch on ubuntu
  INSTALLATION.md
Labels: LGTM, areas/docs, os/ubuntu, size/L

#761 bugfix: network device is remaining after container have been removed
  daemon/mgr/container.go
Labels: LGTM, areas/network, kind/bug, size/S

#757 feature: complete functions of cni manager
  daemon/mgr/cri.go
  daemon/mgr/cri_network.go
Labels: LGTM, areas/network, kind/feature, size/L

#771 test: use helloworld image in image test
  test/cli_rmi_test.go
  test/utils.go
Labels: LGTM, areas/test, size/S

#755 feature: support pull image with authentication
  apis/server/image_bridge.go
  cli/login.go
  cli/pull.go
  client/container.go
  client/image.go
  client/interface.go
  client/network.go
  client/request.go
  client/system.go
  client/volume.go
  credential/config_file.go
  credential/credential.go
  credential/file_store.go
  credential/helpers.go
  credential/helpers_test.go
  credential/store.go
  ctrd/image.go
  ctrd/utils.go
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  daemon/mgr/image.go
  main.go
  registry/auth.go
Labels: LGTM, kind/feature, size/XL

#768 fix: make intel RDT compatible with legacy machines
  daemon/mgr/spec_linux.go
Labels: LGTM, kind/bug, size/XS

#764 feature: add update command
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/resources.go
  apis/types/update_config.go
  cli/main.go
  cli/update.go
  client/container.go
  client/interface.go
  ctrd/container.go
  ctrd/utils.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  test/cli_update_test.go
Labels: LGTM, areas/cli, kind/feature, size/XXL

#767 feature: add rich container mode
  apis/swagger.yml
  apis/types/container_config.go
  apis/types/host_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container_rich_mode.go
  daemon/mgr/container_rich_mode_test.go
  daemon/mgr/spec.go
  daemon/mgr/spec_hook.go
  daemon/mgr/spec_process.go
Labels: kind/feature, size/XL

#774 bugfix: client request.post params change fix
  client/container.go
Labels: LGTM, kind/bug, size/XS

#773 bugfix: update client request.post params change fix
  client/container.go
Labels: LGTM, kind/bug, size/XS

#772 feature: replace opencontainers/runc to alibaba/runc
  hack/make.sh
  hack/package/build.sh
Labels: LGTM, kind/feature, size/XS

#760 test: add aliKernel specified tests
  test/cli_alikernel_test.go
  test/cli_network_test.go
  test/cli_run_test.go
  test/cli_volume_test.go
  test/environment/env.go
Labels: LGTM, areas/test, size/XL

#780 fix: replace opencontainers/runc to alibaba/runc
  hack/package/deb/Makefile
Labels: LGTM, kind/bug, size/XS

#776 feature: add logout command
  cli/logout.go
  cli/main.go
  credential/credential.go
  credential/file_store.go
  credential/store.go
Labels: LGTM, areas/cli, areas/log, kind/feature, size/L

#785 test: merge test fix to branch 0.2.x
  test/cli_alikernel_test.go
  test/cli_network_test.go
  test/cli_run_test.go
  test/cli_volume_test.go
  test/environment/env.go
Labels: LGTM, areas/test, size/XL

#790 fix: change pouch version to 0.2.0
  daemon/mgr/system.go
  version/version.go
Labels: LGTM, kind/bug, size/S
