Repository alibaba/pouch, pull requests merged in 2018-09, with the labels that each got.

#2193 bugfix: set pid of stopped container to 0
  daemon/mgr/container_state.go
  test/cli_stop_test.go
Labels: LGTM, kind/bug, size/S

#2188 docs: add doc for pouch checkpoint/restore function with criu
  docs/features/pouch_with_criu.md
Labels: areas/docs, size/L

#2196 bugfix: umount rootfs when delete a container
  daemon/mgr/container.go
Labels: kind/bug, size/S

#2200 bugfix: sort mounts according to the depth of destination path
  daemon/mgr/spec_mount.go
  daemon/mgr/spec_mount_test.go
Labels: kind/bug, size/M

#2207 docs: fix stop example
  cli/stop.go
Labels: LGTM, areas/docs, size/XS

#2206 bugfix: use more accurate flag %T to print func
  daemon/logger/syslog/syslog_test.go
Labels: LGTM, kind/bug, size/XS

#2205 fix: simplify logic of update env file, and fix bug
  daemon/mgr/container.go
  daemon/mgr/container_envs.go
  daemon/mgr/container_envs_test.go
  test/cli_rich_container_test.go
Labels: LGTM, areas/log, kind/bug, size/XL

#2209 bugfix: add the missing `devices` field when creating cri container
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: LGTM, kind/bug, size/S

#2043 refactor: polish error construction and log format
  ctrd/container.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_logs.go
  daemon/mgr/container_storage.go
  daemon/mgr/container_utils.go
  daemon/mgr/image.go
  daemon/mgr/image_store.go
  daemon/mgr/image_store_test.go
  daemon/mgr/network.go
  daemon/mgr/snapshot.go
  daemon/mgr/system.go
  daemon/mgr/volume.go
  pkg/errtypes/errors.go
  pkg/errtypes/errors_test.go
  test/cli_inspect_test.go
Labels: areas/log, gap/needs-rebase, kind/bug, kind/refactor, size/XL

#2215 docs: fix some command which not have desc and example
  cli/exec.go
  cli/generate_doc.go
  cli/logs.go
  cli/restart.go
  cli/run.go
  cli/upgrade.go
Labels: LGTM, areas/cli, areas/docs, size/M

#2210 feature: make lxcfs configurable supportd in CRI
  cri/annotations/annotations.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
Labels: kind/feature, size/S

#2220 minor fixes for shell variables and spelling
  docs/features/pouch_with_runV.md
Labels: size/S

#2198 test: add node e2e test in CI
  .travis.yml
  Makefile
  hack/install/install_cni.sh
  hack/install/install_critest.sh
  hack/install/install_etcd.sh
  hack/install/install_ginkgo.sh
  hack/testing/run_daemon_cri_e2e.sh
  hack/testing/run_daemon_cri_integration.sh
Labels: areas/test, size/XL

#2223 test: add test case for privileged container
  daemon/mgr/spec_linux.go
  test/cli_run_test.go
  test/cli_run_with_privileged_test.go
Labels: areas/test, size/L

#2191 docs: add quick experience pouch with kubernetes by vagrant
  Makefile
  VAGRANT.md
  Vagrantfile
  hack/kubernetes/allinone_aliyun.sh
Labels: areas/docs, areas/orchestration, size/XL

#2229 bugfix: fix start container twice error
  apis/server/router.go
  apis/swagger.yml
  daemon/mgr/container.go
  pkg/errtypes/errors.go
  test/api_container_start_test.go
  test/cli_stop_test.go
Labels: LGTM, kind/bug, size/M

#2234 bugfix: container inspect/list should return image field right
  apis/server/container_bridge.go
  test/api_container_inspect_test.go
  test/api_container_list_test.go
  test/util_api.go
Labels: LGTM, areas/images, kind/bug, size/M

#2225 bugfix: fix error api json
  apis/types/registry_service_config.go
  hack/codegen/swagger.sh
Labels: kind/bug, size/S

#2238 bugfix: fix lock competition between Stats and Start interface
  daemon/mgr/container_stats.go
Labels: kind/bug, size/S

#2241 typo: fix typo on hack/install/install_ci_related.sh
  hack/install/install_ci_related.sh
Labels: LGTM, areas/test, areas/typo, size/XS

#2237 feature: add CRI interface of start podsandbox
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_wrapper.go
Labels: areas/kubernetes, kind/feature, size/XXL

#2244 bash_completion: add events command
  contrib/completion/bash/pouch
Labels: areas/cli, size/S

#2214 refactor: make CRI Stream Server share http server with pouchd
  apis/server/router.go
  apis/server/server.go
  cri/config/config.go
  cri/criservice.go
  cri/stream/router.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_stream.go
  cri/v1alpha1/cri_stream_test.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha1/server.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_stream.go
  cri/v1alpha2/cri_stream_test.go
  cri/v1alpha2/cri_wrapper.go
  cri/v1alpha2/server.go
  daemon/daemon.go
  main.go
Labels: areas/kubernetes, kind/refactor, size/XL

#2246 add $GOPATH/bin to PATH environment variable for root user.
  Vagrantfile
Labels: size/S

#2164 bugfix: Fix that cannot update bridge when restart pouchd
  network/mode/bridge/bridge.go
  network/mode/bridge/vars.go
  pkg/utils/utils.go
Labels: LGTM, areas/network, kind/bug, size/L

#2242 feature: complete the details of StartPodSandbox
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  docs/kubernetes/pouch_cri_api_changelog.md
Labels: kind/feature, size/XL

#2250 feature: add envs for pouch exec
  apis/swagger.yml
  apis/types/exec_create_config.go
  cli/exec.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_types.go
  test/api_container_exec_create_test.go
  test/cli_exec_test.go
Labels: LGTM, kind/feature, size/M

#2252 fixes: top options can't work
  apis/server/container_bridge.go
  apis/swagger.yml
  cli/top.go
  test/api_container_top_test.go
  test/cli_top_test.go
Labels: LGTM, kind/bug, size/L

#2257 bugfix: exec stdin should support -i
  daemon/mgr/container_exec.go
Labels: LGTM, kind/bug, size/XS

#2254 cri: add default annotation sandboxid
  cri/annotations/annotations.go
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: size/XS

#2260 bugfix: print error info twice when cmd unknown
  cli/main.go
Labels: kind/bug, size/XS

#2256 fix: make container state in inpsect API correct
  apis/swagger.yml
  apis/types/container_state.go
  apis/types/exec_create_config.go
  test/cli_inspect_test.go
Labels: kind/bug, size/XL

#2247 docs: add a document about CRI API
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  docs/api/CRI_API.html
  hack/boilerplate/boilerplate.go.txt
  hack/protoc/html.tmpl
  hack/protoc/protoc.sh
Labels: LGTM, areas/docs, size/XXL

#2267 bugfix: fix check annotation format
  apis/opts/spec_annotation.go
  apis/opts/spec_annotation_test.go
Labels: LGTM, kind/bug, size/XS

#2266 bugfix: complete json tag for StreamServerReusePort and add some useful log for stop & remove pod operation
  cri/config/config.go
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: LGTM, areas/log, kind/bug, size/S

#2268 bugfix: use same memory in ringbuffer
  daemon/containerio/container_io.go
  test/api_container_exec_start_test.go
Labels: LGTM, kind/bug, size/M

#2275 bugfix: pouch exec with envs will not replace old envs
  daemon/mgr/container_exec.go
  test/cli_exec_test.go
Labels: kind/bug, size/S

#2274 bugfix: event api connection may be recycled if keeps idle too long
  apis/server/router.go
  apis/server/system_bridge.go
  cli/events.go
  ctrd/client.go
Labels: kind/bug, size/S

#2269 bugfix: return pid with 0 rather than -1
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  daemon/mgr/container_state.go
Labels: kind/bug, size/S

#2277 bugfix: minor fix for error misuse
  cri/v1alpha1/cri.go
Labels: LGTM, kind/bug, os/suse, size/XS

#2270 refactor: handle the error in advance to avoid useless requests
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri_utils.go
Labels: LGTM, kind/bug, kind/refactor, size/S

#2263 feature: support RunAsGroup of CRI Manager
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  hack/testing/run_daemon_cri_integration.sh
Labels: kind/feature, size/L

#2285 remove redundant code.
  pkg/kmutex/kmutex.go
Labels: size/XS

#2286 feature: add LogPath in Inspect Response
  apis/server/container_bridge.go
  daemon/mgr/container.go
  daemon/mgr/container_logger.go
  test/cli_inspect_test.go
Labels: areas/log, kind/feature, size/M

#2278 bugfix: make the time period of cri collecting stats from containerd configurable or just disable it
  cri/config/config.go
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
  main.go
Labels: DO-NOT-MERGE, kind/bug, size/M

#2291 test: Add checkpoints for PouchRunBlkioSuite
  test/cli_run_blkio_test.go
  test/util/util.go
Labels: areas/test, size/M

#2273 bugfix: only list container stats which are created by cri
  cri/utils/utils.go
  cri/utils/utils_test.go
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
Labels: kind/bug, size/L

#2295 test.cli_run_memory_test: add container check
  test/cli_run_memory_test.go
Labels: areas/test, size/L
