Repository alibaba/pouch, pull requests merged in 2018-04, with the labels that each got.

#1023 doc: improve 0.3.0 changelog
  CHANGELOG.md
Labels: LGTM, areas/docs, areas/log, size/L

#1024 test:add container update test
  client/container.go
  client/container_update.go
  client/container_update_test.go
Labels: LGTM, areas/test, size/M

#1010 feature: enhance multiple inspection
  cli/image_inspect.go
  cli/inspect.go
  cli/inspect/inspector.go
  cli/network.go
  cli/volume.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/cli_inspect_test.go
Labels: LGTM, kind/feature, size/L

#1019 doc: improve the doc of Kubernetes deployment
  README.md
  docs/kubernetes/pouch_with_kubernetes_deploying.md
Labels: LGTM, areas/docs, areas/orchestration, size/XL

#1025 Merge 0.3.x to master branch
  CHANGELOG.md
  version/version.go
Labels: LGTM, size/L

#1020 test: add mock test for network operations on client side
  client/network.go
  client/network_create.go
  client/network_create_test.go
  client/network_inspect.go
  client/network_inspect_test.go
  client/network_list.go
  client/network_list_test.go
  client/network_remove.go
  client/network_remove_test.go
Labels: LGTM, areas/network, areas/test, size/XL

#1026 test: add mock test for volume operations on client side
  client/volume.go
  client/volume_create.go
  client/volume_create_test.go
  client/volume_inspect.go
  client/volume_inspect_test.go
  client/volume_list.go
  client/volume_list_test.go
  client/volume_remove.go
  client/volume_remove_test.go
Labels: LGTM, areas/storage, areas/test, size/XL

#1009 test: add daemon test
  daemon/config/config.go
  test/daemon/daemon.go
  test/z_cli_daemon_test.go
Labels: areas/test, size/XL

#1033 bugfix: fix logic error in volume create mock test
  client/volume_create_test.go
Labels: LGTM, areas/log, areas/storage, areas/test, kind/bug, size/XS

#1037 test:add container get test
  client/container.go
  client/container_get.go
  client/container_get_test.go
Labels: LGTM, areas/test, size/L

#1032 test: add mock test for image operations on client side
  client/image.go
  client/image_inspect.go
  client/image_inspect_test.go
  client/image_list.go
  client/image_list_test.go
  client/image_pull.go
  client/image_pull_test.go
  client/image_remove.go
  client/image_remove_test.go
Labels: LGTM, areas/test, size/XL

#1027 bugfix: specify both cmd and its args when create a container
  daemon/mgr/cri.go
Labels: LGTM, areas/test, kind/bug, size/XS

#1035 bugfix: restful api url should support both with or without version info
  apis/server/router.go
  test/api_version_parameter_test.go
Labels: LGTM, kind/bug, size/XS

#1034 bugfix: change container create output
  cli/create.go
  test/cli_create_test.go
Labels: LGTM, kind/bug, size/S

#1028 feature: add options when using volume list
  apis/server/volume_bridge.go
  cli/volume.go
  daemon/mgr/volume.go
  test/cli_volume_test.go
  volume/core.go
  volume/core_util.go
  volume/types/volume.go
Labels: LGTM, areas/storage, kind/feature, size/XL

#1044 bugfix: fix client login logic
  client/registry_login.go
Labels: LGTM, areas/log, kind/bug, size/XS

#1043 feature: add circleci parrallism testing to split unit-test and code-check
  .circleci/config.yml
  Makefile
Labels: areas/test, kind/feature, size/M

#1048 bugfix: remove duplicate error msgs
  daemon/mgr/network.go
Labels: LGTM, kind/bug, size/XS

#1029 bugfix: modify volume inspect docs
  cli/volume.go
Labels: areas/storage, kind/bug, size/S

#1049 test:add container list test
  client/container.go
  client/container_list.go
  client/container_list_test.go
Labels: LGTM, areas/test, size/L

#1050 feature: restrict codecov.yml to ignore files
  .circleci/config.yml
  .travis.yml
  codecov.yml
Labels: LGTM, kind/feature, size/S

#1053 doc: fix image inspect and network inspect command docs
  cli/image_inspect.go
  cli/network.go
Labels: LGTM, areas/cli, areas/docs, areas/network, size/XS

#1045 bugfix: distinguish cmd and entrypoint better
  daemon/mgr/container_types.go
  daemon/mgr/cri.go
Labels: kind/bug, size/S

#936 feature: containerd grpc client pool
  ctrd/client.go
  ctrd/client_test.go
  ctrd/container.go
  ctrd/image.go
  ctrd/snapshot.go
  ctrd/watch.go
  ctrd/wrapper_client.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: LGTM, kind/feature, size/XL

#1046 feature: add spec annotation flag
  apis/swagger.yml
  apis/types/container_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/spec_annotations.go
  test/cli_create_test.go
  test/cli_run_test.go
  test/cli_start_test.go
Labels: LGTM, kind/feature, size/L

#1038 bugfix: setup hook in advance to avoid panic if no prestart hook setup before
  daemon/mgr/spec_hook.go
Labels: LGTM, kind/bug, kind/panic, priority/P0, size/S

#1041 refactor: mv cli params parse and validate part of code into opts package
  cli/container.go
  cli/container_test.go
  cli/update.go
  daemon/mgr/container_validation.go
  daemon/mgr/spec_devices.go
  pkg/opts/devicemappings.go
  pkg/opts/devicemappings_test.go
  pkg/opts/diskquota.go
  pkg/opts/diskquota_test.go
  pkg/opts/intel_rdt.go
  pkg/opts/intel_rdt_test.go
  pkg/opts/labels.go
  pkg/opts/labels_test.go
  pkg/opts/memory.go
  pkg/opts/memory_swap.go
  pkg/opts/memory_swap_test.go
  pkg/opts/memory_swappiness.go
  pkg/opts/memory_swappiness_test.go
  pkg/opts/memory_test.go
  pkg/opts/networks.go
  pkg/opts/networks_test.go
  pkg/opts/oom_score.go
  pkg/opts/portbindings.go
  pkg/opts/portbindings_test.go
  pkg/opts/ports.go
  pkg/opts/ports_test.go
  pkg/opts/restart_policy.go
  pkg/opts/restart_policy_test.go
  pkg/opts/spec_annotation.go
  pkg/opts/spec_annotation_test.go
  pkg/opts/sysctl.go
  pkg/opts/sysctl_test.go
  pkg/runconfig/hostconfig_test.go
Labels: LGTM, kind/refactor, size/XXL

#1054 test: modify hardcode test device /dev/sda
  test/cli_run_test.go
  test/environment/env.go
Labels: LGTM, areas/test, size/M

#1064 test:add container remove and stop test
  client/container.go
  client/container_remove.go
  client/container_remove_test.go
  client/container_stop.go
  client/container_stop_test.go
Labels: areas/test, size/XL

#1040 feature: inspect network by ID
  daemon/mgr/network.go
  test/cli_network_test.go
Labels: LGTM, areas/network, kind/feature, size/L

#1059 golint: not found has exit code 1
  Makefile
Labels: LGTM, size/XS

#1005 bugfix: container name not equals input params
  daemon/mgr/container.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: LGTM, kind/bug, size/L

#1055 bugfix: for privileged container, make some paths not be readonly
  daemon/mgr/spec_volume.go
Labels: kind/bug, size/S

#1066 fix: make json ID be Id to be compatible
  apis/swagger.yml
  apis/types/exec_create_resp.go
  apis/types/image_info.go
  apis/types/network_create_resp.go
  apis/types/network_info.go
  apis/types/network_inspect_resp.go
Labels: LGTM, kind/bug, size/S

#1067 feature: add cpu period and quota for containers
  apis/swagger.yml
  apis/types/resources.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/spec.go
  daemon/mgr/spec_cgroup_cpu.go
  pkg/opts/cpu.go
  test/cli_run_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/feature, size/XL

#1074 test:add container pause and unpause test
  client/container.go
  client/container_pause.go
  client/container_pause_test.go
  client/container_unpause.go
  client/container_unpause_test.go
Labels: LGTM, areas/test, size/L

#1070 feature: add allinone to deploy pouch as available container to kubernetes
  hack/kubernetes/allinone.sh
Labels: areas/orchestration, kind/feature, size/L

#1081 fix: issues with go report
  ctrd/client.go
  daemon/mgr/image.go
  pkg/errtypes/errors.go
  pkg/quota/prjquota.go
  test/environment/env.go
  test/util_api.go
Labels: LGTM, kind/bug, size/S

#1078 test: refine daemon framework
  test/daemon/daemon.go
  test/util_daemon.go
  test/z_cli_daemon_test.go
Labels: areas/log, areas/test, size/XL

#875 feature: add exec inspect api in daemon side
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/container_exec_inspect.go
  apis/types/exec_create_config.go
  apis/types/exec_create_resp.go
  apis/types/exec_start_config.go
  apis/types/process_config.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/cri.go
  daemon/mgr/cri_stream.go
  test/api_container_exec_create_test.go
  test/api_container_exec_inspect_test.go
Labels: kind/feature, size/XL

#1086 bugfix: loop execInspect to get result for cri manager's exec method
  daemon/mgr/cri.go
  daemon/mgr/cri_stream.go
Labels: LGTM, areas/test, kind/bug, size/S

#1089 fix: make pouch network non-existent return exit code 1
  cli/network.go
  cli/volume.go
Labels: LGTM, areas/network, kind/bug, size/XS

#1093 test:add container_top test
  client/container.go
  client/container_top.go
  client/container_top_test.go
Labels: LGTM, areas/test, size/L

#1087 test: add tests for label and config file in daemon
  test/daemon/daemon.go
  test/util_daemon.go
  test/z_cli_daemon_test.go
Labels: LGTM, areas/test, size/XL

#1098 test: seperate integration test and cri test in travisCI
  .travis.yml
  Makefile
  hack/make.sh
Labels: LGTM, areas/test, size/S

#1088 config: support some flags in daemon config file
  daemon/config/config.go
Labels: LGTM, size/XS

#1085 bugfix: fix interface casting error
  main.go
Labels: LGTM, kind/bug, size/XS

#1106 test:add container create test
  client/container.go
  client/container_create.go
  client/container_create_test.go
Labels: areas/test, size/L

#1113 test: skip flaky test TestRichContainerSystemdWorks
  test/cli_rich_container_test.go
Labels: LGTM, areas/test, size/XS

#1117 refactor: refactor return err for golint
  daemon/mgr/container.go
Labels: LGTM, kind/refactor, size/XS

#1092 feature: selinux for cri manager
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
  daemon/mgr/cri_utils.go
  daemon/mgr/spec.go
  daemon/mgr/spec_linux.go
  hack/build
  hack/cri-test/test-cri.sh
  vendor/github.com/opencontainers/selinux/LICENSE
  vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#1116 bugfix: remove ip mask in Networks.IPAddress
  daemon/mgr/network.go
Labels: LGTM, areas/network, kind/bug, size/XS

#1110 bugfix: do not append latest to image name having a tag already
  apis/server/image_bridge.go
  apis/server/image_bridge_test.go
Labels: areas/test, kind/bug, size/M

#1102 feature: add image proxy info in 'pouch info'
  cli/info.go
  daemon/mgr/system.go
Labels: LGTM, kind/feature, size/S

#1119 bugfix: make inspect output an array
  cli/image_inspect.go
  cli/inspect.go
  cli/inspect/inspector.go
  cli/inspect/inspector_test.go
  cli/network.go
  cli/volume.go
  pkg/utils/utils.go
  test/cli_create_test.go
  test/cli_images_test.go
  test/cli_inspect_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_rich_container_test.go
  test/cli_run_test.go
  test/cli_update_test.go
  test/cli_upgrade_test.go
  test/cli_volume_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/bug, size/XL

#1069 bugfix: del endpoint after failing to create endpoint
  daemon/mgr/network.go
Labels: LGTM, kind/bug, size/XS

#1118 feature: add a flag of pouchd to specify whether enable CRI
  daemon/config/config.go
  daemon/daemon.go
  hack/cri-test/test-utils.sh
  main.go
Labels: LGTM, areas/test, kind/feature, size/L

#1097 feature: image auth for cri manager
  daemon/mgr/cri.go
Labels: LGTM, kind/feature, size/S

#1099 bugfix: make container exit with real exit code
  cli/cli.go
  cli/main.go
  cli/run.go
  cli/start.go
  daemon/mgr/container.go
  test/cli_network_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/bug, size/L

#1112 bugfix: we should get image ID from containerd
  ctrd/image.go
  daemon/mgr/cri.go
  hack/cri-test/test-cri.sh
Labels: LGTM, kind/bug, size/M

#1126 make TLS config params can be setup in the file
  main.go
Labels: LGTM, size/S

#1057 feature: add diskquota support regular expression
  apis/swagger.yml
  apis/types/container_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container.go
  daemon/mgr/spec_blkio.go
  pkg/quota/grpquota.go
  pkg/quota/prjquota.go
  pkg/quota/quota.go
  pkg/quota/set_diskquota.go
  pkg/quota/type.go
  test/cli_network_test.go
  test/cli_run_test.go
Labels: LGTM, kind/feature, size/XL

#1134 feature: add node ip and sn into daemon labels
  daemon/daemon.go
  pkg/system/machine.go
  pkg/system/network.go
  test/api_daemon_update_test.go
Labels: LGTM, kind/feature, size/L

#1127 test: add lxcfs binary check
  test/cli_run_test.go
  test/environment/env.go
Labels: LGTM, areas/test, size/S

#1136 bugfix: fix set diskquota failed without quota id
  daemon/mgr/spec_blkio.go
Labels: LGTM, kind/bug, size/S

#1115 test: add tls test
  hack/make.sh
  test/daemon/daemon.go
  test/tls/a_client/a_client.csr
  test/tls/a_client/ca.pem
  test/tls/a_client/ca_wrong.pem
  test/tls/a_client/cert.pem
  test/tls/a_client/key.pem
  test/tls/ca-key.pem
  test/tls/ca.pem
  test/tls/ca.srl
  test/tls/extfile.out
  test/tls/generate_tls.sh
  test/tls/server/ca.pem
  test/tls/server/cert.pem
  test/tls/server/key.pem
  test/tls/server/server.csr
  test/utils.go
  test/z_cli_daemon_test.go
Labels: LGTM, areas/test, size/XL

#1125 feature: add rm flag in pouch run command
  cli/container.go
  cli/run.go
  cli/start.go
  test/cli_run_test.go
Labels: areas/cli, kind/feature, size/S

#1142 fix: fix code style
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/XS

#1140 bugfix: fix daemon panic when meta snapshotter is nil
  daemon/mgr/container.go
Labels: LGTM, kind/bug, kind/panic, priority/P0, size/XS

#1131 feature: add volumes-from for container
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container.go
  pkg/opts/mountpoint.go
  pkg/opts/mountpoint_test.go
  test/cli_run_test.go
Labels: LGTM, areas/storage, kind/feature, size/XL

#1129 feature: gc unused exec processes
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  pkg/collect/safe_map.go
  pkg/collect/safe_map_test.go
Labels: LGTM, kind/feature, size/M

#1159 bugfix: make infra image configurable
  cri/config.go
  daemon/mgr/cri.go
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  main.go
Labels: LGTM, kind/bug, size/S

#1132 refactor: refactor config file resolve
  daemon/config/config.go
  daemon/config/config_test.go
  main.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/refactor, size/XL

#1148 feature: upgrade containerd version to v1.0.3
  INSTALLATION.md
  hack/make.sh
  hack/package/deb/Makefile
  hack/package/rpm/build.sh
  vendor/github.com/containerd/containerd/Makefile
  vendor/github.com/containerd/containerd/RUNC.md
  vendor/github.com/containerd/containerd/cio/io.go
  vendor/github.com/containerd/containerd/cio/io_unix.go
  vendor/github.com/containerd/containerd/cio/io_windows.go
  vendor/github.com/containerd/containerd/content/helpers.go
  vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
  vendor/github.com/containerd/containerd/dialer/dialer.go
  vendor/github.com/containerd/containerd/fs/diff.go
  vendor/github.com/containerd/containerd/image.go
  vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
  vendor/github.com/containerd/containerd/rootfs/diff.go
  vendor/github.com/containerd/containerd/sys/socket_unix.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/containerd/version/version.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XL

#1157 bugfix: fix set quota-id without disk-quota
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/XS

#1161 bugfix: failed to create 'volumefrom' container
  daemon/mgr/container.go
  test/cli_run_test.go
Labels: LGTM, areas/storage, kind/bug, size/XS

#1145 feature: parse volumes from image
  ctrd/utils.go
  daemon/mgr/container.go
  daemon/mgr/volume.go
  storage/volume/core_util.go
  test/cli_run_test.go
  test/cli_volume_test.go
  test/util_daemon.go
Labels: LGTM, areas/storage, kind/feature, size/L

#1156 feature: add pidfile for daemon
  daemon/config/config.go
  main.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/daemon/daemon.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/feature, size/L

#1166 doc: add changelog for 0.4.0
  CHANGELOG.md
  version/version.go
Labels: LGTM, areas/docs, areas/log, size/L

#1173 refactor: refact network list api
  apis/server/network_bridge.go
  apis/swagger.yml
  apis/types/endpoint_resource.go
  apis/types/network_info.go
  apis/types/network_list_resp.go
  apis/types/network_resource.go
  cli/network.go
  client/interface.go
  client/network_list.go
  client/network_list_test.go
Labels: areas/network, kind/refactor, size/XL

#1165 bugfix: persistent storage of sandbox metadata
  daemon/mgr/cri.go
  daemon/mgr/cri_types.go
  pkg/meta/backend.go
  pkg/meta/boltdb.go
  pkg/meta/local.go
  pkg/meta/store.go
Labels: LGTM, areas/storage, kind/bug, size/L

#1172 feature: add network disconnect interface
  apis/server/network_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/network_disconnect.go
  cli/network.go
  client/interface.go
  client/network_disconnect.go
  client/network_disconnect_test.go
  ctrd/container.go
  daemon/mgr/container.go
  test/cli_network_test.go
Labels: LGTM, areas/network, kind/feature, size/XL

#1091 feature: stop cli support specify multi containers
  cli/stop.go
  test/cli_stop_test.go
Labels: LGTM, areas/test, kind/feature, size/M

#1175 bugfix: update SafeMap item just call Put, no need call Remove
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/XS

#1178 typo: fix misspell in test code
  test/z_cli_daemon_test.go
Labels: LGTM, areas/test, areas/typo, size/S

#1176 feature: record container last exit time
  daemon/mgr/container_types.go
  daemon/mgr/container_types_test.go
  test/cli_ps_test.go
  test/cli_stop_test.go
Labels: LGTM, kind/feature, size/L

#1183 bugfix: evaluate finish time of container in CRI correctly
  daemon/mgr/cri.go
Labels: LGTM, kind/bug, size/XS

#1182 bugfix: if user rename container with id use the real name to clean the cache
  daemon/mgr/container.go
  test/api_container_rename_test.go
Labels: LGTM, kind/bug, size/M

#1149 docs: update cri-related docs to revise pouch config file
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  hack/kubernetes/allinone.sh
Labels: areas/docs, size/M

#1192 remove log format type check
  cli/logs.go
Labels: LGTM, areas/log, size/XS

#1190 bugfix: container cannot start after first start failed
  daemon/mgr/container.go
  docs/kubernetes/pouch_with_kubernetes_deploying.md
Labels: LGTM, kind/bug, size/M

#1193 bugfix: should use `go get -u golang.org/x/lint/golint`
  .circleci/config.yml
  Dockerfile
Labels: kind/bug, size/XS

#1189 fix minor mistakes in pouch_with_runV.md docs
  docs/features/pouch_with_runV.md
Labels: LGTM, areas/runv, size/XS

#1195 test: skip always fail test
  test/cli_rich_container_test.go
Labels: LGTM, areas/test, size/XS

#1153 feature: refactor exec to enable configure stdin
  ctrd/container.go
  daemon/containerio/cio.go
  daemon/containerio/container_io.go
  daemon/containerio/options.go
  daemon/mgr/container.go
  daemon/mgr/cri.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_restart_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_top_test.go
  test/cli_unpause_test.go
  test/cli_update_test.go
  test/cli_upgrade_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/feature, kind/refactor, size/XL

#1201 bugfix: reset to `go get -u golang.org/x/lint/golint`
  .circleci/config.yml
  Dockerfile
Labels: LGTM, kind/bug, size/XS

#1200 docs: fix misspell in docs
  docs/api/HTTP_API.md
  docs/kubernetes/pouch_with_cri_introduction.md
  docs/static_files/pouch_with_cri_work_flow.png
Labels: LGTM, areas/docs, size/L

#1187 feature: add network connect for container
  README.md
  apis/server/network_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/network_connect.go
  cli/network.go
  client/interface.go
  client/network_connect.go
  daemon/mgr/container.go
  daemon/mgr/network_utils.go
  hack/make.sh
  pkg/utils/utils.go
  test/cli_network_test.go
Labels: LGTM, areas/network, kind/feature, size/XL

#1203 refactor: if store container info to disk failed return errors
  apis/server/network_bridge.go
  apis/server/router.go
  daemon/mgr/container.go
Labels: LGTM, kind/bug, kind/refactor, size/M

#1202 bugfix: make logrus detect whether output with color
  main.go
Labels: LGTM, areas/log, kind/bug, size/XS

#1209 fix: make stop stopped container return no error
  daemon/mgr/container.go
  test/cli_stop_test.go
Labels: LGTM, kind/bug, size/XS

#1210 fix: make stopping non-running container valid
  daemon/mgr/container.go
  test/cli_stop_test.go
Labels: LGTM, kind/bug, size/XS

#1212 bugfix: remove the DiskQuota useless field from Resource
  apis/swagger.yml
  apis/types/resources.go
Labels: LGTM, kind/bug, size/XS

#1154 refactor: make spec created more reasonable
  daemon/mgr/container.go
  daemon/mgr/spec.go
  daemon/mgr/spec_annotations.go
  daemon/mgr/spec_blkio.go
  daemon/mgr/spec_cgroup_cpu.go
  daemon/mgr/spec_cgroup_memory.go
  daemon/mgr/spec_devices.go
  daemon/mgr/spec_hook.go
  daemon/mgr/spec_linux.go
  daemon/mgr/spec_mount.go
  daemon/mgr/spec_namespace.go
  daemon/mgr/spec_network.go
  daemon/mgr/spec_process.go
  daemon/mgr/spec_root.go
Labels: LGTM, kind/refactor, size/XXL

#1196 bugfix: remove update image and fix bugs when update env
  apis/swagger.yml
  apis/types/update_config.go
  cli/update.go
  daemon/mgr/container.go
  test/cli_update_test.go
Labels: LGTM, kind/bug, size/L

#1214 test: fix ci fail cause container run and stop
  test/cli_update_test.go
Labels: LGTM, areas/test, size/XS

#1215 bugfix: fix volume size without unit
  pkg/bytefmt/bytefmt.go
  pkg/bytefmt/bytefmt_test.go
  test/cli_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/S

#1100 test: uncomment daemon config test
  test/z_cli_daemon_test.go
Labels: areas/test, size/L

#1213 bugfix: Volume info of inspect output is incompatible with Moby API
  daemon/mgr/container.go
  test/cli_run_test.go
Labels: LGTM, areas/storage, kind/bug, size/M

#1216 docs: fix misspell for ObjectMeta comments
  storage/volume/types/meta/types.go
Labels: LGTM, areas/docs, size/XS

#1218 feature: support update env when container is running
  daemon/mgr/container.go
  test/cli_update_test.go
  vendor/github.com/magiconair/properties/CHANGELOG.md
  vendor/github.com/magiconair/properties/LICENSE
  vendor/github.com/magiconair/properties/README.md
  vendor/github.com/magiconair/properties/decode.go
  vendor/github.com/magiconair/properties/doc.go
  vendor/github.com/magiconair/properties/integrate.go
  vendor/github.com/magiconair/properties/lex.go
  vendor/github.com/magiconair/properties/load.go
  vendor/github.com/magiconair/properties/parser.go
  vendor/github.com/magiconair/properties/properties.go
  vendor/github.com/magiconair/properties/rangecheck.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#1219 bugfix: add parse Config.Volumes when create container
  daemon/mgr/container.go
Labels: LGTM, areas/storage, kind/bug, size/XL

#1220 bugfix: handle container io properly when restart pouchd
  cli/run.go
  ctrd/container.go
  daemon/containerio/cio.go
Labels: LGTM, kind/bug, size/M

#1191 bugfix: add default tag ":latest" when using pouch rmi to remove untagged container images.
  daemon/mgr/image.go
Labels: LGTM, areas/test, kind/bug, size/XS

#1222 feature: support update container's cpu-period
  cli/update.go
  ctrd/utils.go
  daemon/mgr/container.go
  test/cli_update_test.go
Labels: LGTM, kind/feature, size/L

#1224 feature: add volume driver alias
  daemon/config/config.go
  main.go
  storage/volume/config.go
  storage/volume/core.go
  storage/volume/driver/driver.go
Labels: LGTM, areas/storage, kind/feature, size/M

#1229 fix pouch github address url
  ctrd/README.md
Labels: LGTM, areas/typo, size/XS

#1228 bugfix: update label compatibility with alidocker
  apis/swagger.yml
  apis/types/update_config.go
  cli/update.go
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/M

#1179 feature: add run flag ulimit
  apis/swagger.yml
  apis/types/resources.go
  apis/types/ulimit.go
  cli/common_flags.go
  cli/container.go
  cli/ulimit.go
  daemon/mgr/container.go
  daemon/mgr/spec_process.go
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_run_test.go
  test/cli_start_test.go
Labels: LGTM, kind/feature, size/XL

#1226 bugfix: align with docker v1.24 API
  cli/exec.go
  ctrd/container.go
  hack/cri-test/test-cri.sh
  test/api_container_exec_inspect_test.go
  test/api_container_exec_start_test.go
  vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go
  vendor/vendor.json
Labels: LGTM, kind/bug, size/XL

#1233 bugfix: setRawMode can only be set when the user set tty
  cli/run.go
Labels: LGTM, kind/bug, size/S

#1239 bugfix: modify log format
  daemon/mgr/network.go
  main.go
Labels: LGTM, areas/log, kind/bug, size/XS

#1235 feature: update restful api support update container diskquota
  apis/swagger.yml
  apis/types/update_config.go
  cli/update.go
  daemon/mgr/container.go
  storage/quota/quota.go
  storage/quota/set_diskquota.go
Labels: kind/feature, size/XL

#1234 feature: add client debug flag
  cli/cli.go
Labels: LGTM, kind/bug, kind/feature, size/S

#1248 doc: fix word misspell
  daemon/mgr/spec.go
Labels: LGTM, areas/docs, size/XS

#1254 bugfix: add _test.go suffix to the test file
  test/api_container_resize_test.go
Labels: LGTM, areas/test, kind/bug, size/XS

#1245 feature: add vagrant environment for development
  hack/vagrant/.gitignore
  hack/vagrant/README.md
  hack/vagrant/Vagrantfile
  hack/vagrant/bootstrap.sh
Labels: kind/feature, size/L
