Repository alibaba/pouch, pull requests merged in 2018-03, with the labels that each got.

#786 feature: optimize update interface
  cli/update.go
  daemon/mgr/container.go
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_help_test.go
  test/cli_images_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_pull_test.go
  test/cli_rmi_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_unpause_test.go
  test/cli_update_test.go
  test/cli_version_test.go
  test/cli_volume_test.go
Labels: LGTM, kind/feature, size/L

#796 test: fix unit-test error
  hack/build
Labels: LGTM, areas/test, kind/bug, size/XS

#799 INSTALLATION.md: Fix runv link
  INSTALLATION.md
Labels: LGTM, areas/runv, size/XS

#795 test: fix ci test
  test/cli_alikernel_test.go
  test/cli_create_test.go
  test/cli_images_test.go
  test/cli_ps_test.go
  test/cli_pull_test.go
  test/cli_rmi_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_unpause_test.go
  test/cli_update_test.go
  test/cli_version_test.go
Labels: LGTM, areas/test, size/S

#806 docs: add changelog for 0.2.0
  CHANGELOG.md
Labels: areas/docs, areas/log, size/M

#793 doc: modify apt repository url
  INSTALLATION.md
Labels: LGTM, kind/bug, size/S

#797 feature: basic framework of stream server for cri manager
  cri/stream/constant/protocols.go
  cri/stream/constant/types.go
  cri/stream/errors.go
  cri/stream/httpstream/httpstream.go
  cri/stream/httpstream/spdy/connection.go
  cri/stream/httpstream/spdy/upgrade.go
  cri/stream/remotecommand/attach.go
  cri/stream/remotecommand/exec.go
  cri/stream/remotecommand/httpstream.go
  cri/stream/request_cache.go
  cri/stream/server.go
  daemon/daemon.go
  daemon/mgr/cri.go
  daemon/mgr/cri_stream.go
  hack/cri-test/test-cri.sh
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#804 bugfix: set quota by kernel version
  daemon/config/config.go
  main.go
  pkg/kernel/kernel.go
  pkg/kernel/kernel_test.go
  pkg/quota/grpquota.go
  pkg/quota/prjquota.go
  pkg/quota/quota.go
  volume/modules/local/local.go
Labels: LGTM, kind/bug, size/L

#812 fix: add pouch version information
  daemon/mgr/system.go
  version/version.go
Labels: LGTM, kind/bug, size/S

#808 feature: add user flag implement in pouch create and exec
  cli/exec.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/spec_process.go
  pkg/user/user.go
  pkg/user/user_test.go
  test/cli_run_test.go
  test/cli_start_test.go
Labels: kind/feature, size/XL

#576 feature: add pouch daemon config file
  daemon/config/config.go
  main.go
  pkg/utils/tls.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: LGTM, kind/feature, size/XL

#769 test: add container memory limitation validness checking
  test/cli_run_test.go
Labels: LGTM, areas/test, size/S

#818 docs: fix typos in architecture doc
  docs/architecture.md
Labels: areas/docs, areas/typo, size/S

#821 test: add resource check test and fix a typo error in cli
  cli/common_flags.go
  cli/update.go
  hack/make.sh
  test/cli_run_test.go
Labels: LGTM, areas/test, areas/typo, kind/bug, size/L

#754 refactor: refact metadata store
  Makefile
  daemon/daemon.go
  daemon/meta/errors.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
  daemon/mgr/network.go
  daemon/mgr/volume.go
  hack/module
  internal/generator.go
  pkg/client/errors.go
  pkg/meta/backend.go
  pkg/meta/boltdb.go
  pkg/meta/errors.go
  pkg/meta/local.go
  pkg/meta/store.go
  pkg/meta/store_test.go
  volume/core.go
  volume/error/errors.go
  volume/store/boltdb/db.go
  volume/store/store.go
  volume/types/volume.go
Labels: LGTM, kind/refactor, size/XXL

#822 fix: update command args to be exact one
  cli/update.go
Labels: LGTM, areas/cli, kind/bug, size/XS

#792 test: add rich container test
  docs/features/pouch_with_rich_container.md
  hack/make.sh
  test/cli_rich_container_test.go
  test/environment/env.go
Labels: LGTM, areas/test, size/XL

#814 fix: optimize the way of packaging
  hack/make.sh
  hack/package/README.md
  hack/package/deb/Makefile
  hack/package/deb/build.sh
  hack/package/deb/ubuntu-xenial/Dockerfile.x86_64
  hack/package/package.sh
  hack/package/rpm/build.sh
  hack/package/rpm/centos-7/Dockerfile.x86_64
Labels: LGTM, kind/bug, size/XL

#832 bug: fix Makefile bug and speed up unit test
  Makefile
  hack/build
Labels: areas/test, kind/bug, size/XS

#829 test: add blkio test
  test/cli_run_test.go
Labels: LGTM, areas/test, size/XL

#828 docs: integrate pouch with dragonfly
  docs/features/pouch_with_dragonfly.md
Labels: LGTM, areas/docs, size/M

#834 bugfix: skip the cri test for attach
  hack/cri-test/test-cri.sh
Labels: areas/test, kind/bug, size/XS

#835 bugfix: use host network when build package
  hack/package/package.sh
Labels: LGTM, areas/network, kind/bug, size/XS

#840 test: add test skeleton for alikernel flags
  test/cli_run_test.go
Labels: LGTM, areas/test, size/S

#841 fix: close net connection in exec process
  cli/exec.go
Labels: LGTM, kind/bug, size/XS

#838 fix: ordinary binary volume binding bugs
  daemon/mgr/container.go
  test/cli_run_test.go
Labels: LGTM, areas/storage, kind/bug, size/S

#791 feature: add cgroupspath flag for pouchd
  cli/common_flags.go
  cli/container.go
  daemon/config/config.go
  daemon/mgr/container.go
  main.go
  test/cli_run_test.go
  test/cli_update_test.go
Labels: LGTM, kind/feature, size/L

#844 docs: add maintainers for project Pouch
  MAINTAINERS
  MAINTAINERS.md
Labels: areas/docs, size/S

#845 docs: update README.md to make title and feature clear
  README.md
Labels: areas/docs, kind/feature, size/XS

#846 cherry-pick commits from master to 0.2.1
  daemon/config/config.go
  main.go
  pkg/kernel/kernel.go
  pkg/kernel/kernel_test.go
  pkg/quota/grpquota.go
  pkg/quota/prjquota.go
  pkg/quota/quota.go
  version/version.go
  volume/modules/local/local.go
Labels: LGTM, size/L

#833 feature: add port mapping for container
  apis/swagger.yml
  apis/types/host_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container.go
  daemon/mgr/network.go
  network/types/endpoint.go
  test/cli_network_test.go
  vendor/github.com/docker/go-connections/LICENSE
  vendor/github.com/docker/go-connections/nat/nat.go
  vendor/github.com/docker/go-connections/nat/parse.go
  vendor/github.com/docker/go-connections/nat/sort.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#850 bugfix: fix project quota can't be set on kernel-4.9
  pkg/quota/grpquota.go
  pkg/quota/prjquota.go
Labels: LGTM, kind/bug, size/S

#853 doc: change my name in MAINTAINERS
  MAINTAINERS.md
Labels: LGTM, areas/docs, size/XS

#855 bugfix: fix project quota can't be set on kernel-4.9
  pkg/quota/grpquota.go
  pkg/quota/prjquota.go
Labels: LGTM, kind/bug, size/S

#858 doc: add changelog for version 0.2.1
  CHANGELOG.md
Labels: LGTM, areas/docs, areas/log, size/S

#856 doc: refine test doc
  docs/test/test.md
Labels: areas/docs, areas/test, size/XL

#871 [feature] add inspect format for image network and volume
  cli/image_inspect.go
  cli/network.go
  cli/volume.go
  test/cli_images_test.go
  test/cli_network_test.go
  test/cli_volume_test.go
Labels: areas/network, areas/storage, kind/feature, size/L

#872 add some type in .gitignore
  .gitignore
Labels: LGTM, size/XS

#869 feature: pouch restful api url support version param
  apis/server/router.go
  client/client.go
  client/request.go
  test/api_version_parameter_test.go
  test/request/request.go
Labels: LGTM, kind/feature, size/XL

#852 feature: skeleton of upgrade interface
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/container_upgrade_config.go
  cli/main.go
  cli/upgrade.go
  client/container.go
  client/interface.go
  daemon/mgr/container.go
  test/api_container_upgrade_test.go
  test/cli_upgrade_test.go
Labels: LGTM, kind/feature, size/XL

#874 feature: pull request from 0.2.x branch to master
  CHANGELOG.md
  apis/swagger.yml
  apis/types/host_config.go
  cli/common_flags.go
  cli/container.go
  cli/update.go
  daemon/mgr/container.go
  daemon/mgr/network.go
  docs/features/pouch_with_rich_container.md
  hack/make.sh
  network/types/endpoint.go
  test/cli_alikernel_test.go
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_help_test.go
  test/cli_images_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_pull_test.go
  test/cli_rich_container_test.go
  test/cli_rmi_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_unpause_test.go
  test/cli_update_test.go
  test/cli_version_test.go
  test/cli_volume_test.go
  test/environment/env.go
  vendor/github.com/docker/go-connections/LICENSE
  vendor/github.com/docker/go-connections/nat/nat.go
  vendor/github.com/docker/go-connections/nat/parse.go
  vendor/github.com/docker/go-connections/nat/sort.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#881 fix: make swagger version locked 0.12.0 rather than lastet
  Dockerfile
Labels: LGTM, kind/bug, size/XS

#883 [test] Print error log in CI.
  hack/make.sh
Labels: LGTM, areas/log, areas/test, kind/bug, size/XS

#862 feature: add debugger tool for pouch
  main.go
  vendor/github.com/google/gops/LICENSE
  vendor/github.com/google/gops/agent/agent.go
  vendor/github.com/google/gops/internal/internal.go
  vendor/github.com/google/gops/signal/signal.go
  vendor/github.com/kardianos/osext/LICENSE
  vendor/github.com/kardianos/osext/README.md
  vendor/github.com/kardianos/osext/osext.go
  vendor/github.com/kardianos/osext/osext_go18.go
  vendor/github.com/kardianos/osext/osext_plan9.go
  vendor/github.com/kardianos/osext/osext_procfs.go
  vendor/github.com/kardianos/osext/osext_sysctl.go
  vendor/github.com/kardianos/osext/osext_windows.go
  vendor/vendor.json
Labels: LGTM, kind/bug, kind/feature, size/XXL

#753 feature: namespace options and supplemental groups for cri manager
  cli/common_flags.go
  cli/container.go
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  daemon/mgr/spec_process.go
  hack/cri-test/test-cri.sh
  pkg/user/user.go
  pkg/user/user_test.go
Labels: LGTM, kind/feature, size/L

#878 feature: add container top interface
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/container_process_list.go
  cli/top.go
  client/container.go
  client/interface.go
  test/api_container_top_test.go
  test/cli_top_test.go
Labels: LGTM, kind/feature, size/XL

#859 feature: add pouch info command
  apis/swagger.yml
  apis/types/commit.go
  apis/types/container_config.go
  apis/types/index_info.go
  apis/types/registry_service_config.go
  apis/types/runtime.go
  apis/types/system_info.go
  apis/types/volume_create_config.go
  cli/info.go
  cli/main.go
  daemon/mgr/system.go
  test/api_system_test.go
Labels: areas/cli, kind/feature, size/XXL

#895 bugfix: inspect image by image id with prefix
  daemon/mgr/image_utils.go
Labels: kind/bug, size/XS

#884 test: add deamon related function
  hack/make.sh
  test/api_container_attach_test.go
  test/api_container_create_test.go
  test/api_container_delete_test.go
  test/api_container_exec_start_test.go
  test/api_container_exec_test.go
  test/api_container_inspect_test.go
  test/api_container_list_test.go
  test/api_container_pause_test.go
  test/api_container_rename_test.go
  test/api_container_start_test.go
  test/api_container_stop_test.go
  test/api_image_create_test.go
  test/api_image_delete_test.go
  test/api_image_inspect_test.go
  test/cli_alikernel_test.go
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_inspect_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_unpause_test.go
  test/daemon/daemon.go
  test/util/util.go
  test/util_api.go
  test/utils.go
  test/z_cli_daemon_test.go
Labels: areas/test, size/XXL

#896 bugfix: cgroup-parent must be abs
  daemon/mgr/container.go
  test/cli_run_test.go
Labels: LGTM, kind/bug, size/S

#886 feature: add pouch logs cli command
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/container_logs_options.go
  cli/logs.go
  cli/main.go
  client/container.go
  client/interface.go
  test/api_container_logs_test.go
  test/cli_logs_test.go
Labels: LGTM, areas/cli, areas/log, kind/feature, size/XL

#900 feature: finish top interface
  apis/server/container_bridge.go
  cli/top.go
  ctrd/container.go
  daemon/mgr/container.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
  test/cli_top_test.go
Labels: LGTM, kind/feature, size/XL

#890 feature: add restart skeleton
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/main.go
  cli/restart.go
  client/container.go
  client/interface.go
Labels: kind/feature, size/L

#904 docs: fix typo
  cli/top.go
Labels: LGTM, areas/docs, areas/typo, size/XS

#879 feature: add resize interface
  apis/server/container_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/resize_options.go
  client/container.go
  client/interface.go
  daemon/mgr/container.go
  test/api_container_resize.go
Labels: LGTM, kind/feature, size/L

#854 feature: implement exec and attach method of stream server
  cri/stream/remotecommand/attach.go
  cri/stream/remotecommand/exec.go
  cri/stream/remotecommand/httpstream.go
  cri/stream/server.go
  daemon/containerio/container_io.go
  daemon/containerio/options.go
  daemon/containerio/streams.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/cri_stream.go
  hack/cri-test/test-cri.sh
Labels: LGTM, kind/feature, size/XL

#913 doc: fix the repository URL
  INSTALLATION.md
Labels: LGTM, areas/docs, size/XS

#909 feature: add no-trunc flag for 'pouch ps'
  cli/ps.go
  test/cli_ps_test.go
Labels: kind/feature, size/M

#908 test: add test for login/logout
  test/api_system_test.go
  test/cli_images_test.go
  test/environment/env.go
  test/util/util.go
  test/utils.go
Labels: LGTM, areas/log, areas/test, size/M

#907 bugfix: fix lxc test error
  hack/make.sh
  test/cli_run_test.go
  test/cli_top_test.go
Labels: areas/test, kind/bug, size/S

#914 test: fix cli_top_test test case
  test/cli_top_test.go
  test/util/util.go
Labels: areas/test, size/S

#888 bugfix: fix volume can be removed when using by container
  apis/server/volume_bridge.go
  daemon/mgr/container.go
  test/cli_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/M

#925 test: quick fix to skip pull httpd image
  test/cli_network_test.go
Labels: areas/test, size/XS

#912 feature: dns configuration for cri manager
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  hack/cri-test/test-cri.sh
Labels: kind/feature, size/L

#919 [feature] add plugin framework
  apis/plugins/ContainerPlugin.go
  apis/plugins/DaemonPlugin.go
  apis/server/container_bridge.go
  apis/server/server.go
  daemon/config/config.go
  daemon/daemon.go
  daemon/mgr/container.go
  daemon/mgr/spec.go
  daemon/mgr/spec_hook.go
  docs/features/pouch_with_plugin.md
  internal/generator.go
  main.go
Labels: LGTM, kind/feature, size/XL

#929 bugfix: fix some typo in doc and comments
  apis/plugins/ContainerPlugin.go
  apis/plugins/DaemonPlugin.go
  apis/server/container_bridge.go
  docs/features/pouch_with_plugin.md
Labels: LGTM, areas/typo, kind/bug, size/S

#928 feature: cri manager could get the log of container
  daemon/containerio/cri_log_file.go
  daemon/containerio/options.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/cri.go
  hack/cri-test/test-cri.sh
Labels: LGTM, areas/log, kind/feature, size/XL

#926 bugfix: pull a image failed will lead to list images failed
  ctrd/image.go
Labels: LGTM, kind/bug, size/S

#930 fix: make Installation more compatible
  INSTALLATION.md
Labels: LGTM, kind/bug, size/S

#911 feature: add default registry namespace
  daemon/config/config.go
  daemon/mgr/image.go
  daemon/mgr/image_utils.go
  main.go
  pkg/reference/def.go
  pkg/reference/parse.go
  pkg/reference/parse_test.go
Labels: kind/feature, size/S

#721 feature: add repoTags and repoDigests
  apis/server/image_bridge.go
  apis/swagger.yml
  apis/types/image_info.go
  cli/image_list.go
  ctrd/image.go
  daemon/mgr/container.go
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  daemon/mgr/image.go
  daemon/mgr/image_test.go
  pkg/reference/def.go
  pkg/reference/parse.go
  pkg/reference/parse_test.go
  pkg/reference/regexp.go
  test/api_image_inspect_test.go
  test/cli_images_test.go
  test/environment/cleanup.go
Labels: kind/feature, size/XL

#876 feature: add disk quota for container's rootfs
  apis/server/container_bridge.go
  apis/swagger.yml
  apis/types/container_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container_types.go
  daemon/mgr/spec.go
  daemon/mgr/spec_blkio.go
  daemon/mgr/spec_namespace.go
  pkg/quota/prjquota.go
  pkg/quota/set_diskquota.go
  test/cli_run_test.go
  test/environment/env.go
Labels: LGTM, areas/storage, kind/feature, size/XL

#935 feature: implement ReadOnlyRootfs and NoNewPrivs of cri manager
  daemon/mgr/container_types.go
  daemon/mgr/container_utils.go
  daemon/mgr/cri_utils.go
  daemon/mgr/spec.go
  daemon/mgr/spec_process.go
  daemon/mgr/spec_root.go
  hack/cri-test/test-cri.sh
Labels: LGTM, kind/feature, size/M

#942 feature: add kernel value in 'pouch version' command
  cli/version.go
  daemon/mgr/system.go
Labels: LGTM, areas/cli, kind/feature, size/S

#941 feature: pouch info print information enhance
  apis/swagger.yml
  apis/types/system_info.go
  cli/info.go
  daemon/daemon.go
  daemon/mgr/system.go
  internal/generator.go
Labels: LGTM, kind/feature, size/XL

#931 feature: finish resize interface
  apis/server/container_bridge.go
  client/container.go
  client/interface.go
  ctrd/container.go
  daemon/mgr/container.go
  test/api_container_resize.go
Labels: LGTM, kind/feature, size/L

#946 bugfix: fix check kernel version is wrong
  pkg/quota/quota.go
Labels: LGTM, kind/bug, size/XS

#945 feature: seperate stdout & stderr of container io and support host network mode for sandbox
  daemon/containerio/backend.go
  daemon/containerio/container_io.go
  daemon/containerio/cri_log_file.go
  daemon/containerio/discard.go
  daemon/containerio/hijack_conn.go
  daemon/containerio/mem_buffer.go
  daemon/containerio/raw_file.go
  daemon/containerio/streams.go
  daemon/mgr/cri.go
  hack/cri-test/test-cri.sh
Labels: LGTM, areas/network, kind/feature, size/L

#917 bugfix: fix pouchd cannot listen tcp address
  cli/restart.go
  main.go
Labels: LGTM

#952 bugfix: revert #917
  main.go
Labels: LGTM, kind/bug, size/XS

#944 feature: finish restart interface
  apis/server/container_bridge.go
  apis/server/router.go
  cli/restart.go
  client/container.go
  client/interface.go
  ctrd/container.go
  daemon/mgr/container.go
  test/api_restart_test.go
  test/cli_restart_test.go
Labels: LGTM, kind/feature, size/XL

#934 feature: add oom flag
  apis/swagger.yml
  apis/types/host_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/spec.go
  daemon/mgr/spec_cgroup_memory.go
  daemon/mgr/spec_process.go
  test/api_container_create_test.go
  test/cli_create_test.go
Labels: LGTM, kind/feature, size/L

#955 feature: sandbox store for cri manager
  daemon/mgr/cri.go
  daemon/mgr/cri_types.go
Labels: LGTM, kind/feature, size/L

#953 bugfix: corrent the import path of logrus
  daemon/mgr/network.go
  network/mode/bridge/bridge.go
  registry/auth.go
  volume/core.go
Labels: LGTM, areas/log, kind/bug, size/S

#956 bugfix: initialize the network log
  daemon/mgr/network.go
Labels: LGTM, areas/log, areas/network, kind/bug, size/XS

#959 typo: unknow -> unknown
  main.go
  pkg/exec/command.go
  volume/types/volume.go
Labels: LGTM, areas/typo, size/XS

#923 feature: finish upgrade interface
  cli/upgrade.go
  client/container.go
  daemon/mgr/container.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/cli_upgrade_test.go
  test/utils.go
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/LICENSE
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#961 feature: add circleci to pouch to validate markdown files
  .circleci/config.yml
Labels: LGTM, areas/docs, kind/feature, size/S

#970 bugfix: rm dump ContainerPIDs method
  ctrd/container.go
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/S

#974 doc: fix errors checked by markdownlint
  .circleci/config.yml
  CHANGELOG.md
  CONTRIBUTING.md
  FAQ.md
  INSTALLATION.md
  MAINTAINERS.md
  README.md
  ROADMAP.md
  ctrd/README.md
  docs/README.md
  docs/architecture.md
  docs/contributions/code_styles.md
  docs/features/pouch_with_dragonfly.md
  docs/features/pouch_with_lxcfs.md
  docs/features/pouch_with_plugin.md
  docs/features/pouch_with_prometheus.md
  docs/features/pouch_with_rich_container.md
  docs/features/pouch_with_runV.md
  docs/features/pouch_with_tls.md
  docs/kubernetes/pouch_with_cri_introduction.md
  docs/kubernetes/pouch_with_cri_verification.md
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/test/debug_in_travis.md
  docs/test/test.md
  hack/package/README.md
  volume/README.md
Labels: LGTM, areas/docs, kind/bug, size/XXL

#978 fix: logo image
  .circleci/config.yml
  README.md
Labels: LGTM, areas/log, kind/bug, size/XS

#971 refactor:pouch ctrd layer refactor
  ctrd/client.go
  ctrd/interface.go
  daemon/daemon.go
  daemon/mgr/container.go
  daemon/mgr/image.go
  docs/features/pouch_with_rich_container.md
  internal/generator.go
Labels: LGTM, kind/refactor, size/L

#885 refactor: set lxcfs managed by systemd
  cli/main.go
  cli/remount_lxcfs.go
  hack/install_lxcfs_on_centos.sh
  hack/make.sh
  hack/package/rpm/build.sh
  hack/package/rpm/service/lxcfs.service
  lxcfs/lxcfs.go
  main.go
Labels: size/L

#940 refactor: modify logic in complement image fullname
  daemon/mgr/image_utils.go
  daemon/mgr/image_utils_test.go
  pkg/reference/parse.go
  pkg/reference/parse_test.go
Labels: areas/log, kind/refactor, size/XL

#973 bugfix: pull image and get its status with RefDigest
  apis/server/image_bridge.go
  daemon/mgr/cri.go
  daemon/mgr/cri_utils.go
  daemon/mgr/image.go
  hack/cri-test/test-cri.sh
  test/cli_images_test.go
Labels: LGTM, kind/bug, size/XL

#979 test: add cases for testing imageCache.get
  daemon/mgr/image_test.go
Labels: areas/test, size/L

#962 fix: make pkg client independent to other inner pkgs
  apis/server/server.go
  cli/cli.go
  client/client.go
  client/client_test.go
  client/utils.go
  daemon/config/config.go
  pkg/utils/tls.go
  pkg/utils/tls_test.go
  test/environment/env.go
  test/request/request.go
Labels: LGTM, kind/bug, size/XL

#982 feature: add daemon label for Pouch
  apis/server/server.go
  cli/info.go
  cri/service/cri.go
  daemon/config/config.go
  daemon/daemon.go
  daemon/mgr/system.go
  main.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/cli_upgrade_test.go
Labels: kind/feature, size/L

#965 test: add mock test for pouch package client
  client/client_mock_test.go
  client/container.go
  client/container_start.go
  client/container_start_test.go
Labels: LGTM, areas/test, size/L

#981 bugfix: handle image format 'namespace/name:tag' correctly
  pkg/reference/parse.go
  pkg/reference/parse_test.go
  test/cli_pull_test.go
Labels: LGTM, kind/bug, size/S

#986 bugfix: restart router miss versionMatcher
  apis/server/router.go
Labels: LGTM, kind/bug, size/XS

#943 test: use stable image tag
  hack/make.sh
  test/api_container_attach_test.go
  test/api_container_create_test.go
  test/api_container_delete_test.go
  test/api_container_exec_start_test.go
  test/api_container_exec_test.go
  test/api_container_inspect_test.go
  test/api_container_list_test.go
  test/api_container_pause_test.go
  test/api_container_rename_test.go
  test/api_container_resize.go
  test/api_container_start_test.go
  test/api_container_stop_test.go
  test/api_image_create_test.go
  test/api_image_inspect_test.go
  test/cli_alikernel_test.go
  test/cli_create_test.go
  test/cli_exec_test.go
  test/cli_images_test.go
  test/cli_inspect_test.go
  test/cli_logs_test.go
  test/cli_network_test.go
  test/cli_ps_test.go
  test/cli_rich_container_test.go
  test/cli_rmi_test.go
  test/cli_run_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_top_test.go
  test/cli_unpause_test.go
  test/cli_update_test.go
  test/cli_upgrade_test.go
  test/cli_volume_test.go
  test/daemon/daemon.go
  test/environment/env.go
  test/main_test.go
  test/util_api.go
  test/utils.go
  test/z_cli_daemon_test.go
Labels: areas/test, size/XL

#990 [linting] Fix go misspell linting errors
  client/container.go
  client/system.go
  daemon/mgr/container.go
  daemon/mgr/cri.go
  test/cli_network_test.go
  test/util/util.go
Labels: LGTM, kind/bug, size/S

#992 fix: url mistake and test incorrectness
  apis/server/router.go
  test/api_container_restart_test.go
Labels: areas/test, kind/bug, priority/P0, size/XS

#985 feature: websocket support for cri stream server
  cri/stream/remotecommand/httpstream.go
  cri/stream/remotecommand/websocket.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/server.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/util/wsstream/BUILD
  vendor/k8s.io/apiserver/pkg/util/wsstream/conn.go
  vendor/k8s.io/apiserver/pkg/util/wsstream/doc.go
  vendor/k8s.io/apiserver/pkg/util/wsstream/stream.go
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#996 test: to debug top ci test case
  test/cli_top_test.go
Labels: LGTM, areas/test, kind/bug, size/XS

#997 refactor: add validation for name in api server
  apis/server/container_bridge.go
  apis/server/router.go
  apis/server/utils.go
  apis/server/utils_test.go
  client/container.go
Labels: LGTM, kind/refactor, size/L

#1000 revert: revert #997 validationName
  apis/server/container_bridge.go
  apis/server/utils.go
  apis/server/utils_test.go
Labels: LGTM, size/L

#998 rpm: do not start lxcfs by default in pouchd deamon
  INSTALLATION.md
  hack/package/deb/systemd/pouch.service
  hack/package/rpm/service/pouch.service
Labels: LGTM, size/S

#1002 fix: make container ID json name compatible
  apis/swagger.yml
  apis/types/container.go
Labels: LGTM, kind/bug, size/XS

#987 feature: add daemon update API
  apis/server/router.go
  apis/server/system_bridge.go
  apis/swagger.yml
  apis/types/daemon_update_config.go
  daemon/config/config.go
  daemon/mgr/system.go
  test/api_daemon_update_test.go
Labels: kind/feature, size/XL

#988 refactor: make route code much more siplified
  apis/server/router.go
Labels: kind/refactor, size/L

#902 feature: make logout use default registry
  apis/swagger.yml
  apis/types/system_info.go
  cli/login.go
  cli/logout.go
  credential/file_store.go
  credential/helpers.go
  daemon/mgr/system.go
Labels: LGTM, areas/log, kind/feature, size/M

#1006 fix: make conflict from different merge consistent
  apis/server/router.go
Labels: kind/bug, size/XS

#1007 feature: error stream for cri stream server
  cri/stream/docs.go
  cri/stream/remotecommand/attach.go
  cri/stream/remotecommand/errors.go
  cri/stream/remotecommand/exec.go
  cri/stream/remotecommand/httpstream.go
  cri/stream/remotecommand/websocket.go
  cri/stream/server.go
  daemon/mgr/cri_stream.go
Labels: LGTM, kind/bug, kind/feature, size/XL

#1004 test: add mock test for system_version
  client/system.go
  client/system_version.go
  client/system_version_test.go
Labels: LGTM, areas/test, size/L

#937 feature: add bind mode
  apis/server/container_bridge.go
  apis/swagger.yml
  apis/types/mount_point.go
  cli/common_flags.go
  daemon/mgr/container.go
  daemon/mgr/container_test.go
  daemon/mgr/spec_volume.go
  test/cli_volume_test.go
Labels: kind/feature, size/XL

#1014 feature: cherry-pich one commit
  apis/server/container_bridge.go
  apis/swagger.yml
  apis/types/mount_point.go
  cli/common_flags.go
  daemon/mgr/container.go
  daemon/mgr/container_test.go
  daemon/mgr/spec_volume.go
  test/cli_volume_test.go
Labels: kind/feature, size/XL

#1016 Add CHANGELOG for 0.3.0
  CHANGELOG.md
  version/version.go
Labels: LGTM, areas/log, size/M
