Repository alibaba/pouch, pull requests merged in 2018-12, with the labels that each got.

#2523 cleanup: rm runtime.Caller with const func name
  test/cli_alikernel_test.go
  test/cli_create_test.go
  test/cli_network_test.go
  test/cli_rich_container_test.go
  test/cli_run_volume_test.go
  test/cli_volume_test.go
Labels: size/XL

#2469 feature: add volume filter
  apis/filters/parse.go
  apis/filters/parse_test.go
  apis/server/volume_bridge.go
  apis/swagger.yml
  cli/volume.go
  client/interface.go
  client/volume_list.go
  client/volume_list_test.go
  daemon/mgr/volume.go
  storage/volume/core.go
  storage/volume/core_test.go
  test/api_volume_list_test.go
  test/cli_volume_test.go
  test/environment/cleanup.go
Labels: LGTM, areas/storage, kind/feature, size/XL

#2516 ci: update runc version to 1.0.0-rc6-1
  hack/install/install_runc.sh
Labels: areas/test, size/XS

#2500 refactor: fix part of megacheck issue
  apis/filters/parse.go
  apis/opts/config/blkio.go
  apis/opts/config/runtime.go
  apis/server/image_bridge.go
  cli/container.go
  cli/image_list.go
  cli/tag.go
  cli/top.go
  cli/update.go
  client/request.go
  cri/criservice.go
  cri/stream/portforward/httpstream.go
  cri/stream/portforward/portforward.go
  ctrd/client.go
  ctrd/container.go
  ctrd/snapshot.go
  daemon/config/config.go
  daemon/logger/jsonfile/jsonfile_read_test.go
  daemon/logger/jsonfile/utils_test.go
  daemon/mgr/container.go
  daemon/mgr/container_logger.go
  daemon/mgr/container_storage.go
  daemon/mgr/container_types.go
  daemon/mgr/image_store.go
  lxcfs/lxcfs.go
  pkg/archive/archive.go
  pkg/kmutex/kmutex_test.go
  pkg/meta/local.go
  pkg/meta/store.go
  pkg/netutils/interface_test.go
  pkg/user/user.go
  pkg/utils/timeutils.go
  pkg/utils/utils.go
  registry/auth.go
  registry/auth_challenge.go
  storage/plugins/client.go
  storage/quota/grpquota.go
  storage/quota/quota.go
  storage/volume/core_test.go
  storage/volume/driver/driver.go
  storage/volume/driver/driver_test.go
  storage/volume/driver/remote.go
  test/cli_exec_test.go
  test/cli_run_blkio_test.go
  test/cli_run_cgroup_test.go
  test/daemon/daemon.go
  test/environment/env.go
  test/util/util.go
  test/utils.go
Labels: LGTM, kind/refactor, size/XL

#2470 test: add test cases for configuration of daemon
  daemon/config/config.go
  daemon/config/config_test.go
Labels: LGTM, areas/test, size/XL

#2513 feature: add cross building support for arm64/ppc64le
  .gitignore
  Dockerfile.amd64.cross
  Dockerfile.arm64.cross
  Dockerfile.ppc64le.cross
  Makefile
Labels: kind/feature, size/XL

#2476 feature: add support for maximum log size and max number of log files
  daemon/logger/jsonfile/jsonfile.go
  daemon/logger/jsonfile/jsonfile_read_test.go
  daemon/mgr/container_logs.go
Labels: LGTM, areas/log, kind/feature, size/L

#2527 bugfix: Fix CopyData in Bind Mount
  daemon/mgr/container_storage.go
  test/cli_run_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/S

#2535 test: Clean up temporary test file
  test/cli_run_volume_test.go
Labels: LGTM, areas/test, size/XS

#2532 feature: fullfill network scope field in `network ls` and `inspect`
  apis/server/network_bridge.go
  cli/network.go
  test/cli_network_test.go
Labels: LGTM, areas/network, kind/feature, size/M

#2536 fix: compatible with multi host ip
  pkg/system/system.go
Labels: LGTM, kind/bug, size/XS

#2540 bugfix: fix jsonfile flaky test
  daemon/logger/jsonfile/utils_test.go
Labels: areas/test, kind/bug, size/XS

#2542 fix: volume test fails in custom version pouch
  test/cli_run_volume_test.go
Labels: areas/storage, areas/test, kind/bug, size/XS

#2544 fix: volume copy data test
  test/cli_run_volume_test.go
Labels: LGTM, areas/storage, areas/test, kind/bug, size/S

#2547 test: update the existing tag image case
  test/api_image_tag_test.go
Labels: LGTM, areas/test, size/S

#2546 test: add image config for test.
  test/api_container_inspect_test.go
  test/api_container_list_test.go
  test/api_image_inspect_test.go
  test/api_image_list_test.go
  test/api_image_tag_test.go
  test/api_network_create_test.go
  test/api_network_inspect_test.go
  test/api_network_list_test.go
  test/cli_network_test.go
  test/cli_pull_test.go
  test/cli_rmi_test.go
  test/cli_run_dns_test.go
  test/cli_run_volume_test.go
  test/cli_tag_test.go
  test/environment/env.go
  test/utils.go
Labels: areas/test, size/XL

#2549 Get a valid image user and image uid
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: LGTM, size/S

#2551 bugfix: issues with go vet
  daemon/logger/jsonfile/utils.go
  pkg/netutils/interface.go
Labels: LGTM, kind/bug, size/XS

#2524 bugfix: delete upperDir and workDir when deleting container taken over by pouch
  daemon/mgr/container.go
  daemon/mgr/container_types.go
Labels: kind/bug, size/M

#2554 bugfix: can't copy data with dr mode
  daemon/mgr/container_storage.go
  daemon/mgr/container_storage_test.go
  test/cli_run_volume_test.go
Labels: kind/bug, size/L

#2552 bugfix: container can not write cgroup with privileged
  daemon/mgr/spec_mount.go
  test/cli_run_with_privileged_test.go
Labels: kind/bug, size/S

#2557 bugfix: do not use string to convert int64
  cli/image_list.go
Labels: kind/bug, size/XS

#2559 bugfix: container log path map not initialized for existing businesses
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/log, kind/bug, size/L

#2558 test: simpler test in cli_run_with_privileged_test.go
  test/cli_run_with_privileged_test.go
Labels: areas/test, size/S

#2561 bugfix: StringSliceEqual should also consider duplicate items in slice
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: kind/bug, size/S

#2564 docs: uses unix:// prefix to socket for CRI
  docs/kubernetes/pouch_with_cri_verification.md
Labels: areas/docs, size/XS

#2545 feature: add publish-all cli flag
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container.go
  daemon/mgr/network.go
  test/cli_inspect_test.go
  test/cli_run_network_test.go
Labels: LGTM, kind/feature, size/L

#2565 test: http_utils_test: add cases for func BoolValue
  pkg/httputils/http_utils_test.go
Labels: areas/test, size/M

#2325 feature: upgrade cri to sync k8s 1.12
  apis/swagger.yml
  apis/types/container_config.go
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/spec_linux.go
  docs/kubernetes/pouch_cri_annotations_supported.md
Labels: kind/feature, size/XXL, status/4-ready-to-merge

#2525 feature: support to choose storage driver
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
  ctrd/client.go
  ctrd/container.go
  ctrd/image.go
  ctrd/image_commit.go
  ctrd/interface.go
  ctrd/snapshot.go
  daemon/config/config.go
  daemon/daemon.go
  daemon/daemon_utils.go
  daemon/mgr/container_types.go
  daemon/mgr/snapshot.go
  daemon/mgr/system.go
  main.go
  test/cli_snapshotter_test.go
  vendor/github.com/containerd/containerd/client.go
  vendor/github.com/containerd/containerd/image.go
  vendor/github.com/containerd/containerd/snapshots/snapshotter.go
  vendor/vendor.json
Labels: areas/storage, kind/feature, size/XL, status/4-ready-to-merge

#2580 fix: dragonfly document is dead link
  docs/features/pouch_with_dragonfly.md
Labels: areas/docs, kind/bug, kind/feature, size/XS

#2579 test: synchronize branch from tools-dev to release-1.12 in critest
  hack/install/install_critest.sh
  hack/testing/run_daemon_cri_integration.sh
Labels: areas/test, size/XS

#2567 enhance: use bit operation to get device major/minor
  daemon/mgr/spec_linux.go
Labels: size/XS

#2584 test: add unit test case for func ParseEnv
  apis/opts/env_test.go
Labels: LGTM, areas/test, size/XS

#2589 [RFC] CRI: Add daemon configuration to StatusResponse as extra information
  cri/v1alpha2/cri.go
Labels: size/XS

#2593 remove unused member of daemon config
  daemon/config/config.go
  daemon/config/config_test.go
  test/daemon/daemon.go
Labels: LGTM, size/XS

#2600 test: add test cases for parse_test.go
  apis/filters/parse_test.go
Labels: areas/test, size/M

#2605 upgrade: move to 1.1.0
  Makefile
  version/version.go
Labels: size/XS

#2592 refactor: modify output formatting of info command
  cli/info.go
  test/z_cli_daemon_test.go
Labels: LGTM, areas/cli, kind/refactor, size/L

#2606 bugfix: make pouchd support top a paused container
  daemon/mgr/container.go
  test/cli_top_test.go
Labels: kind/bug, size/S

#2573 test: fix TestRunWithoutCapability not take effect
  test/cli_run_test.go
Labels: areas/test, size/XS

#2602 test: aggregate deveice r/w bps/iops cases to reduce time
  test/cli_run_device_test.go
Labels: areas/test, size/XL

#2607 test: aggregate update test cases to reduce CI time
  cli/update.go
  test/cli_update_test.go
  test/utils.go
Labels: areas/test, size/XL

#2611 config: disable snapshot syncer by default
  main.go
Labels: size/XS

#2608 feature: split image pull interface
  ctrd/image.go
  ctrd/interface.go
  daemon/mgr/image.go
Labels: areas/images, kind/feature, size/M

#2621 test: optimize the time of run test cases
  test/cli_events_test.go
  test/cli_exec_test.go
  test/cli_inspect_test.go
  test/cli_network_test.go
  test/cli_pause_test.go
  test/cli_ps_test.go
  test/cli_restart_test.go
  test/cli_rich_container_test.go
  test/cli_run_volume_test.go
  test/cli_start_test.go
  test/cli_stop_test.go
  test/cli_upgrade_test.go
  test/util_api.go
Labels: LGTM, areas/test, size/M

#2328 test: api_ulimit_test: add test for ulimit
  apis/opts/config/ulimit_test.go
Labels: areas/test, size/XL

#2625 fix: outdated crictl command in docs
  docs/kubernetes/pouch_with_cri_verification.md
Labels: areas/cli, kind/bug, size/M

#2329 test: api_runtime_test: add new checkpoints
  apis/opts/config/runtime_test.go
Labels: areas/test, size/L

#2626 fix: typos
  apis/opts/config/ulimit_test.go
  apis/opts/portbindings.go
  ctrd/image.go
  test/cli_create_test.go
  test/cli_top_test.go
Labels: areas/typo, kind/bug, size/S

#2632 bugfix: repair the script of creating k8s cluster with pouch in Ubuntu 16.04.5
  hack/kubernetes/allinone.sh
  hack/kubernetes/allinone_aliyun.sh
Labels: kind/bug, os/ubuntu, size/S

#2629 daemon: replace error with warning message when synchronize snapshot update
  daemon/mgr/snapshot.go
Labels: LGTM, kind/bug, size/XS
