Repository alibaba/pouch, pull requests merged in 2018-07, with the labels that each got.

#1616 feature: update pouchrobot address tobe Alibaba Cloud
  .circleci/config.yml
  .travis.yml
Labels: LGTM, kind/feature, size/XS

#1619 bugfix: execConfig remove omitemtpy
  apis/swagger.yml
  apis/types/container_exec_inspect.go
  apis/types/process_config.go
  apis/types/registry_service_config.go
  daemon/mgr/container_exec.go
Labels: LGTM, kind/bug, size/XL

#1622 bugfix: execute remount rootfs before prestart hook
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/S

#1608 enhance: add new formatter for syslog
  daemon/logger/syslog/fmt.go
  daemon/logger/syslog/validate.go
  daemon/logger/syslog/validate_test.go
Labels: LGTM, gap/needs-rebase, size/S

#1625 bugfix: list image should ignore error if containerd can't handle well
  daemon/mgr/image.go
Labels: LGTM, kind/bug, size/XS

#1593 feature: make runtime choosing supported in CRI managers for Kubernetes
  cri/annotations/annotations.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_types.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
Labels: areas/orchestration, kind/feature, size/L

#1577 feature: add systemd notify
  apis/server/server.go
  cri/criservice.go
  daemon/daemon.go
  hack/package/deb/systemd/pouch.service
  hack/package/rpm/service/pouch.service
  vendor/github.com/coreos/go-systemd/LICENSE
  vendor/github.com/coreos/go-systemd/NOTICE
  vendor/github.com/coreos/go-systemd/daemon/sdnotify.go
  vendor/github.com/coreos/go-systemd/daemon/watchdog.go
  vendor/github.com/coreos/go-systemd/util/util.go
  vendor/github.com/coreos/go-systemd/util/util_cgo.go
  vendor/github.com/coreos/go-systemd/util/util_stub.go
  vendor/github.com/coreos/pkg/LICENSE
  vendor/github.com/coreos/pkg/NOTICE
  vendor/github.com/coreos/pkg/dlopen/dlopen.go
  vendor/github.com/coreos/pkg/dlopen/dlopen_example.go
  vendor/vendor.json
Labels: gap/needs-rebase, kind/feature, size/XXL

#1605 bugfix: fix exec stuck when exec get error
  apis/server/exec_bridge.go
  apis/server/router.go
  cli/exec.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_stream.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_stream.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  test/cli_exec_test.go
Labels: size/XL

#1586 enhance: adjust data stream from pouch pull api
  apis/server/image_bridge.go
  cli/pull.go
  ctrd/image.go
  daemon/mgr/image.go
  pkg/jsonstream/format.go
  pkg/jsonstream/image_progress.go
  pkg/jsonstream/stream.go
  pkg/jsonstream/types.go
  test/util_api.go
Labels: LGTM, areas/images, areas/test, size/XL

#1621 bugfix: release the container resources if contaienr failed to start
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/XS

#1590 enhance: display disconnect result for pouch network disconnect
  cli/network.go
Labels: LGTM, areas/network, size/S

#1626 test: add unit-tests for core CreateVolume
  storage/volume/core_test.go
  storage/volume/driver/driver.go
  storage/volume/driver/fake_driver.go
Labels: areas/storage, areas/test, size/L

#1431 feature: stats of cri manager
  cri/config/config.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  ctrd/client.go
  ctrd/client_opts.go
  ctrd/container.go
  ctrd/container_types.go
  ctrd/interface.go
  ctrd/snapshot.go
  ctrd/wrapper_client.go
  daemon/daemon.go
  daemon/mgr/container.go
  daemon/mgr/snapshot.go
  daemon/mgr/snapshot_test.go
  vendor/github.com/containerd/cgroups/LICENSE
  vendor/github.com/containerd/cgroups/Protobuild.toml
  vendor/github.com/containerd/cgroups/README.md
  vendor/github.com/containerd/cgroups/blkio.go
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/cgroups/control.go
  vendor/github.com/containerd/cgroups/cpu.go
  vendor/github.com/containerd/cgroups/cpuacct.go
  vendor/github.com/containerd/cgroups/cpuset.go
  vendor/github.com/containerd/cgroups/devices.go
  vendor/github.com/containerd/cgroups/errors.go
  vendor/github.com/containerd/cgroups/freezer.go
  vendor/github.com/containerd/cgroups/hierarchy.go
  vendor/github.com/containerd/cgroups/hugetlb.go
  vendor/github.com/containerd/cgroups/memory.go
  vendor/github.com/containerd/cgroups/metrics.pb.go
  vendor/github.com/containerd/cgroups/metrics.pb.txt
  vendor/github.com/containerd/cgroups/metrics.proto
  vendor/github.com/containerd/cgroups/named.go
  vendor/github.com/containerd/cgroups/net_cls.go
  vendor/github.com/containerd/cgroups/net_prio.go
  vendor/github.com/containerd/cgroups/paths.go
  vendor/github.com/containerd/cgroups/perf_event.go
  vendor/github.com/containerd/cgroups/pids.go
  vendor/github.com/containerd/cgroups/rdma.go
  vendor/github.com/containerd/cgroups/state.go
  vendor/github.com/containerd/cgroups/subsystem.go
  vendor/github.com/containerd/cgroups/systemd.go
  vendor/github.com/containerd/cgroups/ticks.go
  vendor/github.com/containerd/cgroups/utils.go
  vendor/github.com/containerd/cgroups/v1.go
  vendor/github.com/coreos/go-systemd/dbus/dbus.go
  vendor/github.com/coreos/go-systemd/dbus/methods.go
  vendor/github.com/coreos/go-systemd/dbus/properties.go
  vendor/github.com/coreos/go-systemd/dbus/set.go
  vendor/github.com/coreos/go-systemd/dbus/subscription.go
  vendor/github.com/coreos/go-systemd/dbus/subscription_set.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#1647 feature: deamon support --log-driver and --log-opt options
  cli/common_flags.go
  daemon/mgr/container.go
  main.go
Labels: areas/log, kind/feature, size/M

#1652 fix: remove the information about baiji
  apis/opts/cpu_test.go
  apis/opts/oom_score_test.go
  ctrd/image_proxy_util_test.go
  daemon/config/config_test.go
  storage/volume/core_test.go
Labels: kind/bug, size/S

#1576 feature: support net priority flag
  apis/swagger.yml
  apis/types/container_config.go
  cli/common_flags.go
  cli/container.go
Labels: kind/feature, size/S

#1673 docs: update docs about contributing
  CONTRIBUTING.md
Labels: LGTM, areas/docs, size/S

#1668 test: add unit-test for proxy/has port
  ctrd/image_proxy_util_test.go
Labels: LGTM, areas/test, size/S

#1711 Revert "test: add unit-test for proxy/has port"
  ctrd/image_proxy_util_test.go
Labels: areas/test, size/S

#1654 test: add unit-test for hasPort method
  ctrd/image_proxy_util_test.go
Labels: LGTM, areas/test, size/S

#1598 enhance: Port Pouch Cli to Darwin(MacOS)
  pkg/term/term.go
  vendor/github.com/pkg/term/LICENSE
  vendor/github.com/pkg/term/termios/doc.go
  vendor/github.com/pkg/term/termios/ioctl.go
  vendor/github.com/pkg/term/termios/ioctl_darwin.go
  vendor/github.com/pkg/term/termios/ioctl_solaris.go
  vendor/github.com/pkg/term/termios/pty.go
  vendor/github.com/pkg/term/termios/pty_bsd.go
  vendor/github.com/pkg/term/termios/pty_darwin.go
  vendor/github.com/pkg/term/termios/pty_linux.go
  vendor/github.com/pkg/term/termios/pty_solaris.go
  vendor/github.com/pkg/term/termios/termios.go
  vendor/github.com/pkg/term/termios/termios_bsd.go
  vendor/github.com/pkg/term/termios/termios_const.go
  vendor/github.com/pkg/term/termios/termios_const_solaris.go
  vendor/github.com/pkg/term/termios/termios_linux.go
  vendor/github.com/pkg/term/termios/termios_solaris.go
  vendor/github.com/pkg/term/termios/termios_windows.go
  vendor/vendor.json
Labels: gap/needs-rebase, size/XL

#1712 bugfix: schema point to a response object
  apis/swagger.yml
Labels: kind/bug, size/S

#1573 docs: enable non-root user to run pouch commands without sudo
  INSTALLATION.md
  README.md
Labels: areas/cli, areas/docs, size/S

#1657 bugfix: fix exec record user as container config user
  daemon/config/config.go
  daemon/daemon.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  main.go
  test/cli_exec_test.go
Labels: kind/bug, size/M

#1714 enhance: add ExtraAttribute functionality in LogInfo
  daemon/logger/info.go
  daemon/logger/info_test.go
  daemon/logger/loggerutils/tag_test.go
  daemon/mgr/container_logger.go
Labels: LGTM, areas/log, size/XL

#1724 enhance: add .DS_Store ignore
  .gitignore
Labels: size/XS

#1592 feature: add pouch save functionality
  apis/server/image_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/main.go
  cli/save.go
  client/image_save.go
  client/image_save_test.go
  client/interface.go
  ctrd/image.go
  ctrd/interface.go
  daemon/mgr/image.go
  daemon/mgr/image_load.go
  daemon/mgr/image_save.go
  test/cli_load_test.go
  test/cli_save_and_load_test.go
Labels: kind/feature, priority/P2, size/XL

#1720 docs: change logos to new version
  docs/static_files/logo/pouch_10x11_orange.png
  docs/static_files/logo/pouch_10x11_underlying_orange.png
  docs/static_files/logo/pouch_10x11_white.png
  docs/static_files/logo/pouch_10x4_orange.png
  docs/static_files/logo/pouch_10x4_underlying_orange.png
  docs/static_files/logo/pouch_10x4_white.png
  docs/static_files/logo/pouchcontainer_10x10_orange.png
  docs/static_files/logo/pouchcontainer_10x10_underorange.png
  docs/static_files/logo/pouchcontainer_10x10_white.png
  docs/static_files/logo/pouchcontainer_10x1_orange.png
  docs/static_files/logo/pouchcontainer_10x1_underorange.png
  docs/static_files/logo/pouchcontainer_10x1_white.png
Labels: areas/docs, areas/log, size/XS

#1727 bugfix: deb package build failed
  hack/package/deb/Makefile
Labels: kind/bug, size/XS

#1718 test: add unit test for filter validation
  pkg/utils/filters/filter.go
  pkg/utils/filters/filter_test.go
Labels: areas/test, size/M

#1729 bugfix: Fix log-opt option parse fails if value contains comma
  cli/common_flags.go
  main.go
Labels: areas/log, kind/bug, size/XS

#1698 Update INSTALLATION.md
  INSTALLATION.md
Labels: size/XS

#1660 test: add unit-tests for core GetVolume
  storage/volume/core_test.go
Labels: LGTM, areas/storage, areas/test, size/M

#1658 test: add unit test for function ValidateOOMScore in oom_score_test.go
  apis/opts/oom_score_test.go
Labels: areas/test, size/M

#1690 Add unit-test for ValidateCPUPeriod
  apis/opts/cpu_test.go
Labels: LGTM, areas/test, size/S

#1679 test: TestRemoveVolume
  storage/volume/core_test.go
Labels: areas/storage, areas/test, size/S

#1707 test: TestListVolumes
  storage/volume/core_test.go
Labels: areas/storage, areas/test, size/S

#1692 Add unit-test for ValidateCPUQuota
  apis/opts/cpu_test.go
Labels: LGTM, areas/test, size/S

#1731 build: change version from 0.5.0 to 1.0.0-rc1
  hack/build
  version/version.go
Labels: LGTM, size/XS

#1732 build: change version from 0.5.0 to 1.0.0-rc1 (#1731)
  hack/build
  version/version.go
Labels: LGTM, size/XS

#1734 fix: fix swagger generate not consistent
  apis/types/registry_service_config.go
Labels: kind/bug, size/XS

#1717 refactor: split container env and add unit test
  daemon/mgr/container.go
  daemon/mgr/container_envs.go
  daemon/mgr/container_envs_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: LGTM, areas/test, kind/refactor, size/XL

#1716 fix: check user/group in container start
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_types.go
  daemon/mgr/spec_process.go
  pkg/user/user.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/cli_run_user_test.go
Labels: LGTM, kind/bug, size/XL

#1725 refactor: Extract stream manager as the public part
  cri/stream/config.go
  cri/stream/portforward/httpstream.go
  cri/stream/portforward/portforward.go
  cri/stream/remotecommand/attach.go
  cri/stream/remotecommand/exec.go
  cri/stream/runtime.go
  cri/v1alpha1/cri_stream.go
  cri/v1alpha1/server.go
  cri/v1alpha2/cri_stream.go
  cri/v1alpha2/server.go
Labels: kind/refactor, size/XXL

#1617 feature: extend cri apis for special needs
  cri/apis/v1alpha1/BUILD
  cri/apis/v1alpha1/api.pb.go
  cri/apis/v1alpha1/api.proto
  cri/apis/v1alpha1/constants.go
  cri/apis/v1alpha2/BUILD
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/apis/v1alpha2/constants.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_network.go
  cri/v1alpha1/cri_types.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha1/server.go
  cri/v1alpha1/service/cri.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_network.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  cri/v1alpha2/cri_wrapper.go
  cri/v1alpha2/server.go
  cri/v1alpha2/service/cri.go
  daemon/containerio/cri_log_file.go
  hack/boilerplate/boilerplate.go.txt
  hack/protoc.sh
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto
  vendor/vendor.json
Labels: areas/test, gap/needs-rebase, kind/feature, size/XXL

#1741 style: alert the name of struct context to streamContext
  cri/stream/portforward/httpstream.go
  cri/stream/portforward/portforward.go
  cri/stream/remotecommand/attach.go
  cri/stream/remotecommand/exec.go
  cri/stream/remotecommand/httpstream.go
  cri/stream/remotecommand/websocket.go
Labels: LGTM, size/L

#1738 feature: remove InstanceInfo from container env
  daemon/mgr/container_envs.go
Labels: LGTM, kind/feature, size/M

#1743 fix: ensure daemon start successfully after update damon offline
  cli/update_daemon.go
  daemon/config/config.go
  test/z_cli_daemon_test.go
Labels: LGTM, areas/test, kind/bug, size/S

#1745 feature: populate empty volumes when creating container
  daemon/mgr/container.go
Labels: LGTM, areas/storage, kind/feature, size/L

#1750 refactor: reorder hack scripts
  .circleci/config.yml
  .codecov.yml
  .gitignore
  .gometalinter.json
  .travis.yml
  Makefile
  client/image_list.go
  hack/codegen/swagger.sh
  hack/cri-test/test-cri.sh
  hack/cri-test/test-utils.sh
  hack/cri-test/versions
  hack/install/check.sh
  hack/install/install_ci_related.sh
  hack/install/install_containerd.sh
  hack/install/install_critest.sh
  hack/install/install_dumb_init.sh
  hack/install/install_local_persist.sh
  hack/install/install_lxcfs.sh
  hack/install/install_nsenter.sh
  hack/install/install_runc.sh
  hack/testing/run_daemon_cri_integration.sh
  hack/testing/run_daemon_integration.sh
  hack/testing/utils.sh
  hack/validate_swagger.sh
  test/cli_pause_test.go
Labels: LGTM, areas/test, kind/refactor, size/XXL

#1753 bugfix: pouch pull should handle space input as an error
  cli/pull.go
  pkg/reference/parse_test.go
Labels: areas/images, kind/bug, size/S

#1742 docs: update CHANGELOG for 1.0.0-rc1
  CHANGELOG.md
Labels: areas/docs, areas/log, size/L

#1757 bugfix: Add missing document in Makefile
  Makefile
Labels: areas/docs, kind/bug, size/S

#1775 bugfix: a typo in CONTRIBUTTING.md
  CONTRIBUTING.md
Labels: areas/typo, kind/bug, size/XS

#1823 test: fix incorrect error judging in core_test.go
  storage/volume/core_test.go
Labels: LGTM, areas/test, kind/bug, size/XS

#1788 add unit-test for Volume Core's VolumePath method
  storage/volume/core_test.go
Labels: areas/storage, areas/test, size/S

#1810 test: add unit test for func storage/volume/ListVolumeName
  storage/volume/core_test.go
Labels: areas/storage, areas/test, size/M

#1808 test: add unit-test for daemon/config/getUnknownFlags
  daemon/config/config_test.go
Labels: LGTM, areas/test, size/M

#1824 fix issue #1761 baiji-group 264-2
  storage/volume/core_test.go
Labels: LGTM, size/M

#1851 add unit-test for daemon/config/getConfigurations team4
  daemon/config/config_test.go
Labels: LGTM, areas/test, size/S

#1755 [bug]: roolback the code about CRI of version v1alpha1
  .travis.yml
  Makefile
  cri/apis/v1alpha1/api.proto
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_network.go
  cri/v1alpha1/cri_types.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha1/server.go
  cri/v1alpha1/service/cri.go
  daemon/containerio/cri_log_file.go
  hack/install/install_critest.sh
  hack/testing/run_daemon_cri_integration.sh
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.pb.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/constants.go
  vendor/vendor.json
Labels: kind/bug, size/XXL

#1893 docs: add code coverage icon on README
  README.md
Labels: LGTM, areas/docs, size/XS

#1765 bugfix: avoid task exit channel exit unexpected
  ctrd/watch.go
Labels: LGTM, containerd-related, kind/bug, size/XS

#1899 test: run with volume whose destination is not empty
  test/cli_run_volume_test.go
Labels: LGTM, areas/storage, areas/test, size/S

#1921 makefile: simplify makefile output
  Makefile
Labels: size/XS

#1909 test: unit test for cri/stream/errors.go
  cri/stream/errors_test.go
Labels: areas/test, kind/bug, size/M

#1767 test: unit test for request cache of stream server
  cri/stream/request_cache.go
  cri/stream/request_cache_test.go
Labels: areas/test, size/L

#1926 bugfix: don't set mount tab when rootfs diskquota is null
  daemon/mgr/spec_hook.go
Labels: kind/bug, size/S

#1918 feature: add CriEnabled field in api and show this in cli
  apis/swagger.yml
  apis/types/system_info.go
  cli/info.go
  daemon/mgr/system.go
  test/api_system_test.go
  test/z_cli_daemon_test.go
Labels: kind/feature, size/L

#1924 bugfix: add --name following container name in cmd
  test/cli_create_test.go
Labels: LGTM, kind/bug, size/XS

#1719 refactor: Extract cni manager as the public part
  cri/ocicni/cni_manager.go
  cri/ocicni/interface.go
  cri/ocicni/noop_cni_manager.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_network.go
  cri/v1alpha2/cri_utils.go
Labels: areas/network, kind/refactor, size/XL

#1927 bugfix: add ErrorMessage in jsonstream
  ctrd/image.go
  pkg/jsonstream/types.go
Labels: kind/bug, size/XS

#1960 fix: add more details in the NotFound error
  ctrd/watch.go
Labels: kind/bug, size/XS

#1961 BJ266-team10: fix spelling error
  docs/features/pouch_with_runV.md
Labels: LGTM, kind/bug, size/XS

#1945 add unit test for modifyContainerNamespaceOptions
  cri/v1alpha1/cri_utils_test.go
Labels: areas/test, size/S

#1917 docs: update kubernetes deploying document
  docs/kubernetes/pouch_with_kubernetes_deploying.md
  docs/kubernetes/troubleshooting.md
Labels: areas/docs, areas/orchestration, size/XL
