Repository alibaba/pouch, pull requests merged in 2018-11, with the labels that each got.

#2390 refactor: combine functions into one file
  pkg/system/device.go
  pkg/system/machine.go
  pkg/system/network.go
  pkg/system/os.go
  pkg/system/sysinfo.go
  pkg/system/system.go
Labels: kind/refactor, size/XL

#2398 tools: remove package builder from pouch
  hack/build
  hack/make.sh
  hack/package/README.md
  hack/package/deb/Makefile
  hack/package/deb/build.sh
  hack/package/deb/debian/compat
  hack/package/deb/debian/control
  hack/package/deb/debian/docs
  hack/package/deb/debian/pouch.default
  hack/package/deb/debian/pouch.init
  hack/package/deb/debian/pouch.postinst
  hack/package/deb/debian/rules
  hack/package/deb/systemd/pouch.service
  hack/package/deb/ubuntu-xenial/Dockerfile.x86_64
  hack/package/package.sh
  hack/package/rpm/build.sh
  hack/package/rpm/centos-7/Dockerfile.x86_64
  hack/package/rpm/scripts/after-install.sh
  hack/package/rpm/scripts/after-remove.sh
  hack/package/rpm/scripts/after-trans.sh
  hack/package/rpm/scripts/before-install.sh
  hack/package/rpm/scripts/before-remove.sh
  hack/package/rpm/service/pouch-lxcfs.service
  hack/package/rpm/service/pouch.service
Labels: LGTM, size/XXL

#2373 refactor: use return fast to make code readable
  pkg/netutils/interface.go
Labels: kind/refactor, size/M

#2392 feature: add Close function for boltdb backend
  pkg/meta/backend.go
  pkg/meta/boltdb.go
  pkg/meta/local.go
  pkg/meta/store.go
  pkg/meta/store_test.go
Labels: kind/feature, size/XL

#2404 feature: remove unused vendor packages
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/go-ini/ini/LICENSE
  vendor/github.com/go-ini/ini/Makefile
  vendor/github.com/go-ini/ini/README.md
  vendor/github.com/go-ini/ini/README_ZH.md
  vendor/github.com/go-ini/ini/error.go
  vendor/github.com/go-ini/ini/ini.go
  vendor/github.com/go-ini/ini/key.go
  vendor/github.com/go-ini/ini/parser.go
  vendor/github.com/go-ini/ini/section.go
  vendor/github.com/go-ini/ini/struct.go
  vendor/github.com/go-resty/resty/LICENSE
  vendor/github.com/go-resty/resty/README.md
  vendor/github.com/go-resty/resty/client.go
  vendor/github.com/go-resty/resty/default.go
  vendor/github.com/go-resty/resty/middleware.go
  vendor/github.com/go-resty/resty/redirect.go
  vendor/github.com/go-resty/resty/request.go
  vendor/github.com/go-resty/resty/request16.go
  vendor/github.com/go-resty/resty/request17.go
  vendor/github.com/go-resty/resty/response.go
  vendor/github.com/go-resty/resty/resty.go
  vendor/github.com/go-resty/resty/retry.go
  vendor/github.com/go-resty/resty/util.go
  vendor/github.com/magiconair/properties/CHANGELOG.md
  vendor/github.com/magiconair/properties/LICENSE
  vendor/github.com/magiconair/properties/README.md
  vendor/github.com/magiconair/properties/decode.go
  vendor/github.com/magiconair/properties/doc.go
  vendor/github.com/magiconair/properties/integrate.go
  vendor/github.com/magiconair/properties/lex.go
  vendor/github.com/magiconair/properties/load.go
  vendor/github.com/magiconair/properties/parser.go
  vendor/github.com/magiconair/properties/properties.go
  vendor/github.com/magiconair/properties/rangecheck.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#2408 feature: support get security options in daemon
  daemon/mgr/spec_seccomp_linux.go
  daemon/mgr/spec_seccomp_unsupported.go
  daemon/mgr/system.go
Labels: kind/feature, size/S

#2231 feature: support create a container with a given id
  apis/server/container_bridge.go
  apis/swagger.yml
  apis/types/container_config.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container.go
  test/api_container_create_test.go
Labels: LGTM, kind/feature, priority/P2, size/XL, status/4-ready-to-merge

#2418 bugfix: add missing LICENSE in vendor
  vendor/github.com/prometheus/client_golang/LICENSE
  vendor/github.com/prometheus/client_golang/NOTICE
Labels: LGTM, kind/bug, size/XL

#2419 docs: update golang version in Dockerfile to correct 1.10.4
  Dockerfile
Labels: areas/docs, size/XS

#2420 docs: remove pouchcontainer/swagger since we use official one
  hack/codegen/swagger.sh
Labels: areas/docs, areas/test, size/XS

#2402 feature: replace downloading k8s components from googleapis in allinone with apt from aliyun mirrors
  docs/kubernetes/pouch_with_kubernetes_deploying_aliyun.md
  hack/kubernetes/allinone_aliyun.sh
Labels: kind/feature, size/M

#2387 bugfix: fix pouch inspect does not return Ports in NetworkSettings
  daemon/mgr/container.go
  test/cli_inspect_test.go
Labels: LGTM, areas/network, kind/bug, size/S

#2380 feature: support dns related flags when creating container through pouch cli
  cli/common_flags.go
  cli/container.go
  test/cli_run_dns_test.go
Labels: LGTM, kind/feature, size/L

#2375 [RFC] refactor: redesign container io in pouch
  apis/server/container_bridge.go
  apis/server/exec_bridge.go
  cli/exec.go
  cli/run.go
  cri/stream/remotecommand/attach.go
  cri/stream/remotecommand/httpstream.go
  cri/stream/runtime.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  ctrd/container.go
  ctrd/watch.go
  daemon/containerio/backend.go
  daemon/containerio/cio.go
  daemon/containerio/container_io.go
  daemon/containerio/cri_log_file.go
  daemon/containerio/discard.go
  daemon/containerio/hijack_conn.go
  daemon/containerio/io.go
  daemon/containerio/jsonfile.go
  daemon/containerio/options.go
  daemon/containerio/pipe.go
  daemon/containerio/streams.go
  daemon/containerio/syslog.go
  daemon/logger/copier.go
  daemon/logger/copier_test.go
  daemon/logger/crilog/log.go
  daemon/logger/jsonfile/jsonfile.go
  daemon/logger/jsonfile/utils_test.go
  daemon/logger/syslog/syslog.go
  daemon/logger/syslog/syslog_test.go
  daemon/logger/types.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_logger.go
  pkg/ioutils/writer.go
  pkg/streams/multi.go
  pkg/streams/multi_test.go
  pkg/streams/stream.go
  pkg/streams/utils.go
  pkg/streams/utils_test.go
  test/cli_exec_test.go
  test/cli_run_interactive_test.go
Labels: LGTM, kind/design, kind/refactor, priority/P1, size/XXL

#2426 bugfix: fix deadcode reports by gometalinter
  ctrd/container.go
  ctrd/utils.go
  daemon/daemon.go
  daemon/mgr/spec_linux.go
  main.go
  pkg/utils/metrics/unit.go
  registry/auth.go
  storage/quota/grpquota.go
  storage/quota/prjquota.go
  test/util_api.go
  test/util_daemon.go
Labels: LGTM, kind/bug, size/L

#2394 feature: add rules for type validation
  apis/opts/labels.go
  apis/server/container_bridge.go
  apis/server/system_bridge.go
  apis/swagger.yml
  apis/types/container_config.go
  apis/types/exec_create_config.go
  apis/types/port_binding.go
  test/api_container_create_test.go
  test/api_container_exec_create_test.go
  test/cli_exec_test.go
Labels: LGTM, kind/feature, size/L

#2433 test: refactor api_pause_test use util func
  test/api_container_pause_test.go
Labels: LGTM, areas/test, kind/refactor, size/S

#2421 docs: user general pouchlinter to linter pouch's code
  .circleci/Dockerfile
  .circleci/config.yml
  docs/features/pouch_with_plugin.md
  docs/test/test.md
Labels: areas/docs, size/M

#2429 feature: optimise the logic of using prometheus
  apis/metrics/metrics.go
  apis/server/router.go
  cri/metrics/metrics.go
  pkg/utils/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/vendor.json
Labels: LGTM, areas/log, areas/monitoring, kind/feature, size/XXL

#2345 enhance: don't run travis-CI for only document change
  .travis.yml
Labels: areas/docs, areas/test, size/XS

#2437 fix: kata: workaround passthru net mode when get pod ip
  cri/v1alpha2/cri.go
Labels: LGTM, kind/bug, size/XS

#2435 feature: set debug trace back all
  pkg/debug/debug.go
Labels: kind/bug, kind/feature, size/XS

#2441 fix(kata): use `vm` other than `runv` as annotations
  cri/v1alpha2/cri.go
Labels: LGTM, areas/runv, size/XS

#2436 feature: change the function name about prometheus registry
  apis/metrics/metrics.go
  cri/metrics/metrics.go
  pkg/utils/metrics/metrics.go
Labels: areas/monitoring, kind/feature, size/S

#2413 feature: support api plugin
  Makefile
  apis/metrics/metrics.go
  apis/server/cri_bridge.go
  apis/server/router.go
  apis/server/server.go
  apis/server/system_bridge.go
  apis/server/types/handler.go
  cri/metrics/metrics.go
  daemon/daemon.go
  docs/features/pouch_with_plugin.md
  hookplugins/APIPlugin.go
  hookplugins/apiplugin/apiplugin.go
  pkg/utils/identify.go
  pkg/utils/identify_test.go
Labels: kind/feature, size/XL

#2379 refector: refect the pouch's volume module
  daemon/mgr/container_storage.go
  daemon/mgr/volume.go
  pkg/errtypes/errors.go
  pkg/errtypes/volume_errors.go
  pkg/serializer/interfaces.go
  pkg/serializer/serialize.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  storage/quota/grpquota.go
  storage/quota/prjquota.go
  storage/quota/quota.go
  storage/volume/README.md
  storage/volume/core.go
  storage/volume/core_test.go
  storage/volume/driver/driver_interface.go
  storage/volume/driver/fake_driver.go
  storage/volume/driver/remote.go
  storage/volume/error/errors.go
  storage/volume/examples/demo/demo.go
  storage/volume/modules/local/local.go
  storage/volume/modules/tmpfs/tmpfs.go
  storage/volume/types/meta/meta.go
  storage/volume/types/meta/types.go
  storage/volume/types/selector.go
  storage/volume/types/volume.go
  storage/volume/types/volume_util.go
  storage/volume/types/volume_util_test.go
  test/cli_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/XXL

#2442 ci: add deadcode checking in gometalinter
  .circleci/config.yml
  ctrd/utils.go
Labels: areas/test, size/S

#2439 doc: update requirement about golang and linux kernel
  INSTALLATION.md
  cli/version.go
Labels: LGTM, areas/docs, areas/test, size/S

#2443 bugfix: use netNSPath dynamically
  cri/ocicni/cni_manager.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_types.go
  cri/v1alpha2/cri_utils.go
Labels: LGTM, kind/bug, size/L

#2451 bugfix: use a fixed version of cni instead of the branch of master
  hack/install/install_cni.sh
Labels: areas/network, kind/bug, size/S

#2446 bugfix: fix some meaningless cli option type
  apis/opts/config/blkio.go
  apis/opts/config/runtime.go
  apis/opts/config/ulimit.go
Labels: kind/bug, size/XS

#2410 feature: support images filter flag
  apis/filters/parse.go
  apis/filters/parse_test.go
  apis/server/image_bridge.go
  apis/swagger.yml
  cli/events.go
  cli/image_list.go
  client/image_list.go
  client/image_list_test.go
  client/interface.go
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
  daemon/mgr/image.go
  daemon/mgr/system.go
  test/api_image_list_test.go
  test/cli_images_test.go
  test/cli_run_test.go
  test/environment/cleanup.go
Labels: LGTM, kind/feature, size/XL

#2438 docs: pouch with gVisor
  docs/features/pouch_with_gVisor.md
Labels: LGTM, areas/docs, size/M

#2474 fix: make cpuquota, MemorySwappiness validation compatible with docker
  apis/server/container_bridge.go
  apis/server/exec_bridge.go
  apis/server/network_bridge.go
  apis/server/volume_bridge.go
  apis/swagger.yml
  apis/types/resources.go
  daemon/mgr/container_validation.go
  test/cli_run_memory_test.go
Labels: kind/bug, size/M

#2479 doc: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: areas/docs, size/M

#2468 docs: fix dead link in dragonfly
  docs/features/pouch_with_dragonfly.md
Labels: LGTM, areas/docs, size/XS

#2478 change flags from --ports to --publish
  cli/common_flags.go
Labels: LGTM, size/XS

#2477 bugfix: fix incorrect mountpoint size if running container with tmpfs volume
  storage/volume/modules/tmpfs/tmpfs.go
  test/cli_run_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/S

#2465 linter: add markdown-link-check to check links whether alive
  .circleci/config.yml
  apis/README.md
  storage/volume/README.md
Labels: LGTM, size/S

#2464 feature: add volume ls quiet flag support
  cli/volume.go
  test/cli_volume_test.go
  test/environment/cleanup.go
Labels: areas/storage, kind/feature, size/L

#2428 feature: use ringBuffer to make log not blocking and make it configurable
  daemon/containerio/io.go
  daemon/logger/logbuffer/list.go
  daemon/logger/logbuffer/logbuff.go
  daemon/logger/logbuffer/ringbuff.go
  daemon/logger/logbuffer/ringbuff_test.go
  daemon/logger/types.go
  daemon/mgr/container.go
  daemon/mgr/container_validation.go
Labels: areas/log, kind/feature, size/XL

#2484 release: PouchContainer 1.0.1 version
  Makefile
  version/version.go
Labels: LGTM, size/XS

#2494 circleci: disable megacheck since it consumes more memory
  .circleci/config.yml
Labels: LGTM, areas/test, size/XS

#2330 test: api_blkio_test: add new checkpoints
  apis/opts/config/blkio_test.go
Labels: LGTM, areas/test, size/XL

#2502 fix indentation and typo in command help description
  cli/events.go
  cli/image_list.go
  cli/info.go
  cli/pause.go
  cli/rmi.go
  cli/start.go
  cli/stop.go
  cli/top.go
  cli/unpause.go
  cli/update_daemon.go
  cli/upgrade.go
Labels: LGTM, areas/cli, areas/typo, size/S

#2506 test: fix blkio test case
  apis/opts/config/blkio_test.go
Labels: areas/test, size/XS

#2510 bugfix: cleanup containerd container before do restart policy
  ctrd/client.go
  ctrd/interface.go
  ctrd/watch.go
  daemon/mgr/container.go
Labels: LGTM, kind/bug, size/S

#2504 test: fix some bugs for test
  hack/testing/run_daemon_integration.sh
  hack/testing/utils.sh
  test/api_system_test.go
  test/cli_inspect_test.go
  test/cli_network_test.go
  test/util_daemon.go
Labels: areas/test, kind/bug, size/M

#2496 test: refactor volume test
  test/cli_volume_test.go
Labels: LGTM, areas/storage, areas/test, kind/refactor, size/M

#2498 enhance: add meaningful field in log/error msg
  cri/stream/portforward/httpstream.go
  ctrd/container.go
Labels: areas/log, kind/bug, size/XS

#2396 bugfix: fix that cannot create network with --ipam-opt
  cli/network.go
  test/cli_network_test.go
Labels: LGTM, areas/network, kind/bug, size/S

#2503 bugfix: generate sandboxId to be stored advanced
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
Labels: LGTM, kind/bug, size/L

#2431 fix: fail to resolve correct target directory from home-dir
  main.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: LGTM, kind/bug, size/L

#2427 bugfix: can't recover the container whose restart-policy is always when host restart
  daemon/daemon.go
  daemon/mgr/container.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/bug, size/XL

#2520 test: complete criu test
  test/cli_start_test.go
Labels: areas/test, size/S
