Repository alibaba/pouch, pull requests merged in 2019-03, with the labels that each got.

#2728 bugfix: fix can't set quota with ".*"
  daemon/mgr/container_storage.go
  storage/quota/quota.go
  storage/quota/quota_test.go
  storage/quota/type.go
Labels: kind/bug, size/XL

#2735 fix runc install dependencies to libseccomp-devel in centos
  hack/install/install_runc.sh
Labels: areas/test, os/centos, size/XS

#2737 Revert "test: increate the memory limit to TestRunWithMemoryswap2x"
  test/cli_run_memory_test.go
Labels: areas/test, size/XS

#2736 daemon/mgr/image: update deadline for loading images
  daemon/mgr/image.go
Labels: size/XS

#2739 multisnapshotter: set snapshotter in container config
  daemon/mgr/container.go
Labels: size/S

#2741 bugfix: skip error when failed to set disk quota
  daemon/mgr/container_storage.go
Labels: kind/bug, size/XS

#2742 ctrd: ignore not found error in clean process
  ctrd/container.go
Labels: LGTM, kind/bug, size/XS

#2743 feature: add set mac address for pouch cli
  cli/common_flags.go
  cli/container.go
  test/cli_run_network_test.go
Labels: kind/feature, size/S

#2747 test: make test run faster
  Makefile
  hack/testing/run_daemon_integration.sh
Labels: areas/test, size/XS

#2745 feature: make env support inputting empty value when creation
  apis/opts/env.go
  apis/opts/env_test.go
  apis/swagger.yml
  cli/common_flags.go
  cli/update.go
  daemon/mgr/container_utils.go
  daemon/mgr/container_utils_test.go
  test/cli_create_test.go
  test/cli_update_test.go
Labels: kind/feature, size/XL

#2751 test: pull image before using it
  test/api_container_restart_test.go
  test/api_version_parameter_test.go
  test/cli_checkpoint_test.go
  test/cli_container_commit_test.go
Labels: LGTM, areas/test, size/XS

#2748 feature: independent runtime root
  ctrd/container.go
Labels: LGTM, kind/feature, size/XS

#2753 docs: add missing details generated by swagger
  apis/types/container_config.go
  apis/types/update_config.go
Labels: areas/docs, size/XS

#2755 test: pull image before using it
  test/api_image_list_test.go
Labels: areas/test, size/XS

#2754 swagger: update some defines
  apis/swagger.yml
  apis/types/resources.go
  cli/common_flags.go
  test/cli_create_test.go
Labels: LGTM, size/L

#2758 Revert "feature: independent runtime root"
  ctrd/container.go
Labels: kind/feature, size/XS

#2761 test: increase waiting time for daemon related test
  test/cli_rich_container_test.go
Labels: LGTM, areas/test, size/XS

#2763 ctrd: fix not set mediaType in manifest when commit image
  ctrd/image_commit.go
Labels: size/S

#2760 feature: add disable-bridge switch
  cli/update_daemon.go
  network/config.go
  network/mode/init.go
  test/daemon/daemon.go
  test/daemonv2/daemon.go
  test/daemonv2/types.go
  test/z_cli_daemon_test.go
Labels: kind/feature, size/XL

#2757 fix: should not start a paused container
  daemon/mgr/container.go
  test/api_container_start_test.go
Labels: kind/bug, size/XS

#2744 feature: copy ownship when do copy image content
  daemon/mgr/container_storage.go
  daemon/mgr/container_storage_test.go
  travis_ci.sh
Labels: LGTM, kind/feature, size/M

#2769 cri: diable snapshotter usage collector by default
  cri/config/config.go
  cri/v1alpha1/cri.go
  cri/v1alpha2/cri.go
  daemon/config/config_test.go
  main.go
Labels: LGTM, size/S

#2772 fix: dont set status to exit for oom condition
  daemon/mgr/container_state.go
Labels: LGTM, kind/bug, size/XS

#2777 bugfix: not save ExecIds to meta.json file
  daemon/mgr/container_types.go
Labels: areas/test, kind/bug, size/XS

#2782 version: bump to v1.3.0
  Makefile
  version/version.go
Labels: size/XS

#2766 test: add override default mount config test
  test/cli_run_volume_test.go
Labels: areas/test, kind/refactor, size/S

#2784 cgroup: make cgroup-parent absolute path
  daemon/mgr/spec_linux.go
  test/cli_run_cgroup_test.go
Labels: LGTM, size/S
