Repository alibaba/pouch, pull requests merged in 2019-01, with the labels that each got.

#2639 fix typos in comment
  cli/cli.go
  pkg/jsonstream/format.go
Labels: LGTM, areas/typo, size/XS

#2635 bugfix: should add snapshot gc label to config
  ctrd/image_commit.go
Labels: kind/bug, size/L

#2631 feature: Allow multi snapshotters
  ctrd/client.go
  ctrd/interface.go
  daemon/config/config.go
  daemon/daemon.go
  daemon/daemon_utils.go
  main.go
  test/cli_snapshotter_test.go
Labels: LGTM, kind/feature, size/L

#2651 fix: outdated x509 key pair for testing
  daemon/logger/syslog/test/ca-key.pem
  daemon/logger/syslog/test/ca.pem
  daemon/logger/syslog/test/generate_x509_pair.sh
Labels: areas/test, kind/bug, priority/P1, size/L

#2647 fix: wrong time unit in storage plugin
  storage/plugins/client.go
Labels: LGTM, areas/storage, kind/bug, size/XS

#2627 docs: add two maintainers and component owner/backup policy for project
  MAINTAINERS.md
Labels: LGTM, areas/docs, size/S

#2643 test: add new checkpoint for apis/opts/config/runtime.go
  apis/opts/config/runtime_test.go
Labels: LGTM, areas/test, size/L

#2652 test: use runc build from source code
  hack/install/install_runc.sh
Labels: areas/test, size/M

#2614 bugfix: do not return stop container time out error
  ctrd/container.go
Labels: kind/bug, size/XS

#2653 refactor: refact the setup spec mount
  daemon/mgr/spec_mount.go
Labels: LGTM, kind/refactor, size/M

#2656 test: try to make TestRunRestartPolicyNone case happy
  test/cli_run_test.go
  test/util/util.go
Labels: LGTM, areas/test, size/S

#2657 test: change test image
  test/cli_container_commit_test.go
  test/cli_logs_test.go
Labels: LGTM, areas/test, size/S

#2658 test: make TestPouchRestartExitedContainer be happy
  test/cli_restart_test.go
Labels: LGTM, areas/test, size/XS

#2645 test: add new checkpoint for apis/opts/config/ulimit.go
  apis/opts/config/ulimit_test.go
Labels: areas/test, size/M

#2591 test: upgrade cri e2e test to v1.12
  hack/testing/run_daemon_cri_e2e.sh
Labels: areas/test, size/XS

#2617 bugfix: support rich mode container
  daemon/mgr/container_rich_mode.go
  daemon/mgr/container_rich_mode_test.go
  daemon/mgr/container_validation.go
  docs/features/pouch_with_rich_container.md
  test/cli_rich_container_test.go
Labels: kind/bug, size/XL

#2660 delete omitempty from Privileged in api
  apis/swagger.yml
  apis/types/host_config.go
  test/cli_inspect_test.go
Labels: size/S

#2638 test: add test cases for diskquota_test.go
  apis/opts/diskquota.go
  apis/opts/diskquota_test.go
Labels: LGTM, areas/storage, areas/test, size/XS

#2665 bugfix: flaky test case in cli_start_test.go
  cli/create.go
  test/cli_start_test.go
  vendor/github.com/kr/pty/License
  vendor/github.com/kr/pty/README.md
  vendor/github.com/kr/pty/doc.go
  vendor/github.com/kr/pty/ioctl.go
  vendor/github.com/kr/pty/ioctl_bsd.go
  vendor/github.com/kr/pty/mktypes.bash
  vendor/github.com/kr/pty/pty_darwin.go
  vendor/github.com/kr/pty/pty_dragonfly.go
  vendor/github.com/kr/pty/pty_freebsd.go
  vendor/github.com/kr/pty/pty_linux.go
  vendor/github.com/kr/pty/pty_unsupported.go
  vendor/github.com/kr/pty/run.go
  vendor/github.com/kr/pty/util.go
  vendor/github.com/kr/pty/ztypes_386.go
  vendor/github.com/kr/pty/ztypes_amd64.go
  vendor/github.com/kr/pty/ztypes_arm.go
  vendor/github.com/kr/pty/ztypes_arm64.go
  vendor/github.com/kr/pty/ztypes_dragonfly_amd64.go
  vendor/github.com/kr/pty/ztypes_freebsd_386.go
  vendor/github.com/kr/pty/ztypes_freebsd_amd64.go
  vendor/github.com/kr/pty/ztypes_freebsd_arm.go
  vendor/github.com/kr/pty/ztypes_mipsx.go
  vendor/github.com/kr/pty/ztypes_ppc64.go
  vendor/github.com/kr/pty/ztypes_ppc64le.go
  vendor/github.com/kr/pty/ztypes_s390x.go
  vendor/vendor.json
Labels: LGTM, areas/test, kind/bug, size/XXL

#2640 feature: add stats cli command
  cli/main.go
  cli/stats.go
  cli/stats_helpers.go
  daemon/mgr/container_stats.go
  daemon/mgr/network.go
  test/api_container_stats_test.go
  test/cli_stats_test.go
  vendor/github.com/docker/go-units/CONTRIBUTING.md
  vendor/github.com/docker/go-units/MAINTAINERS
  vendor/github.com/docker/go-units/circle.yml
  vendor/github.com/docker/go-units/duration.go
  vendor/github.com/docker/go-units/size.go
  vendor/vendor.json
Labels: LGTM, areas/cli, kind/feature, size/XXL

#2666 fix: avoid daemon start hang when one shim hang
  ctrd/container.go
Labels: LGTM, kind/bug, size/S

#2661 ctrd: try to fix fail to destroy container
  ctrd/container.go
Labels: LGTM, containerd-related, size/XS

#2458 bugfix: fix images filter when show multi-tag images
  daemon/mgr/image.go
  test/api_image_list_test.go
Labels: kind/bug, size/M

#2670 feature: make pouchd support generating command line docs
  docs/commandline/pouchd.md
  docs/commandline/pouchd_gen-doc.md
  gen_doc.go
  main.go
Labels: areas/cli, areas/docs, kind/feature, size/XL

#2623 feature: extend cri apis for support pause/unpause container
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/v1alpha2/container_pause.go
  cri/v1alpha2/container_unpause.go
  docs/kubernetes/pouch_cri_api_changelog.md
  hack/protoc/protoc.sh
  pkg/utils/metrics/actions.go
Labels: kind/feature, size/XXL

#2641 feature: support push image in daemon side
  apis/server/image_bridge.go
  apis/server/router.go
  apis/swagger.yml
  cli/pull.go
  client/image_push.go
  client/image_push_test.go
  client/interface.go
  ctrd/image.go
  ctrd/interface.go
  ctrd/utils.go
  daemon/mgr/image.go
  pkg/jsonstream/image_progress.go
  pkg/jsonstream/image_push.go
  test/api_image_push_test.go
Labels: kind/feature, size/XL

#2668 bugfix: should initialize ContainerIO for all container
  daemon/mgr/container.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/bug, size/M

#2675 bugfix: /etc/mtab will miss quota id
  daemon/mgr/container_storage.go
  storage/quota/quota.go
Labels: LGTM, kind/bug, size/S

#2616 feature: support cgroup systemd driver
  ctrd/container.go
  ctrd/container_types.go
  daemon/config/config.go
  daemon/config/config_test.go
  daemon/mgr/container.go
  daemon/mgr/spec.go
  daemon/mgr/spec_linux.go
  main.go
  test/environment/env.go
  test/z_cli_daemon_test.go
Labels: kind/feature, size/L

#2683 upgrade: move to 1.2.0
  Makefile
  version/version.go
Labels: LGTM, size/XS

#2673 test: refact travis-ci
  .gitignore
  .travis.yml
  Makefile
  hack/install/config.sh
  hack/install/install_critest.sh
  hack/install/install_criu.sh
  hack/install/install_nsenter.sh
  hack/install/install_runc.sh
  hack/testing/run_daemon_cri_integration.sh
  hack/testing/run_daemon_integration.sh
  hack/testing/utils.sh
  travis_ci.sh
Labels: areas/test, size/XL

#2678 bugfix: make sure SnapshotID not empty when start container
  daemon/mgr/container.go
Labels: kind/bug, size/XS

#2682 bugfix: check old volume mode
  daemon/mgr/container_storage.go
Labels: LGTM, areas/storage, kind/bug, size/S

#2684 bugfix: fix wrongly update cpu-quota to 0
  daemon/mgr/container.go
  test/cli_run_cgroup_test.go
  test/cli_update_test.go
Labels: LGTM, kind/bug, size/L

#2686 test: skip the flay case
  test/z_cli_daemon_test.go
Labels: LGTM, areas/test, size/XS

#2690 test: shouldn't use string to convert int64 to string
  test/cli_update_test.go
Labels: LGTM, areas/test, size/XS

#2677 docs: add doc to describe how to use `pouch run --log-driver`
  docs/features/pouch_with_log_driver.md
Labels: areas/docs, areas/log, kind/question, size/M

#2693 test: skip test cgroup parent when use cgroup ns
  test/cli_run_cgroup_test.go
  test/util/util.go
Labels: LGTM, areas/test, size/M

#2692 test: change oss endpoint
  hack/install/config.sh
Labels: LGTM, areas/test, size/XS

#2679 bugfix: fix containerd pid may be reuse
  ctrd/supervisord/daemon.go
  test/z_cli_daemon_test.go
Labels: LGTM, kind/bug, size/M

#2681 feature: CONTAINER_PAUSE state for CRI
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: LGTM, kind/feature, size/XXL

#2687 feature: exposed rootfs path of the container through inspect command
  apis/server/container_bridge.go
  apis/swagger.yml
  apis/types/container_json.go
  test/cli_inspect_test.go
Labels: LGTM, areas/cli, kind/feature, size/S

#2691 support update daemon with home-dir and snapshotter
  cli/update_daemon.go
  test/z_cli_daemon_test.go
Labels: LGTM, size/M

#2700 support memory swap by CRI
  cri/annotations/annotations.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: areas/cri, size/L

#2680 fix: update container state according to containerd events
  daemon/mgr/container.go
  daemon/mgr/container_state.go
  daemon/mgr/events.go
Labels: kind/bug, size/M

#2699 bugfix: we should get a container's execids from inspect
  apis/server/container_bridge.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  pkg/collect/safe_map.go
  pkg/collect/safe_map_test.go
  test/cli_inspect_test.go
Labels: areas/test, kind/bug, size/L
