Repository alibaba/pouch, pull requests merged in 2019-06, with the labels that each got.

#2872 test: modify the env test
  test/cli_create_test.go
Labels: LGTM, areas/test, size/XS

#2850 feature: search the images from specific registry
  apis/server/image_bridge.go
  apis/swagger.yml
  cli/main.go
  cli/search.go
  client/image_search.go
  client/image_search_test.go
  client/interface.go
  daemon/mgr/image.go
  registry/types/search_result_resp.go
  test/api_image_search_test.go
  test/cli_search_test.go
Labels: areas/images, areas/test, kind/feature, size/XL

#2879 feature: add pouch cp cmd
  apis/server/copy_bridge.go
  apis/server/router.go
  apis/swagger.yml
  apis/types/container_path_stat.go
  cli/cp.go
  cli/main.go
  client/container_copy.go
  client/interface.go
  client/request.go
  daemon/mgr/container.go
  daemon/mgr/container_copy.go
  daemon/mgr/container_storage.go
  pkg/ioutils/reader.go
  test/api_container_cp_test.go
  test/cli_container_cp_test.go
  test/request/request.go
Labels: kind/feature, size/XXL

#2870 feature: cli supports --env-file
  cli/common_flags.go
  cli/container.go
  cli/create.go
  cli/envfile.go
  cli/envfile_test.go
  cli/run.go
  test/cli_create_test.go
  test/cli_run_test.go
  test/util/util.go
Labels: kind/feature, size/XL

#2889 feature: add kernel info to EngineVersion metric
  apis/metrics/metrics.go
  main.go
  test/api_system_metrics_test.go
  test/util_api.go
Labels: kind/feature, size/M

#2876 fix: fix invalid memory limit
  daemon/config/config.go
  daemon/mgr/container_stats.go
  main.go
Labels: kind/bug, size/S

#2891 Add test information in cli_version_test.go
  test/cli_version_test.go
Labels: LGTM, areas/test, size/XS

#2899 copy: should not mount rootfs again
  daemon/mgr/container_copy.go
  daemon/mgr/container_storage.go
Labels: size/L

#2895 feature: add pouch port cmd
  cli/main.go
  cli/port.go
  test/cli_container_cp_test.go
  test/cli_container_port_test.go
Labels: LGTM, kind/feature, size/XL

#2901 fix: fix runv configure doc
  docs/features/pouch_with_runV.md
Labels: LGTM, areas/runv, kind/bug, size/XS

#2903 fix docs: add taint step to enable schedule on master
  docs/kubernetes/pouch_with_kubernetes_deploying.md
Labels: areas/docs, size/XS

#2902 fix: distinguish image name and ref
  ctrd/image.go
  ctrd/interface.go
  ctrd/utils.go
  daemon/mgr/image.go
Labels: kind/bug, size/XL

#2905 fix: search images api methods
  apis/server/router.go
  client/image_search.go
  client/image_search_test.go
  test/api_image_search_test.go
Labels: kind/bug, size/XS

#2909 upgrade: bump to Go 1.12.6
  .travis.yml
  Dockerfile
  Vagrantfile
  ctrd/utils.go
  test/z_cli_daemon_test.go
Labels: size/XS

#2911 doc: add Aliyun Linux 2 support to INSTALLATION.md
  INSTALLATION.md
Labels: areas/docs, size/S

#2904 feature: cri support update runtime config
  cri/config/config.go
  cri/ocicni/cni_manager.go
  cri/ocicni/interface.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  main.go
  vendor/github.com/containernetworking/cni/CODE-OF-CONDUCT.md
  vendor/github.com/containernetworking/cni/CONTRIBUTING.md
  vendor/github.com/containernetworking/cni/CONVENTIONS.md
  vendor/github.com/containernetworking/cni/DCO
  vendor/github.com/containernetworking/cni/Documentation/cnitool.md
  vendor/github.com/containernetworking/cni/Documentation/spec-upgrades.md
  vendor/github.com/containernetworking/cni/GOVERNANCE.md
  vendor/github.com/containernetworking/cni/MAINTAINERS
  vendor/github.com/containernetworking/cni/README.md
  vendor/github.com/containernetworking/cni/RELEASING.md
  vendor/github.com/containernetworking/cni/ROADMAP.md
  vendor/github.com/containernetworking/cni/SPEC.md
  vendor/github.com/containernetworking/cni/Vagrantfile
  vendor/github.com/containernetworking/cni/cnitool/README.md
  vendor/github.com/containernetworking/cni/cnitool/cnitool.go
  vendor/github.com/containernetworking/cni/libcni/api.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/logo.png
  vendor/github.com/containernetworking/cni/pkg/invoke/args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/cni_args.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/invoke/fakes/version_decoder.go
  vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
  vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
  vendor/github.com/containernetworking/cni/pkg/skel/skel.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/github.com/containernetworking/cni/pkg/version/legacy_examples/example_runtime.go
  vendor/github.com/containernetworking/cni/pkg/version/legacy_examples/examples.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/github.com/containernetworking/cni/pkg/version/testhelpers/testhelpers.go
  vendor/github.com/containernetworking/cni/pkg/version/version.go
  vendor/github.com/containernetworking/cni/plugins/test/noop/debug/debug.go
  vendor/github.com/containernetworking/cni/plugins/test/noop/main.go
  vendor/github.com/containernetworking/cni/scripts/docker-run.sh
  vendor/github.com/containernetworking/cni/scripts/exec-plugins.sh
  vendor/github.com/containernetworking/cni/scripts/priv-net-run.sh
  vendor/github.com/containernetworking/cni/scripts/release.sh
  vendor/github.com/containernetworking/cni/test.sh
  vendor/github.com/cri-o/ocicni/Makefile
  vendor/github.com/cri-o/ocicni/OWNERS
  vendor/github.com/cri-o/ocicni/README.md
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
  vendor/github.com/cri-o/ocicni/vendor.conf
  vendor/vendor.json
Labels: LGTM, kind/feature, size/XXL

#2910 upgrade: bump critest and k8s e2e test to 1.14
  daemon/logger/crilog/log.go
  hack/install/install_critest.sh
  hack/testing/run_daemon_cri_e2e.sh
  hack/testing/run_daemon_cri_integration.sh
Labels: areas/test, size/S

#2922 bugfix: fix update container rootfs disk quota recursively timeout
  daemon/mgr/container.go
  daemon/mgr/container_storage.go
  storage/quota/quota.go
Labels: kind/bug, size/S

#2914 fix: pull should return 404 when image not exists
  apis/server/image_bridge.go
  ctrd/image.go
  ctrd/interface.go
  ctrd/utils.go
  daemon/mgr/image.go
  test/api_image_create_test.go
  test/z_cli_daemon_test.go
Labels: kind/bug, size/M
