Repository alibaba/pouch, pull requests merged in 2019-04, with the labels that each got.

#2781 support to update memory swap by cri
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: size/S

#2717 feature: add kernel-memory support in cli and ctrd
  cli/common_flags.go
  cli/container.go
  ctrd/utils.go
  daemon/mgr/spec_linux.go
  test/cli_run_memory_test.go
Labels: kind/feature, size/L

#2765 cri: remove v1alpha1 codebase
  Makefile
  cri/criservice.go
  cri/v1alpha1/cri.go
  cri/v1alpha1/cri_stream.go
  cri/v1alpha1/cri_stream_test.go
  cri/v1alpha1/cri_types.go
  cri/v1alpha1/cri_utils.go
  cri/v1alpha1/cri_utils_test.go
  cri/v1alpha1/cri_wrapper.go
  cri/v1alpha1/server.go
  cri/v1alpha1/service/cri.go
  hack/install/install_critest.sh
  hack/testing/run_daemon_cri_e2e.sh
  hack/testing/run_daemon_cri_integration.sh
  travis_ci.sh
Labels: size/XXL

#2756 [RFC]refactor: refact the container lock
  apis/swagger.yml
  apis/types/container_state.go
  daemon/mgr/container.go
  daemon/mgr/container_checkpoint.go
  daemon/mgr/container_exec.go
  daemon/mgr/container_logs.go
  daemon/mgr/container_state.go
  daemon/mgr/container_stats.go
  daemon/mgr/container_storage.go
  daemon/mgr/container_types.go
  daemon/mgr/container_upgrade.go
  daemon/mgr/spec.go
Labels: kind/refactor, size/XL

#2793 refactor: change proto fields number
  cri/apis/v1alpha2/api.pb.go
  cri/apis/v1alpha2/api.proto
Labels: kind/refactor, size/XL

#2796 bugfix: trim specific characters in Kernel version
  pkg/kernel/kernel.go
  pkg/kernel/kernel_test.go
Labels: areas/test, kind/bug, size/S

#2791 cri support to update pids limit by annotation
  cri/annotations/annotations.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
Labels: size/M

#2798 bugfix: fix error to set volume options
  apis/opts/config/volumes.go
  apis/opts/config/volumes_test.go
  cli/common_flags.go
  cli/container.go
  test/cli_run_volume_test.go
Labels: LGTM, areas/storage, kind/bug, size/XL

#2799 bugfix: remove comment line
  cli/common_flags.go
Labels: LGTM, kind/bug, size/XS

#2792 fix: ensure there is a non-empty runtime name in sandbox metadata
  cri/v1alpha2/cri_utils.go
Labels: kind/bug, size/XS

#2797 support to set root dir of container log
  daemon/mgr/container.go
  daemon/mgr/container_logger.go
  daemon/mgr/container_logs.go
  daemon/mgr/container_validation.go
  main.go
  test/cli_logs_test.go
  test/z_cli_daemon_test.go
Labels: LGTM, areas/log, size/XL

#2806 bugfix: fix pouch panic on fatal error: concurrent map read and map write.
  ctrd/container.go
  ctrd/watch.go
  daemon/mgr/container.go
  daemon/mgr/events.go
  test/cli_events_test.go
Labels: kind/bug, kind/panic, priority/P1, size/M

#2802 fix: allow to stats not-running container
  cli/stats_helpers.go
  cri/v1alpha2/cri_utils.go
  daemon/mgr/container_stats.go
  test/cli_stats_test.go
Labels: kind/bug, size/L

#2809 ctrd: support to show shim log
  ctrd/supervisord/config.go
  ctrd/supervisord/option.go
  daemon/daemon.go
Labels: LGTM, areas/log, size/S

#2810 ctrd/daemon: support PlainHttp pull/push image
  ctrd/client.go
  ctrd/client_opts.go
  ctrd/client_opts_test.go
  ctrd/image.go
  ctrd/utils.go
  daemon/config/config.go
  daemon/daemon.go
  main.go
Labels: LGTM, size/XL

#2820 bugfix: fix lease used by pouchd may be expired
  ctrd/client.go
  ctrd/wrapper_client.go
Labels: kind/bug, size/L
