Repository alibaba/pouch, pull requests merged in 2019-02, with the labels that each got.

#2710 test: increate the memory limit to TestRunWithMemoryswap2x
  test/cli_run_memory_test.go
Labels: areas/test, size/XS

#2711 update extend annotation field of memory swap
  cri/annotations/annotations.go
Labels: size/XS

#2708 feature: update blkio device's read/write Bps/IOps
  cli/update.go
  ctrd/utils.go
  daemon/mgr/container.go
  daemon/mgr/spec_linux.go
  test/cli_update_test.go
Labels: LGTM, kind/feature, size/XL

#2715 fix: fix typo
  daemon/mgr/container.go
  daemon/mgr/network.go
Labels: LGTM, areas/typo, kind/bug, size/XS

#2718 test: make test run happy
  test/cli_network_test.go
  test/cli_run_dns_test.go
  test/cli_run_test.go
Labels: areas/test, size/S

#2721 pkg/cri: remove useless code
  cri/stream/httpstream/spdy/connection.go
  pkg/exec/exec.go
  pkg/user/user.go
Labels: LGTM, size/XL

#2719 cri/pkg: use our own interceptor grpc chain function
  cri/v1alpha2/service.go
  pkg/grpc/interceptor/chain.go
  pkg/grpc/interceptor/chain_test.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/CHANGELOG.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/CONTRIBUTING.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/DOC.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/Gopkg.lock
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/Gopkg.toml
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/README.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/makefile
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/slack.png
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
  vendor/vendor.json
Labels: size/XXL

#2726 support annotation in container update api
  apis/swagger.yml
  apis/types/update_config.go
  cli/update.go
  daemon/mgr/container.go
  daemon/mgr/container_utils.go
  test/cli_update_test.go
Labels: LGTM, size/L

#2720 bugfix: we should make MaskedPaths and ReadonlyPaths to be nil when privileged be set
  apis/swagger.yml
  apis/types/container_config.go
  apis/types/host_config.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
  cri/v1alpha2/cri_utils_test.go
  daemon/mgr/container.go
  daemon/mgr/container_types.go
  daemon/mgr/spec_linux.go
Labels: kind/bug, size/L

#2704 refact: refact disk quota api
  apis/opts/diskquota.go
  apis/opts/diskquota_test.go
  cli/container.go
  daemon/mgr/container.go
  daemon/mgr/container_storage.go
  daemon/mgr/container_validation.go
  docs/features/pouch_with_diskquota.md
  storage/quota/quota.go
  storage/quota/quota_test.go
  storage/quota/type.go
  test/cli_run_volume_test.go
Labels: size/XL
