Repository alibaba/pouch, pull requests merged in 2019-10, with the labels that each got.

#2933 fix: make more events available to user
  daemon/mgr/container.go
  daemon/mgr/container_commit.go
  daemon/mgr/container_copy.go
  daemon/mgr/container_exec.go
  daemon/mgr/image.go
  daemon/mgr/image_load.go
  daemon/mgr/image_save.go
  daemon/mgr/volume.go
  test/cli_events_test.go
Labels: areas/cli, kind/bug, size/S

#2984 avoid exec_die filed before exec_start
  daemon/mgr/container_exec.go
Labels: size/XS

#2980 Makefile: add commit for the version
  Makefile
Labels: size/XS

#2985 wait until all the on going requests go to a stable state before shuti…
  .gitignore
  apis/server/router.go
  apis/server/server.go
  main.go
Labels: size/S

#2982 fix: compatiable with legacy and newly pod when stop pod
  cri/v1alpha2/cri.go
Labels: kind/bug, size/S

#2988 enlarge timeout when pouch start
  ctrd/container.go
  ctrd/supervisord/daemon.go
Labels: size/S

#2991 fix node e2e test
  daemon/mgr/container_utils.go
Labels: areas/test, size/S
