Repository alibaba/pouch, pull requests merged in 2019-07, with the labels that each got.

#2927 bugfix: removing image by ID should conflict with running container.
  apis/server/image_bridge.go
  test/cli_rmi_test.go
  test/environment/cleanup.go
Labels: kind/bug, size/M

#2939 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: LGTM, size/XS

#2938 [bugfix] LogOpts doesn't take effect in pouchd config file
  main.go
Labels: areas/log, kind/bug, size/XS

#2928 bugfix: create container with invalid name
  daemon/config/config.go
  daemon/mgr/container.go
  test/cli_create_log_options_test.go
  test/cli_create_test.go
Labels: kind/bug, size/S

#2949 fix: dynamic reload cni default config
  vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
  vendor/vendor.json
Labels: LGTM, areas/network, kind/bug, size/M

#2946 feature: add exec timeout support
  apis/server/exec_bridge.go
  cri/stream/runtime.go
  cri/v1alpha2/cri.go
  ctrd/container.go
  ctrd/interface.go
  daemon/mgr/container.go
  daemon/mgr/container_exec.go
  hack/testing/run_daemon_cri_integration.sh
Labels: kind/feature, size/L
