Repository alibaba/pouch, pull requests merged in 2019-05, with the labels that each got.

#2821 fix: fix golint warning
  cri/v1alpha2/cri_utils.go
  daemon/config/config.go
Labels: LGTM, kind/bug, size/S

#2803 feature: compatible with both k8s and cri-o annotations
  cri/annotations/annotations.go
  cri/v1alpha2/cri.go
  cri/v1alpha2/cri_utils.go
Labels: kind/feature, size/S

#2829 ctrd: support to restart containerd if it is dead
  ctrd/supervisord/daemon.go
Labels: LGTM, size/L

#2824 fixes #2817 container run with the empty label
  apis/opts/labels.go
  apis/opts/labels_test.go
  cli/container.go
  daemon/mgr/container.go
Labels: size/M

#2816 feature: add Mountpoints in containers/json api
  apis/server/container_bridge.go
Labels: LGTM, kind/feature, size/XS

#2831 fix setup workDir will change the dir ownership on host
  daemon/mgr/container_storage.go
  daemon/mgr/container_types.go
Labels: LGTM, size/M

#2832 cli/ctrd: support push command cli
  cli/main.go
  cli/push.go
  ctrd/image.go
Labels: LGTM, areas/cli, size/M

#2759 feature: support containerd shim v2
  apis/swagger.yml
  apis/types/host_config.go
  apis/types/runtime.go
  ctrd/container.go
  ctrd/container_types.go
  daemon/daemon_utils.go
  daemon/mgr/container.go
  daemon/mgr/container_utils.go
  docs/features/pouch_with_gVisor.md
  vendor/github.com/containerd/containerd/runtime/v2/runc/options/doc.go
  vendor/github.com/containerd/containerd/runtime/v2/runc/options/next.pb.txt
  vendor/github.com/containerd/containerd/runtime/v2/runc/options/oci.pb.go
  vendor/github.com/containerd/containerd/runtime/v2/runc/options/oci.proto
  vendor/vendor.json
Labels: kind/feature, size/XXL

#2840 feature: support set ipv4 or ipv6 when create container
  apis/opts/networks.go
  cli/common_flags.go
  cli/container.go
  test/cli_run_network_test.go
Labels: kind/feature, size/L

#2838 remove useless break statement
  storage/quota/quota.go
Labels: size/XS

#2871 docs: modify a spelling mistake
  apis/README.md
Labels: LGTM, areas/docs, size/XS

#2874 feature: support registry mirrors
  ctrd/image.go
  ctrd/interface.go
  daemon/config/config.go
  daemon/config/config_test.go
  daemon/mgr/image.go
  daemon/mgr/system.go
  main.go
Labels: kind/feature, size/L

#2860 feature: cli supports --memory-reservation
  apis/opts/memory_reservation.go
  apis/opts/memory_reservation_test.go
  cli/common_flags.go
  cli/container.go
  daemon/mgr/container_types.go
  daemon/mgr/container_validation.go
  daemon/mgr/container_validation_test.go
  daemon/mgr/spec_linux.go
  pkg/system/cgroup.go
  test/cli_run_memory_test.go
  test/environment/env.go
Labels: kind/feature, size/XL

#2878 stats: check pointer before using metrics
  daemon/mgr/container_stats.go
Labels: size/M

#2855 bugfix: fix error when input 'inspect -f {{.Id}}'
  cli/inspect/inspector.go
  cli/inspect/inspector_test.go
  test/cli_inspect_test.go
Labels: areas/cli, kind/bug, size/S
